(() => {
  "use strict";
  const $=(id)=>document.getElementById(id), lines=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]], key="jasondaemon.tic-tac-toe.stats.v1";
  const cells=[];
  let board,turn,over,lastPlaced;
  function stats(){try{return JSON.parse(localStorage.getItem(key))||{wins:0,losses:0,draws:0};}catch{return{wins:0,losses:0,draws:0};}}
  function save(result){const s=stats();s[result]=(s[result]||0)+1;localStorage.setItem(key,JSON.stringify(s));GameScores.record({game:"tic-tac-toe",mode:$("mode").value,difficulty:$("difficulty").value,value:s.wins,meta:{result}});}
  function winner(b){for(const line of lines)if(b[line[0]]&&b[line[0]]===b[line[1]]&&b[line[0]]===b[line[2]])return{mark:b[line[0]],line};return b.every(Boolean)?{mark:"draw",line:[]}:null;}
  function render(){const result=winner(board);cells.forEach((cell,i)=>{cell.dataset.mark=board[i];cell.classList.toggle("win",!!result?.line.includes(i));cell.classList.toggle("placed",i===lastPlaced);cell.disabled=over||!!board[i];if(i===lastPlaced)cell.addEventListener("animationend",()=>cell.classList.remove("placed"),{once:true});});lastPlaced=-1;$("turn").textContent=over?"—":turn;const s=stats();$("stats").innerHTML=`Local record<br><strong>${s.wins||0} wins · ${s.losses||0} losses · ${s.draws||0} draws</strong>`;}
  function finish(result){over=true;if(result.mark==="draw"){$("result").textContent="Draw";$("message").textContent="Nobody found the opening. Try another round.";save("draws");}else{const cpu=$("mode").value==="cpu",human=result.mark==="X";$("result").textContent=`${result.mark} wins`;$("message").textContent=cpu?(human?"Nice line. You beat the computer.":"The computer found a line first."):`${result.mark} takes the round.`;save(cpu?(human?"wins":"losses"):"wins");}render();}
  function move(i,mark){if(over||board[i])return;board[i]=mark;lastPlaced=i;const result=winner(board);if(result)return finish(result);turn=mark==="X"?"O":"X";render();if($("mode").value==="cpu"&&turn==="O"){$("message").textContent="Computer is choosing…";setTimeout(cpuMove,260);}else $("message").textContent=`${turn}, choose a square.`;}
  function minimax(b,max){const result=winner(b);if(result)return result.mark==="O"?10:result.mark==="X"?-10:0;let best=max?-Infinity:Infinity;for(let i=0;i<9;i++)if(!b[i]){b[i]=max?"O":"X";const score=minimax(b,!max);b[i]="";best=max?Math.max(best,score):Math.min(best,score);}return best;}
  function cpuMove(){if(over)return;const open=board.map((value,i)=>value?null:i).filter((value)=>value!==null),difficulty=$("difficulty").value;let pick;if(difficulty==="easy")pick=open[Math.floor(Math.random()*open.length)];else{const winning=open.find((i)=>{const b=[...board];b[i]="O";return winner(b)?.mark==="O";}),block=open.find((i)=>{const b=[...board];b[i]="X";return winner(b)?.mark==="X";});if(winning!==undefined)pick=winning;else if(block!==undefined)pick=block;else if(difficulty==="medium"){const choices=!board[4]&&Math.random()<.75?[4]:open;pick=choices[Math.floor(Math.random()*choices.length)];}else{let best=-Infinity;for(const i of open){board[i]="O";const score=minimax(board,false);board[i]="";if(score>best){best=score;pick=i;}}}}move(pick,"O");}
  function reset(){board=Array(9).fill("");turn="X";over=false;lastPlaced=-1;$("result").textContent="In play";$("message").textContent=$("mode").value==="cpu"?"You are X. Choose a square.":"X goes first.";$("difficulty").hidden=$("mode").value!=="cpu";render();}
  for(let i=0;i<9;i++){const button=document.createElement("button");button.type="button";button.dataset.mark="";button.setAttribute("aria-label",`Square ${i+1}`);button.addEventListener("click",()=>move(i,turn));$("board").append(button);cells.push(button);}$("new").addEventListener("click",reset);$("mode").addEventListener("change",reset);reset();
})();
