(() => {
  "use strict";
  const SAVE_KEY = "jasondaemon.game.mines.state.v1";
  const configs = { easy:{rows:9,cols:9,mines:10}, medium:{rows:16,cols:16,mines:40}, hard:{rows:16,cols:30,mines:99} };
  const state = { difficulty:"easy",rows:9,cols:9,mines:10,cells:[],started:false,complete:false,won:false,flagMode:false,startTime:0,elapsed:0,timer:null };
  const $ = id => document.getElementById(id);
  const neighbors = index => { const row=Math.floor(index/state.cols),col=index%state.cols,out=[]; for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){if(!dr&&!dc)continue;const r=row+dr,c=col+dc;if(r>=0&&r<state.rows&&c>=0&&c<state.cols)out.push(r*state.cols+c)} return out };
  const formatTime = seconds => `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,"0")}`;
  const save = () => localStorage.setItem(SAVE_KEY, JSON.stringify({difficulty:state.difficulty,rows:state.rows,cols:state.cols,mines:state.mines,cells:state.cells,started:state.started,complete:state.complete,won:state.won,startTime:state.startTime,elapsed:state.elapsed}));
  const stopTimer = () => { if(state.timer) clearInterval(state.timer); state.timer=null };
  const startTimer = () => { stopTimer(); state.timer=setInterval(()=>{if(state.started&&!state.complete){state.elapsed=Math.max(0,Math.floor((Date.now()-state.startTime)/1000));updateReadout();save()}},500) };
  function newGame(difficulty=state.difficulty){const config=configs[difficulty]||configs.easy;stopTimer();Object.assign(state,{difficulty,...config,cells:Array.from({length:config.rows*config.cols},(_,index)=>({index,mine:false,open:false,flagged:false,adjacent:0,exploded:false,bad:false})),started:false,complete:false,won:false,flagMode:false,startTime:0,elapsed:0});document.body.className="";$("status").textContent="Reveal a square to start.";render();save()}
  function placeMines(safeIndex){const forbidden=new Set([safeIndex,...neighbors(safeIndex)]),candidates=state.cells.map(c=>c.index).filter(i=>!forbidden.has(i));for(let n=0;n<state.mines;n++){const pick=Math.floor(Math.random()*candidates.length);state.cells[candidates.splice(pick,1)[0]].mine=true}state.cells.forEach(cell=>cell.adjacent=cell.mine?0:neighbors(cell.index).filter(i=>state.cells[i].mine).length)}
  function reveal(index){const cell=state.cells[index];if(!cell||cell.open||cell.flagged||state.complete)return;if(!state.started){placeMines(index);state.started=true;state.startTime=Date.now()-state.elapsed*1000;startTimer()}if(cell.mine){cell.open=true;cell.exploded=true;lose();return}const queue=[index],seen=new Set();while(queue.length){const currentIndex=queue.shift();if(seen.has(currentIndex))continue;seen.add(currentIndex);const current=state.cells[currentIndex];if(!current||current.mine||current.flagged)continue;current.open=true;if(current.adjacent===0)neighbors(currentIndex).forEach(next=>{const candidate=state.cells[next];if(candidate&&!candidate.open&&!candidate.flagged&&!candidate.mine)queue.push(next)})}checkWin()}
  function toggleFlag(index){const cell=state.cells[index];if(cell&&!cell.open&&!state.complete)cell.flagged=!cell.flagged}
  function lose(){state.complete=true;state.won=false;stopTimer();state.cells.forEach(cell=>{if(cell.mine)cell.open=true;if(cell.flagged&&!cell.mine)cell.bad=true});document.body.className="lost";$("status").textContent="Mine hit. Field lost."}
  function checkWin(){const safe=state.cells.filter(cell=>!cell.mine);if(!safe.every(cell=>cell.open))return;state.complete=true;state.won=true;stopTimer();state.cells.forEach(cell=>{if(cell.mine)cell.flagged=true});document.body.className="won";const result=GameScores.record({game:"mines",difficulty:state.difficulty,metric:"time",value:state.elapsed,meta:{rows:state.rows,cols:state.cols,mines:state.mines}});$("status").textContent=`Cleared in ${formatTime(state.elapsed)}${result?.best?" — a new local best!":"."}`}
  function bestForDifficulty(){const key=`solo:${state.difficulty}:time`,best=GameScores.game("mines").best[key];return best?formatTime(best.value):"—"}
  function updateReadout(){$("mine-count").textContent=state.mines;$("flag-count").textContent=state.cells.filter(cell=>cell.flagged).length;$("timer").textContent=formatTime(state.elapsed);$("best").textContent=bestForDifficulty()}
  function render(){document.querySelectorAll("[data-difficulty]").forEach(button=>button.classList.toggle("active",button.dataset.difficulty===state.difficulty));$("flag-mode").classList.toggle("active",state.flagMode);$("flag-mode").setAttribute("aria-pressed",String(state.flagMode));const board=$("board"),available=Math.max(24,Math.min(Math.floor((innerWidth-40)/state.cols),Math.floor((innerHeight-235)/Math.min(state.rows,16)),48));board.style.setProperty("--cols",state.cols);board.style.setProperty("--cell-size",`${available}px`);board.replaceChildren(...state.cells.map(cell=>{const button=document.createElement("button");button.type="button";button.className=["cell",cell.open?"open":"",cell.flagged&&!cell.open?"flagged":"",cell.mine&&cell.open?"mine":"",cell.bad?"bad":"",cell.open&&cell.adjacent?`n${cell.adjacent}`:""].filter(Boolean).join(" ");button.textContent=cell.open&&!cell.mine&&cell.adjacent?cell.adjacent:"";button.setAttribute("aria-label",`row ${Math.floor(cell.index/state.cols)+1}, column ${cell.index%state.cols+1}`);button.addEventListener("click",()=>{state.flagMode?toggleFlag(cell.index):reveal(cell.index);save();render()});button.addEventListener("contextmenu",event=>{event.preventDefault();toggleFlag(cell.index);save();render()});return button}));updateReadout()}
  function load(){try{const saved=JSON.parse(localStorage.getItem(SAVE_KEY)||"{}");if(saved.cells?.length&&configs[saved.difficulty]){Object.assign(state,saved);if(state.started&&!state.complete)startTimer();document.body.className=state.complete?(state.won?"won":"lost"):"";render();return}}catch{}newGame("easy")}
  document.querySelectorAll("[data-difficulty]").forEach(button=>button.addEventListener("click",()=>newGame(button.dataset.difficulty)));$("flag-mode").addEventListener("click",()=>{state.flagMode=!state.flagMode;render()});$("new-game-top").addEventListener("click",()=>newGame());addEventListener("resize",render);addEventListener("beforeunload",()=>{stopTimer();save()});load();
})();
