(() => {
  "use strict";
  const canvas=document.querySelector("#board"),ctx=canvas.getContext("2d");
  // Navigation uses a half-tower lattice. Towers occupy 2×2 navigation cells,
  // allowing placement every 20 pixels while creeps move continuously between nodes.
  const W=48,H=32,C=20;
  const modes={
    easy:{group:"standard",name:"Easy",desc:"One entrance, 30 waves, generous rewards.",waves:30,lanes:1,lives:20,cash:90,hp:0.82,reward:1.2},
    medium:{group:"standard",name:"Medium",desc:"Two entrances and 50 increasingly difficult waves.",waves:50,lanes:2,lives:20,cash:80,hp:1,reward:1},
    hard:{group:"standard",name:"Hard",desc:"60 waves, tougher creeps, and more dangerous splitters.",waves:60,lanes:2,lives:15,cash:75,hp:1.5,reward:.9,splitDepth:2},
    hundred:{group:"challenge",name:"The 100",desc:"A full hundred-wave endurance run.",waves:100,lanes:2,lives:20,cash:85,hp:1.05,reward:1},
    speed:{group:"challenge",name:"Speed",desc:"Waves arrive rapidly. There is almost no breathing room.",waves:50,lanes:2,lives:20,cash:100,hp:1,reward:1,auto:3},
    fifteen:{group:"challenge",name:"15 Towers",desc:"Survive 50 waves with no more than fifteen towers.",waves:50,lanes:2,lives:20,cash:100,hp:1,reward:1,towerCap:15},
    survivor:{group:"challenge",name:"Survivor",desc:"Every wave splits. The swarm multiplies as it advances.",waves:50,lanes:2,lives:25,cash:110,hp:.8,reward:1,only:"spawn"},
    fixed:{group:"challenge",name:"3K Fixed",desc:"Start with 3,000 credits. Defeated creeps pay nothing.",waves:50,lanes:2,lives:20,cash:3000,hp:1.15,reward:0,noIncome:true},
    nosplash:{group:"challenge",name:"No Splash",desc:"Area-damage towers are unavailable.",waves:50,lanes:2,lives:20,cash:95,hp:1,reward:1,noSplash:true},
    squirts:{group:"challenge",name:"Flow Control",desc:"Only Repeater and Cryo towers may be built.",waves:50,lanes:2,lives:20,cash:105,hp:1,reward:1,onlyTowers:["squirt","frost"]},
    fivemin:{group:"challenge",name:"Five Minutes",desc:"Score as many completed waves as possible before time expires.",waves:999,lanes:2,lives:30,cash:110,hp:.82,reward:1.15,timed:300,auto:2.4},
    nosell:{group:"challenge",name:"No Sell",desc:"Every placement is permanent. Plan the maze carefully.",waves:50,lanes:2,lives:20,cash:100,hp:1,reward:1,noSell:true}
  };
  const towerDefs={
    pellet:{name:"Needle",cost:5,color:"#7dd3fc",range:2.7,rate:.58,damage:8,desc:"Cheap, steady ground fire."},
    squirt:{name:"Repeater",cost:15,color:"#38bdf8",range:3.5,rate:.19,damage:5,desc:"Rapid stream against any target."},
    bash:{name:"Mortar",cost:40,color:"#fb7185",range:3.15,rate:1.5,damage:28,splash:1.1,stun:.35,desc:"Lobs a heavy round that damages a cluster."},
    pulse:{name:"Pulse",cost:48,color:"#c084fc",range:2.35,rate:1.65,damage:18,pulse:true,desc:"A slow radiating shock damages every ground creep nearby."},
    frost:{name:"Cryo",cost:25,color:"#a5f3fc",range:3.1,rate:.9,damage:3,slow:.58,desc:"Slows a group of advancing creeps."},
    swarm:{name:"Flak",cost:50,color:"#facc15",range:4.1,rate:.42,damage:13,airOnly:true,desc:"Dedicated anti-air missile battery."},
    rail:{name:"Rail",cost:65,color:"#fb923c",range:5.6,rate:1.8,damage:58,rail:true,desc:"Long-range precision fire against the toughest target."},
    boost:{name:"Relay",cost:45,color:"#a3e635",range:2.3,rate:0,damage:0,support:true,desc:"Amplifies nearby tower damage."}
  };
  const enemyDefs={
    normal:{name:"Normal",color:"#f8fafc",speed:1,hp:1,reward:1},fast:{name:"Fast",color:"#facc15",speed:1.75,hp:.64,reward:1},
    spawn:{name:"Spawn",color:"#a3e635",speed:.92,hp:.88,reward:1,split:true},dark:{name:"Dark",color:"#8b5cf6",speed:.82,hp:1.85,reward:2,resist:.42},
    morph:{name:"Morph",color:"#fb7185",speed:1.08,hp:1.15,reward:2,morph:true},flying:{name:"Flying",color:"#38bdf8",speed:1.3,hp:.85,reward:2,air:true},
    boss:{name:"Boss",color:"#f97316",speed:.58,hp:11,reward:14,boss:true}
  };
  let selectedMode="easy",tab="standard",mode,state,last=performance.now(),raf;
  const $=s=>document.querySelector(s),ui={start:$("#start-screen"),game:$("#game-screen"),modeList:$("#mode-list"),begin:$("#begin"),towerList:$("#tower-list"),wave:$("#wave"),lives:$("#lives"),credits:$("#credits"),score:$("#score"),mode:$("#mode-name"),status:$("#status"),next:$("#next-wave"),incoming:$("#incoming"),selectionName:$("#selection-name"),selectionCopy:$("#selection-copy"),selectionStats:$("#selection-stats"),upgrade:$("#upgrade"),sell:$("#sell"),send:$("#send-wave"),pause:$("#pause"),speed:$("#speed"),audio:$("#audio")};
  let audioContext=null,audioEnabled=localStorage.getItem("jasondaemon.maze-defense.sound")!=="off";
  function ensureAudio(){if(!audioEnabled)return null;if(!audioContext)audioContext=new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state==="suspended")audioContext.resume();return audioContext}
  function tone(freq,duration=.06,type="sine",volume=.025,slide=0){const ac=ensureAudio();if(!ac)return;const now=ac.currentTime,o=ac.createOscillator(),g=ac.createGain();o.type=type;o.frequency.setValueAtTime(freq,now);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(30,freq+slide),now+duration);g.gain.setValueAtTime(volume,now);g.gain.exponentialRampToValueAtTime(.0001,now+duration);o.connect(g).connect(ac.destination);o.start(now);o.stop(now+duration)}
  function sound(event,type=""){if(!audioEnabled)return;if(event==="build")tone(330,.07,"triangle",.022,190);else if(event==="upgrade"){tone(440,.08,"triangle",.024,240);setTimeout(()=>tone(660,.09,"triangle",.018,180),55)}else if(event==="wave")tone(180,.13,"sawtooth",.025,90);else if(event==="escape")tone(120,.16,"square",.02,-55);else if(event==="impact")tone(type==="bash"?75:type==="frost"?520:type==="swarm"?125:260,type==="bash"?.16:.055,type==="frost"?"sine":"triangle",type==="bash"?.035:.014,type==="bash"?-30:60);else if(event==="fire"){const f={pellet:680,squirt:920,bash:105,pulse:145,frost:480,swarm:210,rail:1040}[type]||400;tone(f,type==="bash"?.11:type==="rail"?.08:.035,type==="bash"?"sine":type==="rail"?"sawtooth":"square",type==="bash"?.024:.009,type==="bash"?-45:type==="rail"?-400:80)}}

  function renderModes(){ui.modeList.innerHTML="";Object.entries(modes).filter(([,m])=>m.group===tab).forEach(([key,m])=>{const b=document.createElement("button");b.className=`mode-card${key===selectedMode?" active":""}`;b.type="button";b.innerHTML=`<strong>${m.name}</strong><span>${m.desc}</span>`;b.onclick=()=>{selectedMode=key;renderModes();ui.begin.textContent=`Start ${m.name}`};ui.modeList.append(b)});if(modes[selectedMode].group!==tab){selectedMode=Object.keys(modes).find(k=>modes[k].group===tab);renderModes();ui.begin.textContent=`Start ${modes[selectedMode].name}`}}
  document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x===b));renderModes()});

  function entries(){return mode.lanes===1?[{x:0,y:16,side:"left"}]:[{x:0,y:10,side:"left"},{x:24,y:0,side:"top"}]}
  function exits(){return mode.lanes===1?[{x:47,y:16}]:[{x:47,y:20},{x:24,y:31}]}
  const key=(x,y)=>y*W+x;
  function occupies(t,x,y){return x>=t.x&&x<t.x+2&&y>=t.y&&y<t.y+2}
  function blocked(x,y,extra){return x<0||y<0||x>=W||y>=H||state.towers.some(t=>occupies(t,x,y))||(extra&&occupies(extra,x,y))}
  function pathFrom(start,extra){const goals=exits(),q=[[start.x,start.y]],prev=new Map([[key(start.x,start.y),null]]),dirs=[[1,0],[-1,0],[0,1],[0,-1]];let end=null;while(q.length){const p=q.shift();if(goals.some(g=>g.x===p[0]&&g.y===p[1])){end=p;break}for(const d of dirs){const nx=p[0]+d[0],ny=p[1]+d[1],k=key(nx,ny);if(!blocked(nx,ny,extra)&&!prev.has(k)){prev.set(k,p);q.push([nx,ny])}}}if(!end)return null;const out=[];for(let p=end;p;p=prev.get(key(p[0],p[1])))out.push({x:p[0]+.5,y:p[1]+.5});return out.reverse()}
  function allPaths(extra){return entries().map(e=>pathFrom(e,extra))}
  function towerAt(x,y){return state.towers.find(t=>occupies(t,x,y))}
  function canBuild(x,y){if(x<0||y<0||x>W-2||y>H-2)return false;for(let yy=y;yy<y+2;yy++)for(let xx=x;xx<x+2;xx++)if(blocked(xx,yy)||entries().some(e=>e.x===xx&&e.y===yy)||exits().some(e=>e.x===xx&&e.y===yy))return false;return allPaths({x,y}).every(Boolean)}
  function refreshPaths(){state.paths=allPaths();state.enemies.filter(e=>!e.air).forEach(e=>{const p=nearestPath(e);e.path=p;e.pi=Math.max(0,closestIndex(p,e.x,e.y))})}
  function closestIndex(path,x,y){let bi=0,bd=Infinity;path.forEach((p,i)=>{const d=(p.x-x)**2+(p.y-y)**2;if(d<bd){bd=d;bi=i}});return bi}
  function nearestPath(e){return state.paths[e.lane]||state.paths[0]}
  function buildTowerButtons(){ui.towerList.innerHTML="";Object.entries(towerDefs).forEach(([id,t])=>{const b=document.createElement("button"),preview=document.createElement("canvas"),copy=document.createElement("span");b.type="button";b.className="tower-button";b.dataset.tower=id;preview.width=92;preview.height=92;preview.setAttribute("aria-hidden","true");copy.className="tower-copy";copy.innerHTML=`<strong>${t.name}</strong><span>${t.cost} cr · ${t.desc}</span>`;b.append(preview,copy);drawTowerGlyph(preview.getContext("2d"),id,46,46,2.15,1,-.2);b.onclick=()=>{state.build=id;state.selected=null;updateSelection();buildTowerButtons()};b.disabled=(mode.noSplash&&(id==="bash"||id==="pulse"))||(mode.onlyTowers&&!mode.onlyTowers.includes(id));b.classList.toggle("active",state.build===id);ui.towerList.append(b)})}
  function startGame(){mode=modes[selectedMode];state={towers:[],enemies:[],shots:[],pulses:[],particles:[],paths:[],build:"pellet",selected:null,hover:null,wave:0,lives:mode.lives,cash:mode.cash,score:0,paused:false,speed:1,spawnQueue:[],spawnTimer:0,waveActive:false,nextTimer:mode.auto||12,elapsed:0,ended:false};refreshPaths();ui.start.hidden=true;ui.game.hidden=false;buildTowerButtons();updateSelection();updateUI();last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
  function waveType(n){if(mode.only)return mode.only;if(n%10===0)return"boss";const cycle=["normal","fast","spawn","normal","dark","flying","morph","fast","spawn"];return cycle[(n-1)%cycle.length]}
  function waveInfo(n){const type=waveType(n),boss=type==="boss",count=boss?Math.max(1,Math.ceil(n/20)):Math.min(8+Math.floor(n*.55),28),base=18*Math.pow(1.115,n-1)*mode.hp;return{type,count,hp:base*(enemyDefs[type].hp||1),gap:boss?1.2:Math.max(.17,.62-n*.005)}}
  function sendWave(){if(state.ended||state.waveActive||state.wave>=mode.waves)return;ensureAudio();sound("wave");state.wave++;const w=waveInfo(state.wave);for(let i=0;i<w.count;i++)for(let lane=0;lane<mode.lanes;lane++)state.spawnQueue.push({delay:(i*mode.lanes+lane)*w.gap,type:w.type,hp:w.hp,lane,depth:mode.splitDepth||1});state.spawnTimer=0;state.waveActive=true;state.nextTimer=mode.auto||12;ui.status.textContent=`Wave ${state.wave}: ${enemyDefs[w.type].name}`;updateUI()}
  function spawn(spec){const d=enemyDefs[spec.type],e0=entries()[spec.lane];state.enemies.push({type:spec.type,x:e0.x+.5,y:e0.y+.5,lane:spec.lane,path:d.air?[{x:e0.x+.5,y:e0.y+.5},{x:exits()[spec.lane].x+.5,y:exits()[spec.lane].y+.5}]:state.paths[spec.lane],pi:0,hp:spec.hp,maxHp:spec.hp,speed:d.speed*2,slow:1,slowTime:0,stun:0,depth:spec.depth||0,angle:0,phase:Math.random()*Math.PI*2})}
  function update(dt){if(state.paused||state.ended)return;dt*=state.speed;state.elapsed+=dt;if(mode.timed&&state.elapsed>=mode.timed){finish(true);return}if(state.spawnQueue.length){state.spawnTimer+=dt;while(state.spawnQueue.length&&state.spawnQueue[0].delay<=state.spawnTimer)spawn(state.spawnQueue.shift())}else if(state.waveActive&&!state.enemies.length){state.waveActive=false;const interest=mode.noIncome?0:Math.min(20,Math.floor(state.cash*.05));state.cash+=interest;state.score+=state.wave*10+state.lives;if(state.wave>=mode.waves){finish(true);return}ui.status.textContent=interest?`Wave clear · ${interest} interest earned.`:"Wave clear."}if(!state.waveActive){state.nextTimer-=dt;if(mode.auto&&state.nextTimer<=0)sendWave()}
    for(const e of [...state.enemies])moveEnemy(e,dt);for(const t of state.towers)updateTower(t,dt);updateProjectiles(dt);state.pulses.forEach(s=>s.life-=dt);state.pulses=state.pulses.filter(s=>s.life>0);state.particles.forEach(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt});state.particles=state.particles.filter(p=>p.life>0);updateUI()}
  function moveEnemy(e,dt){if(e.stun>0){e.stun-=dt;return}if(e.slowTime>0)e.slowTime-=dt;else e.slow=1;const p=e.path[e.pi+1];if(!p){escapeEnemy(e);return}const dx=p.x-e.x,dy=p.y-e.y,dist=Math.hypot(dx,dy),step=e.speed*e.slow*dt;if(dist<=step){e.x=p.x;e.y=p.y;e.pi++}else{e.x+=dx/dist*step;e.y+=dy/dist*step}e.angle=Math.atan2(dy,dx)}
  function escapeEnemy(e){state.enemies.splice(state.enemies.indexOf(e),1);state.lives--;sound("escape");if(state.lives<=0)finish(false)}
  function towerStats(t,level=t.level){const d=towerDefs[t.type];return{power:d.support?Math.round(22*level):Math.round(d.damage*(1+.72*(level-1))),range:(d.range*(1+.1*(level-1))).toFixed(1),rate:d.rate?Math.pow(1.22,level-1)/d.rate:0}}
  function updateTower(t,dt){const d=towerDefs[t.type];if(d.support)return;t.cool=(t.cool||0)-dt;if(t.cool>0)return;const boost=1+state.towers.filter(b=>b.type==="boost"&&Math.hypot((b.x+1)-(t.x+1),(b.y+1)-(t.y+1))<=towerDefs.boost.range*2).reduce((n,b)=>n+.22*b.level,0);const range=d.range*2*(1+.1*(t.level-1));const targets=state.enemies.filter(e=>(d.airOnly?enemyDefs[e.type].air:!enemyDefs[e.type].air||t.type==="squirt")&&Math.hypot(e.x-(t.x+1),e.y-(t.y+1))<=range);if(!targets.length)return;const power=d.damage*(1+.72*(t.level-1))*boost;if(d.pulse){targets.filter(e=>!enemyDefs[e.type].air).forEach(e=>damageEnemy(e,power,t));state.pulses.push({x:t.x+1,y:t.y+1,r:range,color:d.color,life:.46});sound("fire","pulse");t.cool=d.rate/Math.pow(1.15,t.level-1);return}targets.sort((a,b)=>d.rail?b.maxHp-a.maxHp:b.pi-a.pi);launchProjectile(t,targets[0],power);t.cool=d.rate/Math.pow(1.22,t.level-1)}
  function launchProjectile(t,target,damage){const speed={pellet:18,squirt:25,bash:9,frost:14,swarm:12,rail:31}[t.type]||18,sx=t.x+1,sy=t.y+1,duration=Math.max(.08,Math.hypot(target.x-sx,target.y-sy)/speed);state.shots.push({x:sx,y:sy,px:sx,py:sy,target,tx:target.x,ty:target.y,type:t.type,color:towerDefs[t.type].color,damage,speed,tower:t,age:0,duration});sound("fire",t.type)}
  function updateProjectiles(dt){for(const p of [...state.shots]){p.age+=dt;p.px=p.x;p.py=p.y;if(state.enemies.includes(p.target)){p.tx=p.target.x;p.ty=p.target.y}const dx=p.tx-p.x,dy=p.ty-p.y,dist=Math.hypot(dx,dy),step=p.speed*dt;if(dist<=step||p.age>2.5){p.x=p.tx;p.y=p.ty;resolveImpact(p);state.shots.splice(state.shots.indexOf(p),1)}else{p.x+=dx/dist*step;p.y+=dy/dist*step}}}
  function resolveImpact(p){const e=p.target;if(!state.enemies.includes(e)){burst(p.x,p.y,p.color,3);return}const d=towerDefs[p.type],ed=enemyDefs[e.type];let dealt=p.damage*(ed.resist&&p.type!=="squirt"?ed.resist:1);if(ed.morph)dealt*=.75+Math.random()*.5;if(d.splash){state.enemies.filter(x=>!enemyDefs[x.type].air&&Math.hypot(x.x-e.x,x.y-e.y)<=d.splash*2).forEach(x=>damageEnemy(x,dealt*(x===e?1:.58),p.tower))}else damageEnemy(e,dealt,p.tower);if(d.slow){e.slow=Math.min(e.slow,d.slow);e.slowTime=1.4}if(d.stun)e.stun=Math.max(e.stun,d.stun);burst(p.x,p.y,p.color,p.type==="bash"?13:5);sound("impact",p.type)}
  function burst(x,y,color,count){for(let i=0;i<count;i++)state.particles.push({x,y,vx:(Math.random()-.5)*2.5,vy:(Math.random()-.5)*2.5,life:.22+Math.random()*.3,color})}
  function damageEnemy(e,amount,t){e.hp-=amount;if(e.hp>0)return;const ed=enemyDefs[e.type];const idx=state.enemies.indexOf(e);if(idx<0)return;state.enemies.splice(idx,1);const pay=mode.noIncome?0:Math.max(1,Math.round(ed.reward*(1+state.wave*.035)));state.cash+=pay;state.score+=Math.round(10*ed.reward+state.wave*.7);for(let i=0;i<7;i++)state.particles.push({x:e.x,y:e.y,vx:(Math.random()-.5)*2,vy:(Math.random()-.5)*2,life:.4+Math.random()*.4,color:ed.color});if(ed.split&&e.depth>0){for(let i=0;i<2;i++)state.enemies.push({...e,hp:e.maxHp*.32,maxHp:e.maxHp*.32,speed:e.speed*1.28,depth:e.depth-1,x:e.x+(i?-.08:.08),pi:e.pi})}}
  function finish(won){state.ended=true;state.paused=true;ui.status.textContent=won?`Run complete · ${state.score} points.`:`The maze fell on wave ${state.wave}.`;ui.send.disabled=true;window.GameScores?.record({game:"maze-defense",mode:selectedMode,difficulty:selectedMode,metric:"score",value:state.score,meta:{wave:state.wave,lives:state.lives,won}})}
  function pointerCell(ev){const r=canvas.getBoundingClientRect();return{x:Math.floor((ev.clientX-r.left)*canvas.width/r.width/C),y:Math.floor((ev.clientY-r.top)*canvas.height/r.height/C)}}
  function selectCell(ev){if(state.ended)return;const{x,y}=pointerCell(ev),existing=towerAt(x,y);if(existing){state.selected=existing;state.build=null;state.hover=null;buildTowerButtons();updateSelection();return}if(!state.build)return;const d=towerDefs[state.build];if(state.cash<d.cost){flash("Not enough credits.");return}if(mode.towerCap&&state.towers.length>=mode.towerCap){flash("This challenge allows only 15 towers.");return}if(!canBuild(x,y)){flash("Every entrance must retain a path to an exit.");return}ensureAudio();sound("build");state.towers.push({type:state.build,x,y,level:1,spent:d.cost,cool:0});state.cash-=d.cost;state.hover={x,y};refreshPaths();updateUI()}
  function updateSelection(){const t=state.selected;if(!t){ui.selectionName.textContent=state.build?`Place ${towerDefs[state.build].name}`:"Nothing selected";ui.selectionCopy.textContent=state.build?towerDefs[state.build].desc:"Choose a tower, then place it on an open half-square.";ui.selectionStats.hidden=true;ui.upgrade.disabled=true;ui.sell.disabled=true;return}const d=towerDefs[t.type],cost=Math.round(d.cost*Math.pow(1.75,t.level)),cur=towerStats(t),next=towerStats(t,Math.min(4,t.level+1)),powerLabel=d.support?"Boost":"Power";ui.selectionName.textContent=`${d.name} · Level ${t.level}`;ui.selectionCopy.textContent=d.desc;ui.selectionStats.hidden=false;ui.selectionStats.innerHTML=`<span></span><strong>Current</strong><strong class="next">${t.level>=4?"Max":"Next"}</strong><span>${powerLabel}</span><strong>${cur.power}${d.support?"%":""}</strong><strong class="next">${next.power}${d.support?"%":""}</strong><span>Range</span><strong>${cur.range}</strong><strong class="next">${next.range}</strong>${d.rate?`<span>Rate</span><strong>${cur.rate.toFixed(1)}/s</strong><strong class="next">${next.rate.toFixed(1)}/s</strong>`:""}`;ui.upgrade.textContent=t.level>=4?"Max level":`Upgrade ${cost}`;ui.upgrade.disabled=t.level>=4||state.cash<cost;ui.sell.textContent=`Sell ${Math.floor(t.spent*.75)}`;ui.sell.disabled=!!mode.noSell}
  function upgrade(){const t=state.selected;if(!t||t.level>=4)return;const d=towerDefs[t.type],cost=Math.round(d.cost*Math.pow(1.75,t.level));if(state.cash<cost)return;ensureAudio();sound("upgrade");state.cash-=cost;t.spent+=cost;t.level++;updateSelection();updateUI()}
  function sell(){const t=state.selected;if(!t||mode.noSell)return;ensureAudio();tone(360,.09,"triangle",.018,-150);state.cash+=Math.floor(t.spent*.75);state.towers.splice(state.towers.indexOf(t),1);state.selected=null;refreshPaths();updateSelection();updateUI()}
  function flash(s){ui.status.textContent=s;canvas.classList.remove("shake");void canvas.offsetWidth;canvas.classList.add("shake")}
  function updateUI(){if(!state)return;ui.mode.textContent=mode.name;ui.wave.textContent=`${state.wave} / ${mode.waves===999?"∞":mode.waves}`;ui.lives.textContent=state.lives;ui.credits.textContent=state.cash;ui.score.textContent=state.score;ui.next.textContent=state.waveActive?`${state.enemies.length+state.spawnQueue.length} creeps remain`:`Next wave${mode.auto?` in ${Math.max(0,state.nextTimer).toFixed(1)}s`:" ready"}`;const next=waveInfo(Math.min(state.wave+1,mode.waves));ui.incoming.innerHTML=`<strong>${enemyDefs[next.type].name}</strong><br>${next.count*mode.lanes} incoming · approximately ${Math.round(next.hp)} health each`;ui.send.disabled=state.waveActive||state.ended;updateSelection()}
  function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);const grad=ctx.createLinearGradient(0,0,960,640);grad.addColorStop(0,"#152c42");grad.addColorStop(1,"#091827");ctx.fillStyle=grad;ctx.fillRect(0,0,960,640);for(let x=0;x<=W;x++){ctx.strokeStyle=x%2?"rgba(148,177,207,.045)":"rgba(148,177,207,.12)";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x*C,0);ctx.lineTo(x*C,640);ctx.stroke()}for(let y=0;y<=H;y++){ctx.strokeStyle=y%2?"rgba(148,177,207,.045)":"rgba(148,177,207,.12)";ctx.beginPath();ctx.moveTo(0,y*C);ctx.lineTo(960,y*C);ctx.stroke()}drawRoutes();if(state){entries().forEach((e,i)=>drawGate(e.x,e.y,"IN",i));exits().forEach((e,i)=>drawGate(e.x,e.y,"OUT",i));state.towers.forEach(drawTower);drawPlacementGhost();state.enemies.forEach(drawEnemy);state.shots.forEach(drawProjectile);state.pulses.forEach(p=>{const progress=1-p.life/.46;ctx.strokeStyle=p.color;ctx.globalAlpha=1-progress;ctx.lineWidth=6*(1-progress)+1;ctx.beginPath();ctx.arc(p.x*C,p.y*C,p.r*C*progress,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1});state.particles.forEach(p=>{ctx.fillStyle=p.color;ctx.globalAlpha=Math.min(1,p.life*2);ctx.fillRect(p.x*C,p.y*C,3,3);ctx.globalAlpha=1})}if(state?.paused&&!state.ended){ctx.fillStyle="rgba(3,10,18,.62)";ctx.fillRect(0,0,960,640);ctx.fillStyle="#f5f8fc";ctx.font="900 56px Avenir Next";ctx.textAlign="center";ctx.fillText("Paused",480,335)}}
  function drawProjectile(p){const progress=Math.min(1,p.age/p.duration),arc=p.type==="bash"?Math.sin(progress*Math.PI)*22:0,x=p.x*C,y=p.y*C-arc,px=p.px*C,py=p.py*C-(p.type==="bash"?Math.sin(Math.max(0,progress-.08)*Math.PI)*22:0),angle=Math.atan2(y-py,x-px);ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.shadowColor=p.color;ctx.shadowBlur=p.type==="rail"?13:7;ctx.fillStyle=p.color;ctx.strokeStyle="#eaf7ff";ctx.lineWidth=1;
    if(p.type==="pellet"){ctx.beginPath();ctx.moveTo(7,0);ctx.lineTo(-4,-3);ctx.lineTo(-4,3);ctx.closePath();ctx.fill()}
    else if(p.type==="squirt"){ctx.beginPath();ctx.ellipse(0,0,5,3,0,0,Math.PI*2);ctx.fill()}
    else if(p.type==="bash"){ctx.fillStyle="#fb7185";ctx.beginPath();ctx.arc(0,0,6,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle="#07111d";ctx.fillRect(-2,-2,4,4)}
    else if(p.type==="frost"){ctx.beginPath();ctx.roundRect(-6,-3,12,6,3);ctx.fill();ctx.stroke();for(let i=0;i<4;i++){ctx.rotate(Math.PI/2);ctx.fillRect(3,-1,5,2)}}
    else if(p.type==="swarm"){ctx.beginPath();ctx.moveTo(9,0);ctx.lineTo(-5,-4);ctx.lineTo(-3,0);ctx.lineTo(-5,4);ctx.closePath();ctx.fill();ctx.fillStyle="#fb923c";ctx.beginPath();ctx.moveTo(-4,-2);ctx.lineTo(-10,0);ctx.lineTo(-4,2);ctx.closePath();ctx.fill()}
    else if(p.type==="rail"){ctx.fillStyle="#fff7ed";ctx.fillRect(-9,-2,18,4);ctx.fillStyle=p.color;ctx.beginPath();ctx.moveTo(12,0);ctx.lineTo(5,-4);ctx.lineTo(5,4);ctx.closePath();ctx.fill()}
    ctx.restore()}
  function drawPlacementGhost(){if(!state.build||!state.hover)return;const{x,y}=state.hover,d=towerDefs[state.build],valid=state.cash>=d.cost&&(!mode.towerCap||state.towers.length<mode.towerCap)&&state.hover.valid,cx=(x+1)*C,cy=(y+1)*C;ctx.save();ctx.fillStyle=valid?"rgba(163,230,53,.14)":"rgba(251,113,133,.18)";ctx.strokeStyle=valid?"rgba(163,230,53,.8)":"rgba(251,113,133,.85)";ctx.lineWidth=2;ctx.fillRect(x*C,y*C,C*2,C*2);ctx.strokeRect(x*C+1,y*C+1,C*2-2,C*2-2);ctx.beginPath();ctx.arc(cx,cy,d.range*40,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=valid?.68:.42;drawTowerGlyph(ctx,state.build,cx,cy,1,1,-.15);ctx.restore()}
  function drawRoutes(){if(!state)return;ctx.strokeStyle="rgba(83,200,255,.12)";ctx.lineWidth=18;ctx.lineCap="round";state.paths.filter(Boolean).forEach(p=>{ctx.beginPath();p.forEach((n,i)=>i?ctx.lineTo(n.x*C,n.y*C):ctx.moveTo(n.x*C,n.y*C));ctx.stroke()});ctx.lineCap="butt"}
  function drawGate(x,y,label,i){ctx.fillStyle=label==="IN"?"#53c8ff":"#a3e635";ctx.fillRect(x*C+1,y*C+1,C-2,C-2);ctx.fillStyle="#07111d";ctx.font="900 7px Avenir Next";ctx.textAlign="center";ctx.fillText(label,x*C+C/2,y*C+C/2+3)}
  function drawTower(t){const d=towerDefs[t.type],cx=(t.x+1)*C,cy=(t.y+1)*C;ctx.save();if(t===state.selected){ctx.strokeStyle="rgba(83,200,255,.4)";ctx.lineWidth=2;ctx.beginPath();ctx.arc(cx,cy,d.range*(1+.1*(t.level-1))*40,0,Math.PI*2);ctx.stroke()}drawTowerGlyph(ctx,t.type,cx,cy,1,t.level,-.15);ctx.restore()}
  function drawTowerGlyph(g,type,cx,cy,scale=1,level=1,angle=0){const d=towerDefs[type],s=scale;g.save();g.translate(cx,cy);g.rotate(angle);g.shadowColor=d.color;g.shadowBlur=5*s;g.fillStyle="#081522";g.strokeStyle=d.color;g.lineWidth=2*s;g.beginPath();g.roundRect(-15*s,-15*s,30*s,30*s,7*s);g.fill();g.stroke();g.shadowBlur=0;g.fillStyle=d.color;g.strokeStyle=d.color;
    if(type==="pellet"){g.beginPath();g.moveTo(-7*s,8*s);g.lineTo(0,-10*s);g.lineTo(7*s,8*s);g.closePath();g.fill();g.fillRect(3*s,-2*s,15*s,4*s)}
    else if(type==="squirt"){g.beginPath();g.arc(-3*s,0,8*s,0,Math.PI*2);g.fill();g.fillRect(3*s,-7*s,14*s,5*s);g.fillRect(3*s,3*s,14*s,5*s)}
    else if(type==="bash"){g.beginPath();g.arc(0,0,10*s,0,Math.PI*2);g.fill();g.fillStyle="#081522";g.beginPath();g.arc(0,0,5*s,0,Math.PI*2);g.fill();g.fillStyle=d.color;g.fillRect(2*s,-5*s,14*s,10*s)}
    else if(type==="pulse"){for(let r=4;r<=11;r+=4){g.globalAlpha=.35+r/20;g.beginPath();g.arc(0,0,r*s,0,Math.PI*2);g.stroke()}g.globalAlpha=1;g.beginPath();g.arc(0,0,4*s,0,Math.PI*2);g.fill()}
    else if(type==="frost"){for(let i=0;i<6;i++){g.rotate(Math.PI/3);g.fillRect(0,-1.5*s,13*s,3*s);g.fillRect(7*s,-5*s,2*s,10*s)}}
    else if(type==="swarm"){for(let y=-1;y<=1;y+=2)for(let x=-1;x<=1;x+=2){g.beginPath();g.roundRect((x*6-3)*s,(y*6-3)*s,6*s,6*s,2*s);g.fill()}g.fillRect(8*s,-3*s,9*s,6*s)}
    else if(type==="rail"){g.fillRect(-8*s,-5*s,21*s,10*s);g.fillStyle="#081522";g.fillRect(-4*s,-2*s,15*s,4*s);g.fillStyle=d.color;g.fillRect(11*s,-2*s,9*s,4*s)}
    else if(type==="boost"){g.beginPath();g.arc(0,0,5*s,0,Math.PI*2);g.fill();for(let i=0;i<4;i++){g.rotate(Math.PI/2);g.fillRect(4*s,-2*s,12*s,4*s)}g.strokeStyle=d.color;g.beginPath();g.arc(0,0,12*s,0,Math.PI*2);g.stroke()}
    g.fillStyle="#fff";g.font=`800 ${7*s}px Avenir Next`;g.textAlign="center";g.fillText(level,0,3*s);g.restore()}
  function drawEnemy(e){const d=enemyDefs[e.type],x=e.x*C,y=e.y*C,bob=Math.sin(state.elapsed*5+e.phase)*1.4,r=d.boss?17:9;ctx.save();ctx.translate(x,y+bob);ctx.rotate(e.angle);ctx.fillStyle=d.color;ctx.strokeStyle="#07111d";ctx.lineWidth=2;ctx.shadowColor=d.color;ctx.shadowBlur=7;
    if(e.type==="normal"){ctx.beginPath();ctx.arc(0,0,9,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle="#07111d";ctx.fillRect(1,-3,8,6)}
    else if(e.type==="fast"){ctx.beginPath();ctx.moveTo(13,0);ctx.lineTo(-8,-8);ctx.lineTo(-3,0);ctx.lineTo(-8,8);ctx.closePath();ctx.fill();ctx.stroke()}
    else if(e.type==="spawn"){ctx.beginPath();for(let i=0;i<6;i++){const a=i*Math.PI/3;ctx.lineTo(Math.cos(a)*10,Math.sin(a)*10)}ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle="#07111d";ctx.beginPath();ctx.arc(3,0,3,0,Math.PI*2);ctx.fill()}
    else if(e.type==="dark"){ctx.beginPath();ctx.moveTo(11,0);ctx.lineTo(4,9);ctx.lineTo(-10,7);ctx.lineTo(-6,0);ctx.lineTo(-10,-7);ctx.lineTo(4,-9);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle="#07111d";ctx.fillRect(-2,-7,4,14)}
    else if(e.type==="morph"){const rr=9+Math.sin(state.elapsed*7+e.phase)*2;ctx.beginPath();for(let i=0;i<8;i++){const a=i*Math.PI/4,q=i%2?rr*.65:rr;ctx.lineTo(Math.cos(a)*q,Math.sin(a)*q)}ctx.closePath();ctx.fill();ctx.stroke()}
    else if(e.type==="flying"){ctx.beginPath();ctx.moveTo(14,0);ctx.lineTo(-8,-9);ctx.lineTo(-4,0);ctx.lineTo(-8,9);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle="#07111d";ctx.fillRect(-2,-2,8,4)}
    else{ctx.beginPath();ctx.roundRect(-17,-12,34,24,7);ctx.fill();ctx.stroke();ctx.fillStyle="#07111d";ctx.beginPath();ctx.arc(5,0,6,0,Math.PI*2);ctx.fill();ctx.strokeStyle=d.color;ctx.beginPath();ctx.arc(-8,0,6,0,Math.PI*2);ctx.stroke()}
    ctx.shadowBlur=0;ctx.restore();ctx.fillStyle="rgba(2,8,15,.8)";ctx.fillRect(x-12,y-r-8,24,3);ctx.fillStyle=e.hp/e.maxHp>.5?"#a3e635":e.hp/e.maxHp>.2?"#facc15":"#fb7185";ctx.fillRect(x-12,y-r-8,24*Math.max(0,e.hp/e.maxHp),3)}
  function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(state)update(dt);draw();raf=requestAnimationFrame(loop)}
  function updateAudioButton(){ui.audio.textContent=audioEnabled?"Sound on":"Sound off";ui.audio.setAttribute("aria-pressed",String(audioEnabled))}
  canvas.addEventListener("pointerdown",selectCell);canvas.addEventListener("pointermove",ev=>{if(state?.build){const p=pointerCell(ev);if(!state.hover||p.x!==state.hover.x||p.y!==state.hover.y)state.hover={...p,valid:canBuild(p.x,p.y)}}});canvas.addEventListener("pointerleave",()=>{if(state)state.hover=null});ui.begin.onclick=startGame;ui.send.onclick=sendWave;ui.upgrade.onclick=upgrade;ui.sell.onclick=sell;ui.audio.onclick=()=>{audioEnabled=!audioEnabled;localStorage.setItem("jasondaemon.maze-defense.sound",audioEnabled?"on":"off");updateAudioButton();if(audioEnabled){ensureAudio();tone(520,.08,"triangle",.02,180)}};ui.pause.onclick=()=>{if(!state)return;state.paused=!state.paused;ui.pause.textContent=state.paused?"Resume":"Pause"};ui.speed.onclick=()=>{if(!state)return;state.speed=state.speed===1?2:state.speed===2?3:1;ui.speed.textContent=`${state.speed}× speed`};$("#new-game").onclick=()=>{cancelAnimationFrame(raf);ui.game.hidden=true;ui.start.hidden=false;state=null;draw()};
  updateAudioButton();renderModes();draw();
})();
