(() => {
  "use strict";
  const SAVE_KEY="jasondaemon.game.mines.state.v2",LEGACY_SAVE_KEY="jasondaemon.game.mines.state.v1",STATS_KEY="jasondaemon.game.mines.stats.v1",SOUND_KEY="jasondaemon.game.mines.sound.v1";
  const configs={easy:{label:"Easy",rows:9,cols:9,mines:10},medium:{label:"Medium",rows:16,cols:16,mines:40},hard:{label:"Hard",rows:16,cols:30,mines:99}};
  const state={difficulty:"easy",rows:9,cols:9,mines:10,cells:[],started:false,complete:false,won:false,flagMode:false,startTime:0,elapsed:0,timer:null,focusIndex:0,sound:localStorage.getItem(SOUND_KEY)!=="off"};
  const $=id=>document.getElementById(id),board=$("board");
  let holdTimer=null,held=false,cellSize=42,gap=2,pad=8,blastFx=null,hoverIndex=null,audioContext=null;
  const app=new PIXI.Application({width:1,height:1,backgroundAlpha:0,antialias:false,roundPixels:true,resolution:Math.min(devicePixelRatio||1,2),autoDensity:true});
  board.appendChild(app.view);
  const layer=new PIXI.Container();app.stage.addChild(layer);
  const colors=[0,0x67d9ff,0x65e6a4,0xffd75e,0xb88cff,0xff8b72,0x55e5df,0xf1f6fa,0xaab8c6];
  function sound(kind){if(!state.sound)return;audioContext||=new (window.AudioContext||window.webkitAudioContext)();const now=audioContext.currentTime,notes=kind==="blast"?[[75,.24,"sawtooth",.16],[42,.38,"square",.12]]:kind==="win"?[[440,.09,"square",.055],[554,.1,"square",.05],[659,.16,"square",.055]]:kind==="flag"?[[300,.055,"square",.035]]:[[620,.025,"square",.018]];notes.forEach(([frequency,duration,type,gain],i)=>{const oscillator=audioContext.createOscillator(),volume=audioContext.createGain(),start=now+i*.065;oscillator.type=type;oscillator.frequency.setValueAtTime(frequency,start);if(kind==="blast")oscillator.frequency.exponentialRampToValueAtTime(Math.max(24,frequency*.35),start+duration);volume.gain.setValueAtTime(gain,start);volume.gain.exponentialRampToValueAtTime(.0001,start+duration);oscillator.connect(volume).connect(audioContext.destination);oscillator.start(start);oscillator.stop(start+duration)})}
  const formatTime=seconds=>`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,"0")}`;
  const neighbors=index=>{const row=Math.floor(index/state.cols),col=index%state.cols,result=[];for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){if(!dr&&!dc)continue;const r=row+dr,c=col+dc;if(r>=0&&r<state.rows&&c>=0&&c<state.cols)result.push(r*state.cols+c)}return result};
  function getStats(){try{return{played:0,won:0,...JSON.parse(localStorage.getItem(STATS_KEY)||"{}")}}catch{return{played:0,won:0}}}
  function recordResult(won){const stats=getStats();stats.played++;if(won)stats.won++;localStorage.setItem(STATS_KEY,JSON.stringify(stats))}
  function save(){localStorage.setItem(SAVE_KEY,JSON.stringify({difficulty:state.difficulty,rows:state.rows,cols:state.cols,mines:state.mines,cells:state.cells,started:state.started,complete:state.complete,won:state.won,startTime:state.startTime,elapsed:state.elapsed,focusIndex:state.focusIndex}))}
  function stopTimer(){if(state.timer)clearInterval(state.timer);state.timer=null}
  function startTimer(){stopTimer();state.timer=setInterval(()=>{if(state.started&&!state.complete){state.elapsed=Math.max(0,Math.floor((Date.now()-state.startTime)/1000));updateReadout();save()}},500)}
  function setResult(kind,kicker,title,message){$("result-card").dataset.state=kind;$("result-kicker").textContent=kicker;$("result-title").textContent=title;$("status").textContent=message}
  function newGame(difficulty=state.difficulty){const config=configs[difficulty]||configs.easy;stopTimer();Object.assign(state,{difficulty,...config,cells:Array.from({length:config.rows*config.cols},(_,index)=>({index,mine:false,open:false,flagged:false,adjacent:0,exploded:false,bad:false})),started:false,complete:false,won:false,flagMode:false,startTime:0,elapsed:0,focusIndex:0});document.body.className="";$("difficulty").value=difficulty;setResult("ready","Field ready","Choose a square","Your first move and its surrounding squares are always safe.");render();save()}
  function placeMines(safeIndex){const forbidden=new Set([safeIndex,...neighbors(safeIndex)]),candidates=state.cells.map(cell=>cell.index).filter(index=>!forbidden.has(index));for(let n=0;n<state.mines;n++){const pick=Math.floor(Math.random()*candidates.length);state.cells[candidates.splice(pick,1)[0]].mine=true}state.cells.forEach(cell=>{cell.adjacent=cell.mine?0:neighbors(cell.index).filter(index=>state.cells[index].mine).length})}
  function floodReveal(seedIndexes){const queue=[...seedIndexes],seen=new Set();for(let q=0;q<queue.length;q++){const index=queue[q];if(seen.has(index))continue;seen.add(index);const cell=state.cells[index];if(!cell||cell.mine||cell.flagged)continue;cell.open=true;if(cell.adjacent===0)neighbors(index).forEach(next=>{if(!state.cells[next].open&&!state.cells[next].flagged)queue.push(next)})}}
  function reveal(index){const cell=state.cells[index];if(!cell||cell.flagged||state.complete)return;if(!state.started){placeMines(index);state.started=true;state.startTime=Date.now()-state.elapsed*1000;startTimer();setResult("playing","Field active","Sweep carefully","Numbers count the mines in the eight surrounding squares.")}if(cell.open){chord(index);return}if(cell.mine){cell.open=true;cell.exploded=true;lose();return}sound("reveal");floodReveal([index]);checkWin()}
  function chord(index){const cell=state.cells[index];if(!cell?.open||!cell.adjacent)return;const around=neighbors(index);if(around.filter(next=>state.cells[next].flagged).length!==cell.adjacent)return;const mine=around.find(next=>state.cells[next].mine&&!state.cells[next].flagged);if(mine!==undefined){state.cells[mine].open=true;state.cells[mine].exploded=true;lose();return}floodReveal(around);checkWin()}
  function toggleFlag(index){const cell=state.cells[index];if(!cell||cell.open||state.complete)return;sound("flag");cell.flagged=!cell.flagged;if(state.started)setResult("playing","Field active",cell.flagged?"Mine marked":"Flag removed",cell.flagged?"Keep sweeping—or activate a completed number to open around it.":"That square can be revealed again.")}
  function settleElapsed(){if(state.started&&state.startTime)state.elapsed=Math.max(0,Math.floor((Date.now()-state.startTime)/1000))}
  function lose(){settleElapsed();state.complete=true;state.won=false;sound("blast");stopTimer();recordResult(false);state.cells.forEach(cell=>{if(cell.mine)cell.open=true;if(cell.flagged&&!cell.mine)cell.bad=true});document.body.className="lost";setResult("lost","Mine detonated","Field lost","The whole field is revealed. Start a new one when you are ready.")}
  function checkWin(){if(!state.cells.filter(cell=>!cell.mine).every(cell=>cell.open))return;settleElapsed();state.complete=true;state.won=true;sound("win");stopTimer();recordResult(true);state.cells.forEach(cell=>{if(cell.mine)cell.flagged=true});document.body.className="won";const result=GameScores.record({game:"mines",difficulty:state.difficulty,metric:"time",value:state.elapsed,meta:{rows:state.rows,cols:state.cols,mines:state.mines}});setResult("won",result?.best?"New local record":"Field cleared",`Cleared in ${formatTime(state.elapsed)}`,result?.best?"That is your fastest clear at this difficulty.":"Every safe square found. Try to beat your best time.")}
  function bestForDifficulty(){const best=GameScores.game("mines").best[`solo:${state.difficulty}:time`];return best?formatTime(best.value):"—"}
  function updateReadout(){const flags=state.cells.filter(cell=>cell.flagged).length,openedSafe=state.cells.filter(cell=>cell.open&&!cell.mine).length,safeRemaining=state.rows*state.cols-state.mines-openedSafe,stats=getStats();$("remaining").textContent=Math.max(0,state.mines-flags);$("timer").textContent=formatTime(state.elapsed);$("best").textContent=bestForDifficulty();$("clear-rate").textContent=stats.played?`${Math.round(stats.won/stats.played*100)}%`:"0%";$("field-label").textContent=`${configs[state.difficulty].label} field`;$("field-progress").textContent=state.complete?(state.won?"All safe squares cleared":"Minefield revealed"):`${safeRemaining} safe square${safeRemaining===1?"":"s"} remain`;$("stats").innerHTML=`Local record<br><strong>${stats.won} cleared · ${Math.max(0,stats.played-stats.won)} lost · ${stats.played} played</strong>`}
  function cellLabel(cell){const location=`Row ${Math.floor(cell.index/state.cols)+1}, column ${cell.index%state.cols+1}`;if(cell.flagged&&!cell.open)return`${location}, flagged`;if(!cell.open)return`${location}, hidden`;if(cell.mine)return`${location}, mine`;return`${location}, ${cell.adjacent?`${cell.adjacent} nearby mine${cell.adjacent===1?"":"s"}`:"clear"}`}
  function text(value,x,y,color,size){const label=new PIXI.Text(value,{fontFamily:"ui-monospace, SFMono-Regular, Menlo, monospace",fontSize:size,fontWeight:"900",fill:color});label.anchor.set(.5);label.position.set(x,y);return label}
  function starPoints(cx,cy,outer,inner,points=10,rotation=-Math.PI/2){const result=[];for(let i=0;i<points*2;i++){const radius=i%2?inner:outer,angle=rotation+i*Math.PI/points;result.push(cx+Math.cos(angle)*radius,cy+Math.sin(angle)*radius)}return result}
  function drawMine(g,x,y,size){const cx=x+size/2,cy=y+size/2;g.beginFill(0x090d13);g.drawPolygon(starPoints(cx,cy,size*.34,size*.23,10));g.endFill();g.beginFill(0x202b35);g.drawCircle(cx,cy,size*.24);g.endFill();g.beginFill(0x485966);g.drawCircle(cx-size*.055,cy-size*.06,size*.075);g.endFill();g.lineStyle(Math.max(1,size*.045),0xffb14a,1);g.moveTo(cx+size*.13,cy-size*.18);g.lineTo(cx+size*.24,cy-size*.3);g.lineStyle(0);g.beginFill(0xffd166);g.drawCircle(cx+size*.255,cy-size*.315,Math.max(1.5,size*.045));g.endFill()}
  function drawClosedCell(g,x,y,size){const bevel=Math.max(2,Math.min(4,Math.round(size*.08)));g.beginFill(0x0c1d2b);g.drawRect(x,y,size,size);g.endFill();g.beginFill(0x27465e);g.drawRect(x+1,y+1,size-2,size-2);g.endFill();g.beginFill(0x3e6078);g.drawRect(x+2,y+2,size-4,bevel);g.drawRect(x+2,y+2,bevel,size-4);g.endFill();g.beginFill(0x152e42);g.drawRect(x+2,y+size-bevel-2,size-4,bevel);g.drawRect(x+size-bevel-2,y+2,bevel,size-4);g.endFill();g.beginFill(0x223f56);g.drawRect(x+bevel+1,y+bevel+1,size-bevel*2-2,size-bevel*2-2);g.endFill()}
  function drawBlast(g,x,y,size){const cx=x+size/2,cy=y+size/2;g.beginFill(0x26080a);g.drawCircle(cx,cy,size*.39);g.endFill();g.beginFill(0xff6038);g.drawPolygon(starPoints(cx,cy,size*.46,size*.23,12));g.endFill();g.beginFill(0xffb52f);g.drawPolygon(starPoints(cx,cy,size*.34,size*.18,9,.1));g.endFill();g.beginFill(0xfff3a0);g.drawCircle(cx,cy,size*.14);g.endFill();const fx=new PIXI.Container();fx.position.set(cx,cy);layer.addChild(fx);for(let i=0;i<14;i++){const angle=i*Math.PI*2/14+(i%3)*.08,p=new PIXI.Graphics(),color=i%3===0?0xfff3a0:i%3===1?0xff9b36:0xd93442;p.beginFill(color);p.drawRect(-1.5,-1.5,3,3);p.endFill();p._vx=Math.cos(angle)*(size*.035+(i%4)*.012);p._vy=Math.sin(angle)*(size*.035+(i%3)*.014);fx.addChild(p)}blastFx={container:fx,start:performance.now(),size}}
  app.ticker.add(()=>{if(!blastFx)return;const age=performance.now()-blastFx.start,t=Math.min(1,age/850);blastFx.container.children.forEach((p,i)=>{p.x+=p._vx;p.y+=p._vy;p._vy+=.018;p.alpha=1-t;p.rotation+=i%2?.08:-.08});blastFx.container.scale.set(1+t*.35);if(t>=1){blastFx.container.visible=false;blastFx=null}});
  function render(){const maxRows=Math.min(state.rows,16),available=Math.max(22,Math.min(Math.floor((innerWidth-80)/state.cols),Math.floor((innerHeight-245)/maxRows),47));cellSize=available;const pitch=cellSize+gap,width=pad*2+state.cols*pitch-gap,height=pad*2+state.rows*pitch-gap;app.renderer.resize(width,height);board.style.width=`${width}px`;board.style.height=`${height}px`;blastFx=null;layer.removeChildren().forEach(child=>child.destroy());const g=new PIXI.Graphics();layer.addChild(g);let explodedCell=null;for(const cell of state.cells){const col=cell.index%state.cols,row=Math.floor(cell.index/state.cols),x=pad+col*pitch,y=pad+row*pitch;if(!cell.open&&!cell.flagged)drawClosedCell(g,x,y,cellSize);else{const fill=cell.exploded?0x651b24:cell.mine&&cell.open?0x34222a:cell.open?0x08131f:0xd93442;g.beginFill(fill);g.drawRect(x,y,cellSize,cellSize);g.endFill()}if(cell.flagged&&!cell.open){g.beginFill(0xffffff);g.drawRect(x+cellSize*.32,y+cellSize*.22,Math.max(2,cellSize*.08),cellSize*.56);g.drawPolygon([x+cellSize*.4,y+cellSize*.22,x+cellSize*.75,y+cellSize*.38,x+cellSize*.4,y+cellSize*.54]);g.endFill()}else if(cell.exploded)explodedCell={x,y};else if(cell.mine&&cell.open)drawMine(g,x,y,cellSize);else if(cell.open&&cell.adjacent)layer.addChild(text(String(cell.adjacent),x+cellSize/2,y+cellSize/2,colors[cell.adjacent],Math.max(11,cellSize*.42)));if(cell.bad){g.lineStyle(Math.max(2,cellSize*.08),0xffffff,1);g.moveTo(x+cellSize*.28,y+cellSize*.28);g.lineTo(x+cellSize*.72,y+cellSize*.72);g.moveTo(x+cellSize*.72,y+cellSize*.28);g.lineTo(x+cellSize*.28,y+cellSize*.72);g.lineStyle(0)}}if(explodedCell)drawBlast(g,explodedCell.x,explodedCell.y,cellSize);if(hoverIndex!==null&&!state.complete){const col=hoverIndex%state.cols,row=Math.floor(hoverIndex/state.cols),x=pad+col*pitch,y=pad+row*pitch;g.beginFill(0x55c7ff,.75);g.drawRect(x,y,cellSize,2);g.drawRect(x,y+cellSize-2,cellSize,2);g.drawRect(x,y,2,cellSize);g.drawRect(x+cellSize-2,y,2,cellSize);g.endFill()}if(document.activeElement===board){const col=state.focusIndex%state.cols,row=Math.floor(state.focusIndex/state.cols),x=pad+col*pitch,y=pad+row*pitch;g.beginFill(0xffd166,1);g.drawRect(x,y,cellSize,3);g.drawRect(x,y+cellSize-3,cellSize,3);g.drawRect(x,y,3,cellSize);g.drawRect(x+cellSize-3,y,3,cellSize);g.endFill()}$("difficulty").value=state.difficulty;$("flag-mode").setAttribute("aria-pressed",String(state.flagMode));$("sound").setAttribute("aria-pressed",String(state.sound));$("sound").setAttribute("aria-label",state.sound?"Mute sound":"Enable sound");$("sound").textContent=state.sound?"♪ Sound":"♪ Muted";board.setAttribute("aria-label",`Minefield. Selected ${cellLabel(state.cells[state.focusIndex])}. Use arrow keys to move, Enter to reveal, and F to flag.`);updateReadout()}
  const renderBoard=render;render=function(){renderBoard();$("flag-mode").setAttribute("aria-label",state.flagMode?"Disable flag mode":"Enable flag mode");$("sound").title=state.sound?"Mute sound":"Enable sound";$("sound").textContent=state.sound?"🔊":"🔇"}
  function act(index,flag=state.flagMode){state.focusIndex=index;flag?toggleFlag(index):reveal(index);save();render()}
  function hit(clientX,clientY){const rect=app.view.getBoundingClientRect(),x=(clientX-rect.left)*app.screen.width/rect.width-pad,y=(clientY-rect.top)*app.screen.height/rect.height-pad,pitch=cellSize+gap,col=Math.floor(x/pitch),row=Math.floor(y/pitch);if(col<0||row<0||col>=state.cols||row>=state.rows||x-col*pitch>=cellSize||y-row*pitch>=cellSize)return null;return row*state.cols+col}
  function moveFocus(key){const index=state.focusIndex,row=Math.floor(index/state.cols),col=index%state.cols;state.focusIndex=key==="ArrowLeft"?row*state.cols+Math.max(0,col-1):key==="ArrowRight"?row*state.cols+Math.min(state.cols-1,col+1):key==="ArrowUp"?Math.max(0,row-1)*state.cols+col:Math.min(state.rows-1,row+1)*state.cols+col;render()}
  function load(){try{const raw=localStorage.getItem(SAVE_KEY)||localStorage.getItem(LEGACY_SAVE_KEY)||"{}",saved=JSON.parse(raw),config=configs[saved.difficulty];if(saved.cells?.length&&config&&saved.cells.length===config.rows*config.cols){Object.assign(state,saved,{flagMode:false,focusIndex:Math.min(saved.focusIndex||0,saved.cells.length-1)});$("difficulty").value=state.difficulty;if(state.started&&!state.complete){startTimer();setResult("playing","Field resumed","Sweep carefully","Your saved field and timer have been restored.")}else if(state.complete&&state.won)setResult("won","Field cleared",`Cleared in ${formatTime(state.elapsed)}`,"Start a new field to chase another record.");else if(state.complete)setResult("lost","Mine detonated","Field lost","Start a new field when you are ready.");document.body.className=state.complete?(state.won?"won":"lost"):"";render();return}}catch{}newGame("easy")}
  app.view.addEventListener("click",event=>{if(held){held=false;return}const index=hit(event.clientX,event.clientY);if(index!==null)act(index)});
  app.view.addEventListener("contextmenu",event=>{event.preventDefault();const index=hit(event.clientX,event.clientY);if(index!==null)act(index,true)});
  app.view.addEventListener("pointermove",event=>{if(event.pointerType!=="mouse")return;const next=hit(event.clientX,event.clientY);if(next!==hoverIndex){hoverIndex=next;render()}});app.view.addEventListener("pointerleave",()=>{if(hoverIndex!==null){hoverIndex=null;render()}});
  app.view.addEventListener("pointerdown",event=>{board.focus({preventScroll:true});render();if(event.pointerType==="mouse")return;const index=hit(event.clientX,event.clientY);if(index===null)return;held=false;holdTimer=setTimeout(()=>{held=true;act(index,true);navigator.vibrate?.(25)},480)});
  ["pointerup","pointercancel","pointerleave"].forEach(type=>app.view.addEventListener(type,()=>clearTimeout(holdTimer)));
  board.addEventListener("focus",render);board.addEventListener("blur",render);board.addEventListener("keydown",event=>{if(["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"].includes(event.key)){event.preventDefault();moveFocus(event.key)}else if(event.key==="f"||event.key==="F"){event.preventDefault();act(state.focusIndex,true)}else if(event.key==="Enter"||event.key===" "){event.preventDefault();act(state.focusIndex,false)}});
  $("difficulty").addEventListener("change",event=>{const next=event.target.value;if(state.started&&!state.complete&&!confirm("Change fields? Your current game will be replaced.")){event.target.value=state.difficulty;return}if(next==="infinite")location.href="infinite.html";else newGame(next)});$("sound").addEventListener("click",()=>{state.sound=!state.sound;localStorage.setItem(SOUND_KEY,state.sound?"on":"off");if(state.sound)sound("reveal");render()});$("flag-mode").addEventListener("click",()=>{state.flagMode=!state.flagMode;render()});$("new-game").addEventListener("click",()=>{if(state.started&&!state.complete&&!confirm("Start a new field? Your current game will be replaced."))return;newGame()});addEventListener("resize",render);addEventListener("beforeunload",()=>{stopTimer();save()});load();const requestedMode=new URLSearchParams(location.search).get("mode");if(configs[requestedMode]&&requestedMode!==state.difficulty)newGame(requestedMode);
})();
