(() => {
  "use strict";
  const SAVE_KEY="jasondaemon.game.mines.infinite.v1",BEST_KEY="jasondaemon.game.mines.infinite.best.v1",SOUND_KEY="jasondaemon.game.mines.sound.v1";
  const SIZE=16,DENSITY=.15625,SECTOR_BONUS=1000,MINE_SCORE=25,FLAG_MISS=50,CELL=26,GAP=2,PITCH=CELL+GAP,SECTOR=SIZE*PITCH,STEP=SECTOR+GAP;
  const $=id=>document.getElementById(id),key=(x,y)=>`${x},${y}`,sectorKey=(sx,sy)=>`${sx},${sy}`;
  const state={seed:0,sectors:{},unlocked:new Set(),complete:new Set(),blown:new Set(),safe:new Set(),open:new Set(),flags:new Set(),credited:new Set(),damage:{},score:0,wins:0,over:false,flagMode:false,newest:"0,0",started:false,cursor:{x:8,y:8},sound:localStorage.getItem(SOUND_KEY)!=="off"};
  const dirtySectors=new Set(),sectorViews=new Map();
  let topologyDirty=true,saveTimer=null,pointer=null,holdTimer=null,held=false,hoverCell=null,minimapTransform=null;

  const viewport=$("viewport");
  const app=new PIXI.Application({resizeTo:viewport,backgroundAlpha:0,antialias:false,roundPixels:true,resolution:Math.min(devicePixelRatio||1,2),autoDensity:true});
  $("world").appendChild(app.view);
  const world=new PIXI.Container();
  app.stage.addChild(world);
  let audioContext=null;
  function sound(kind){if(!state.sound)return;audioContext||=new (window.AudioContext||window.webkitAudioContext)();const now=audioContext.currentTime,notes=kind==="blast"?[[75,.24,"sawtooth",.16],[42,.38,"square",.12]]:kind==="win"?[[440,.09,"square",.055],[554,.1,"square",.05],[659,.16,"square",.055]]:kind==="flag"?[[300,.055,"square",.035]]:[[620,.025,"square",.018]];notes.forEach(([frequency,duration,type,gain],i)=>{const oscillator=audioContext.createOscillator(),volume=audioContext.createGain(),start=now+i*.065;oscillator.type=type;oscillator.frequency.setValueAtTime(frequency,start);if(kind==="blast")oscillator.frequency.exponentialRampToValueAtTime(Math.max(24,frequency*.35),start+duration);volume.gain.setValueAtTime(gain,start);volume.gain.exponentialRampToValueAtTime(.0001,start+duration);oscillator.connect(volume).connect(audioContext.destination);oscillator.start(start);oscillator.stop(start+duration)})}

  function hash(x,y){let h=(state.seed^Math.imul(x,374761393)^Math.imul(y,668265263))|0;h=Math.imul(h^(h>>>13),1274126177);return(h^(h>>>16))>>>0}
  function mineAt(x,y){return!state.safe.has(key(x,y))&&hash(x,y)/4294967296<DENSITY}
  function adjacent(x,y){let n=0;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++)if((dx||dy)&&mineAt(x+dx,y+dy))n++;return n}
  function coords(sx,sy,index){return{x:sx*SIZE+index%SIZE,y:sy*SIZE+Math.floor(index/SIZE)}}
  function getSector(sx,sy){const id=sectorKey(sx,sy);if(!state.sectors[id])state.sectors[id]={sx,sy};return state.sectors[id]}
  function sectorResolved(sx,sy){for(let i=0;i<SIZE*SIZE;i++){const{x,y}=coords(sx,sy,i),id=key(x,y);if(mineAt(x,y)?!state.flags.has(id)&&!state.open.has(id):!state.open.has(id))return false}return true}
  function save(immediate=false){clearTimeout(saveTimer);const write=()=>localStorage.setItem(SAVE_KEY,JSON.stringify({seed:state.seed,sectors:state.sectors,unlocked:[...state.unlocked],complete:[...state.complete],blown:[...state.blown],safe:[...state.safe],open:[...state.open],flags:[...state.flags],credited:[...state.credited],damage:state.damage,score:state.score,wins:state.wins,over:false,started:state.started,newest:state.newest,cursor:state.cursor}));if(immediate)write();else saveTimer=setTimeout(write,100)}
  function setResult(kind,kicker,title,message){$("result-card").dataset.state=kind;$("result-kicker").textContent=kicker;$("result-title").textContent=title;$("result-message").textContent=message;$("status").textContent=message}
  function updateBest(){const best=Math.max(Number(localStorage.getItem(BEST_KEY)||0),state.score);localStorage.setItem(BEST_KEY,String(best));$("blasts").textContent=Object.values(state.damage).reduce((sum,value)=>sum+value,0);return best}
  function updateHud(){ $("score").textContent=state.score.toLocaleString();$("wins").textContent=state.wins;$("mines-cleared").textContent=state.credited.size;$("best").textContent=updateBest().toLocaleString();$("difficulty").value="infinite";$("flag-mode").setAttribute("aria-pressed",String(state.flagMode));$("flag-mode").setAttribute("aria-label",state.flagMode?"Disable flag mode":"Enable flag mode");$("sound").setAttribute("aria-pressed",String(state.sound));$("sound").setAttribute("aria-label",state.sound?"Mute sound":"Enable sound");$("sound").title=state.sound?"Mute sound":"Enable sound";$("sound").textContent=state.sound?"🔊":"🔇";}

  function newWorld(){Object.assign(state,{seed:crypto.getRandomValues(new Uint32Array(1))[0],sectors:{},unlocked:new Set(["0,0"]),complete:new Set(),blown:new Set(),safe:new Set(),open:new Set(),flags:new Set(),credited:new Set(),damage:{},score:0,wins:0,over:false,flagMode:false,newest:"0,0",started:false,cursor:{x:8,y:8}});getSector(0,0);topologyDirty=true;setResult("ready","Central sector","World ready","Reveal a safe edge square to unlock the neighboring 16 × 16 sector.");render(true);save()}
  function unlock(sx,sy,side){const offsets={left:[-1,0],right:[1,0],top:[0,-1],bottom:[0,1]},[dx,dy]=offsets[side],id=sectorKey(sx+dx,sy+dy);if(state.unlocked.has(id))return false;state.unlocked.add(id);getSector(sx+dx,sy+dy);state.newest=id;topologyDirty=true;setResult("playing","Route expanded","New sector unlocked",`The ${side} edge opened another 16 × 16 field.`);return true}
  function unlockFromEdge(sx,sy,index){const row=Math.floor(index/SIZE),col=index%SIZE;let added=false;if(col===0)added=unlock(sx,sy,"left")||added;if(col===SIZE-1)added=unlock(sx,sy,"right")||added;if(row===0)added=unlock(sx,sy,"top")||added;if(row===SIZE-1)added=unlock(sx,sy,"bottom")||added;return added}
  function flood(sx,sy,start){const queue=[{sx,sy,index:start}],seen=new Set();for(let qi=0;qi<queue.length;qi++){const current=queue[qi],sid=sectorKey(current.sx,current.sy),{x,y}=coords(current.sx,current.sy,current.index),id=key(x,y);if(state.blown.has(sid)||seen.has(id)||state.flags.has(id)||mineAt(x,y))continue;seen.add(id);if(!state.open.has(id)){state.open.add(id);dirtySectors.add(sid);state.score++}unlockFromEdge(current.sx,current.sy,current.index);if(adjacent(x,y)===0){for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const nx=x+dx,ny=y+dy,nsx=Math.floor(nx/SIZE),nsy=Math.floor(ny/SIZE),next=sectorKey(nsx,nsy);if(state.unlocked.has(next)&&!state.blown.has(next))queue.push({sx:nsx,sy:nsy,index:(ny-nsy*SIZE)*SIZE+(nx-nsx*SIZE)})}}}}
  function blowSector(sx,sy){const sid=sectorKey(sx,sy);state.blown.add(sid);state.damage[sid]=1;for(const side of ["left","right","top","bottom"])unlock(sx,sy,side);dirtySectors.add(sid);state.score=Math.max(0,state.score-300);sound("blast");setResult("lost","Mine detonated","Sector blown","−300 points. This field is permanently locked; its neighboring sectors are now active.")}
  function reveal(sx,sy,index){const sid=sectorKey(sx,sy),{x,y}=coords(sx,sy,index),id=key(x,y);if(state.blown.has(sid)||state.flags.has(id))return;if(!state.started){state.started=true;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const safeId=key(x+dx,y+dy);if(!state.flags.has(safeId))state.safe.add(safeId)}setResult("playing","Infinite run","Edges reveal the way","Clear sectors for bonuses, or explore through any safe edge square.")}if(state.open.has(id)){if(!mineAt(x,y))chord(sx,sy,index);return}if(mineAt(x,y)){state.open.add(id);blowSector(sx,sy);refresh();save();return}sound("reveal");flood(sx,sy,index);checkSectors();refresh();save()}
  function chord(sx,sy,index){const{x,y}=coords(sx,sy,index),count=adjacent(x,y);if(!count)return;const around=[];for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++)if(dx||dy)around.push({x:x+dx,y:y+dy});if(around.filter(p=>state.flags.has(key(p.x,p.y))).length!==count)return;if(around.some(p=>state.flags.has(key(p.x,p.y))&&!mineAt(p.x,p.y))){setResult("playing","Check your flags","Chord held","At least one surrounding flag is misplaced. No squares were opened.");return}around.forEach(p=>{const nsx=Math.floor(p.x/SIZE),nsy=Math.floor(p.y/SIZE);if(state.unlocked.has(sectorKey(nsx,nsy)))flood(nsx,nsy,(p.y-nsy*SIZE)*SIZE+(p.x-nsx*SIZE))});checkSectors();refresh();save()}
  function toggleFlag(sx,sy,index){const{x,y}=coords(sx,sy,index),id=key(x,y),sid=sectorKey(sx,sy);if(state.open.has(id)||state.complete.has(sid)||state.blown.has(sid))return;dirtySectors.add(sid);sound("flag");if(state.flags.has(id)){state.flags.delete(id);refresh();save();return}if(!state.started){state.flags.add(id);setResult("ready","Field marked","Flag placed","Your first revealed square and its unflagged surroundings will still be safe.");refresh();save();return}if(mineAt(x,y)){state.flags.add(id);creditFlags();setResult("playing","Mine claim","Flag placed","Correctly secured mines earn points once the surrounding evidence confirms them.");checkSectors()}else{flood(sx,sy,index);state.score=Math.max(0,state.score-FLAG_MISS);setResult("playing","Incorrect flag","Safe square cleared",`−${FLAG_MISS} points. The square was safe and has been revealed.`);checkSectors()}refresh();save()}
  function creditFlags(){for(const id of state.flags){if(state.credited.has(id))continue;const[x,y]=id.split(",").map(Number);if(!mineAt(x,y))continue;let proven=false;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;const nx=x+dx,ny=y+dy,nid=key(nx,ny);if(state.open.has(nid)&&adjacent(nx,ny)>0){const hidden=[];for(let ay=-1;ay<=1;ay++)for(let ax=-1;ax<=1;ax++)if(ax||ay){const aid=key(nx+ax,ny+ay);if(!state.open.has(aid))hidden.push(aid)}if(hidden.every(h=>state.flags.has(h)&&mineAt(...h.split(",").map(Number))))proven=true}}if(proven){state.credited.add(id);state.score+=MINE_SCORE}}}
  function checkSectors(){for(const id of dirtySectors){if(state.complete.has(id))continue;const{sx,sy}=getSector(...id.split(",").map(Number));if(sectorResolved(sx,sy)){const bonus=Math.max(0,SECTOR_BONUS-(state.damage[id]||0)*250);state.complete.add(id);state.wins++;state.score+=bonus;sound("win");setResult("won","Sector secured",`${state.wins} sector${state.wins===1?"":"s"} cleared`,`Completion bonus +${bonus.toLocaleString()}${state.damage[id]?` after ${state.damage[id]} detonation${state.damage[id]===1?"":"s"}`:" for a clean sweep"}.`)}}creditFlags()}

  const numberColors=[0,0x67d9ff,0x65e6a4,0xffd75e,0xb88cff,0xff7a80,0x55e5df,0xf1f6fa,0xaab8c6];
  function makeText(text,x,y,color,size=12){const label=new PIXI.Text(text,{fontFamily:"ui-monospace, SFMono-Regular, Menlo, monospace",fontSize:size,fontWeight:"900",fill:color,align:"center"});label.anchor.set(.5);label.position.set(x,y);label.resolution=Math.min(devicePixelRatio||1,2);return label}
  function drawClosedCell(g,x,y,size,dormant=false){const bevel=2,outer=dormant?0x10283a:0x0c1d2b,face=dormant?0x1b384d:0x27465e,light=dormant?0x31536a:0x3e6078,shadow=dormant?0x122b3e:0x152e42,center=dormant?0x193448:0x223f56;g.beginFill(outer);g.drawRect(x,y,size,size);g.endFill();g.beginFill(face);g.drawRect(x+1,y+1,size-2,size-2);g.endFill();g.beginFill(light);g.drawRect(x+2,y+2,size-4,bevel);g.drawRect(x+2,y+2,bevel,size-4);g.endFill();g.beginFill(shadow);g.drawRect(x+2,y+size-bevel-2,size-4,bevel);g.drawRect(x+size-bevel-2,y+2,bevel,size-4);g.endFill();g.beginFill(center);g.drawRect(x+bevel+1,y+bevel+1,size-bevel*2-2,size-bevel*2-2);g.endFill()}
  function drawSector(id,dormant=false){let container=sectorViews.get(id);if(container){container.removeChildren().forEach(child=>child.destroy());}else{container=new PIXI.Container();sectorViews.set(id,container);world.addChild(container)}const[sx,sy]=id.split(",").map(Number);container.position.set(sx*STEP,sy*STEP);container.alpha=dormant?.7:1;container.visible=true;container._dormant=dormant;const g=new PIXI.Graphics();container.addChild(g);if(dormant){g.beginFill(0x526f86,.5);g.drawRect(0,0,SECTOR,SECTOR);g.endFill();g.beginFill(0x0d2030,.88);g.drawRect(1,1,SECTOR-2,SECTOR-2);g.endFill();for(let row=0;row<SIZE;row++)for(let col=0;col<SIZE;col++)drawClosedCell(g,col*PITCH,row*PITCH,CELL,true);container.addChild(makeText("DORMANT",45,10,0x9ab2c7,8));return}
    const borderColor=state.complete.has(id)?0x65e6a4:0x39708d,borderAlpha=state.complete.has(id)?.85:.68,borderSize=state.complete.has(id)?2:1;g.beginFill(borderColor,borderAlpha);g.drawRect(0,0,SECTOR,SECTOR);g.endFill();g.beginFill(0x07111d,1);g.drawRect(borderSize,borderSize,SECTOR-borderSize*2,SECTOR-borderSize*2);g.endFill();
    g.lineStyle(0);for(let i=0;i<SIZE*SIZE;i++){const{x,y}=coords(sx,sy,i),cid=key(x,y),open=state.open.has(cid),flag=state.flags.has(cid),mine=open&&mineAt(x,y),col=i%SIZE,row=Math.floor(i/SIZE),px=col*PITCH,py=row*PITCH;if(!open&&!flag)drawClosedCell(g,px,py,CELL);else{g.beginFill(mine?0xb92d3a:open?0x08131f:0xd93442,1);g.drawRect(px,py,CELL,CELL);g.endFill()}if(flag&&!open){g.beginFill(0xffffff);g.drawRect(px+8,py+6,2,14);g.drawPolygon([px+10,py+6,px+19,py+10,px+10,py+14]);g.endFill()}else if(mine){g.beginFill(0x180306);g.drawCircle(px+13,py+13,6);g.endFill()}else if(open){const n=adjacent(x,y);if(n)container.addChild(makeText(String(n),px+13,py+13,numberColors[n],12))}}
    if(state.complete.has(id)){g.beginFill(0x65e6a4,.9);g.drawRect(0,0,SECTOR,2);g.drawRect(0,SECTOR-2,SECTOR,2);g.drawRect(0,0,2,SECTOR);g.drawRect(SECTOR-2,0,2,SECTOR);g.endFill()}if(!state.blown.has(id)&&hoverCell&&hoverCell.sx===sx&&hoverCell.sy===sy){const col=hoverCell.index%SIZE,row=Math.floor(hoverCell.index/SIZE),px=col*PITCH,py=row*PITCH;g.beginFill(0x55c7ff,.75);g.drawRect(px,py,CELL,2);g.drawRect(px,py+CELL-2,CELL,2);g.drawRect(px,py,2,CELL);g.drawRect(px+CELL-2,py,2,CELL);g.endFill()}if(!state.blown.has(id)&&document.activeElement===viewport&&Math.floor(state.cursor.x/SIZE)===sx&&Math.floor(state.cursor.y/SIZE)===sy){const col=state.cursor.x-sx*SIZE,row=state.cursor.y-sy*SIZE,px=col*PITCH,py=row*PITCH;g.beginFill(0xffd166,1);g.drawRect(px,py,CELL,2);g.drawRect(px,py+CELL-2,CELL,2);g.drawRect(px,py,2,CELL);g.drawRect(px+CELL-2,py,2,CELL);g.endFill()}if(state.blown.has(id)){const lock=new PIXI.Graphics();lock.beginFill(0x64717a,.48);lock.drawRect(2,2,SECTOR-4,SECTOR-4);lock.endFill();lock.beginFill(0xff5263,1);lock.drawRect(0,0,SECTOR,3);lock.drawRect(0,SECTOR-3,SECTOR,3);lock.drawRect(0,0,3,SECTOR);lock.drawRect(SECTOR-3,0,3,SECTOR);lock.endFill();container.addChild(lock);container.addChild(makeText("BLOWN",SECTOR/2,15,0xffd6da,14))}else container.addChild(makeText(state.complete.has(id)?"SECURED":`${sx},${sy}`,22,7,state.complete.has(id)?0x65e6a4:0x9ab2c7,7));
  }
  function dormantIds(){const result=new Set(),directions=[[1,0],[-1,0],[0,1],[0,-1]];for(const id of state.unlocked){const[sx,sy]=id.split(",").map(Number);for(const[dx,dy]of directions){const next=sectorKey(sx+dx,sy+dy);if(!state.unlocked.has(next))result.add(next)}}return result}
  function drawMinimap(){const canvas=$("minimap");if(!canvas)return;const ctx=canvas.getContext("2d"),ids=new Set([...state.unlocked,...dormantIds()]);if(!ids.size)return;const points=[...ids].map(id=>id.split(",").map(Number)),minX=Math.min(...points.map(p=>p[0])),maxX=Math.max(...points.map(p=>p[0])),minY=Math.min(...points.map(p=>p[1])),maxY=Math.max(...points.map(p=>p[1])),pad=18,cols=maxX-minX+1,rows=maxY-minY+1,cell=Math.max(5,Math.min(34,(canvas.width-pad*2)/cols,(canvas.height-pad*2)/rows)),ox=(canvas.width-cols*cell)/2,oy=(canvas.height-rows*cell)/2;minimapTransform={minX,minY,cell,ox,oy};ctx.clearRect(0,0,canvas.width,canvas.height);for(const id of ids){const[sx,sy]=id.split(",").map(Number),x=ox+(sx-minX)*cell,y=oy+(sy-minY)*cell;ctx.fillStyle=state.blown.has(id)?"#6b7279":state.complete.has(id)?"#65e6a4":state.unlocked.has(id)?"#39708d":"#132c3e";ctx.fillRect(x+1,y+1,cell-2,cell-2);if(state.blown.has(id)){ctx.strokeStyle="#ff5263";ctx.lineWidth=2;ctx.strokeRect(x+1,y+1,cell-2,cell-2)}}const vx=(-world.x+app.screen.width/2)/STEP,vy=(-world.y+app.screen.height/2)/STEP;ctx.strokeStyle="#ffd166";ctx.lineWidth=3;ctx.strokeRect(ox+(vx-minX)*cell-cell*.2,oy+(vy-minY)*cell-cell*.2,cell*.4,cell*.4)}
  function navigateFromMinimap(event){if(!minimapTransform)return;const canvas=$("minimap"),rect=canvas.getBoundingClientRect(),mx=(event.clientX-rect.left)*canvas.width/rect.width,my=(event.clientY-rect.top)*canvas.height/rect.height,{minX,minY,cell,ox,oy}=minimapTransform,sx=Math.floor((mx-ox)/cell)+minX,sy=Math.floor((my-oy)/cell)+minY,id=sectorKey(sx,sy);if(!state.unlocked.has(id))return;setWorldPosition(app.screen.width/2-(sx*STEP+SECTOR/2),app.screen.height/2-(sy*STEP+SECTOR/2))}
  function cullSectors(){const margin=STEP,left=-world.x-margin,top=-world.y-margin,right=left+app.screen.width+margin*2,bottom=top+app.screen.height+margin*2;for(const view of sectorViews.values())view.visible=view.x+SECTOR>=left&&view.x<=right&&view.y+SECTOR>=top&&view.y<=bottom}
  function syncWorld(){const dormant=dormantIds(),wanted=new Set([...state.unlocked,...dormant]);for(const[id,view]of sectorViews)if(!wanted.has(id)){world.removeChild(view);view.destroy({children:true});sectorViews.delete(id)}for(const id of state.unlocked)drawSector(id,false);for(const id of dormant)drawSector(id,true);topologyDirty=false;dirtySectors.clear();cullSectors()}
  function refresh(){const start=performance.now();if(topologyDirty)syncWorld();else{for(const id of dirtySectors)drawSector(id,false);dirtySectors.clear()}updateHud();drawMinimap();$("world").dataset.lastUpdateMs=(performance.now()-start).toFixed(2)}
  function render(center=false){syncWorld();updateHud();if(center)centerWorld()}
  function setWorldPosition(x,y){const scale=app.renderer.resolution||1;world.position.set(Math.round(x*scale)/scale,Math.round(y*scale)/scale);cullSectors();drawMinimap()}
  function centerWorld(){setWorldPosition(app.screen.width/2-SECTOR/2,app.screen.height/2-SECTOR/2)}
  $("minimap").addEventListener("pointerdown",navigateFromMinimap);
  $("minimap").addEventListener("keydown",event=>{const moves={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]},move=moves[event.key];if(!move)return;event.preventDefault();const sx=Math.floor((-world.x+app.screen.width/2)/STEP)+move[0],sy=Math.floor((-world.y+app.screen.height/2)/STEP)+move[1],id=sectorKey(sx,sy);if(state.unlocked.has(id))setWorldPosition(app.screen.width/2-(sx*STEP+SECTOR/2),app.screen.height/2-(sy*STEP+SECTOR/2))});

  function hitCell(clientX,clientY){const rect=app.view.getBoundingClientRect(),px=(clientX-rect.left)*app.screen.width/rect.width-world.x,py=(clientY-rect.top)*app.screen.height/rect.height-world.y,sx=Math.floor(px/STEP),sy=Math.floor(py/STEP),lx=px-sx*STEP,ly=py-sy*STEP;if(lx<0||ly<0||lx>=SECTOR||ly>=SECTOR)return null;const col=Math.floor(lx/PITCH),row=Math.floor(ly/PITCH);if(lx-col*PITCH>=CELL||ly-row*PITCH>=CELL)return null;const id=sectorKey(sx,sy);return state.unlocked.has(id)&&!state.blown.has(id)?{sx,sy,index:row*SIZE+col}:null}
  function cursorSectorId(){return sectorKey(Math.floor(state.cursor.x/SIZE),Math.floor(state.cursor.y/SIZE))}
  function ensureCursorVisible(){const sx=Math.floor(state.cursor.x/SIZE),sy=Math.floor(state.cursor.y/SIZE),col=state.cursor.x-sx*SIZE,row=state.cursor.y-sy*SIZE,x=sx*STEP+col*PITCH+CELL/2+world.x,y=sy*STEP+row*PITCH+CELL/2+world.y,margin=42;let nx=world.x,ny=world.y;if(x<margin)nx+=margin-x;else if(x>app.screen.width-margin)nx-=x-(app.screen.width-margin);if(y<margin)ny+=margin-y;else if(y>app.screen.height-margin)ny-=y-(app.screen.height-margin);setWorldPosition(nx,ny)}
  function moveCursor(dx,dy){const old=cursorSectorId(),next={x:state.cursor.x+dx,y:state.cursor.y+dy},sid=sectorKey(Math.floor(next.x/SIZE),Math.floor(next.y/SIZE));if(!state.unlocked.has(sid))return;state.cursor=next;dirtySectors.add(old);dirtySectors.add(sid);ensureCursorVisible();refresh()}
  function act(cell,flag=state.flagMode){const started=performance.now(),old=cursorSectorId(),point=coords(cell.sx,cell.sy,cell.index);state.cursor={x:point.x,y:point.y};dirtySectors.add(old);flag?toggleFlag(cell.sx,cell.sy,cell.index):reveal(cell.sx,cell.sy,cell.index);$("world").dataset.lastActionMs=(performance.now()-started).toFixed(2)}
  app.view.addEventListener("pointerdown",event=>{if(event.button!==0)return;viewport.focus({preventScroll:true});const selected=hitCell(event.clientX,event.clientY);if(selected){const old=cursorSectorId(),point=coords(selected.sx,selected.sy,selected.index);state.cursor={x:point.x,y:point.y};dirtySectors.add(old);dirtySectors.add(selected.sx+","+selected.sy)}pointer={id:event.pointerId,x:event.clientX,y:event.clientY,worldX:world.x,worldY:world.y,dragged:false};held=false;app.view.setPointerCapture(event.pointerId);if(event.pointerType!=="mouse")holdTimer=setTimeout(()=>{const cell=hitCell(event.clientX,event.clientY);if(cell){held=true;act(cell,true);navigator.vibrate?.(25)}},480)});
  app.view.addEventListener("pointermove",event=>{if(!pointer){if(event.pointerType==="mouse"){const next=hitCell(event.clientX,event.clientY),old=hoverCell&&sectorKey(hoverCell.sx,hoverCell.sy),fresh=next&&sectorKey(next.sx,next.sy),changed=(!next)!==(!hoverCell)||(next&&hoverCell&&(next.sx!==hoverCell.sx||next.sy!==hoverCell.sy||next.index!==hoverCell.index));if(changed){hoverCell=next;if(old)dirtySectors.add(old);if(fresh)dirtySectors.add(fresh);refresh()}}return}if(event.pointerId!==pointer.id)return;const dx=event.clientX-pointer.x,dy=event.clientY-pointer.y;if(!pointer.dragged&&Math.hypot(dx,dy)<2)return;pointer.dragged=true;clearTimeout(holdTimer);viewport.classList.add("dragging");setWorldPosition(pointer.worldX+dx,pointer.worldY+dy)});
  function endPointer(event){if(!pointer||event.pointerId!==pointer.id)return;clearTimeout(holdTimer);viewport.classList.remove("dragging");if(!pointer.dragged&&!held){const cell=hitCell(event.clientX,event.clientY);if(cell)act(cell)}pointer=null}
  app.view.addEventListener("pointerup",endPointer);app.view.addEventListener("pointercancel",event=>{clearTimeout(holdTimer);viewport.classList.remove("dragging");pointer=null});
  app.view.addEventListener("pointerleave",()=>{if(hoverCell){dirtySectors.add(sectorKey(hoverCell.sx,hoverCell.sy));hoverCell=null;refresh()}});
  app.view.addEventListener("contextmenu",event=>{event.preventDefault();const cell=hitCell(event.clientX,event.clientY);if(cell)act(cell,true)});
  viewport.addEventListener("wheel",event=>{setWorldPosition(world.x-event.deltaX,world.y-event.deltaY);event.preventDefault()},{passive:false});
  new ResizeObserver(cullSectors).observe(viewport);
  viewport.addEventListener("focus",()=>{dirtySectors.add(cursorSectorId());refresh()});viewport.addEventListener("blur",()=>{dirtySectors.add(cursorSectorId());refresh()});viewport.addEventListener("keydown",event=>{if(event.key==="ArrowLeft"){event.preventDefault();moveCursor(-1,0)}else if(event.key==="ArrowRight"){event.preventDefault();moveCursor(1,0)}else if(event.key==="ArrowUp"){event.preventDefault();moveCursor(0,-1)}else if(event.key==="ArrowDown"){event.preventDefault();moveCursor(0,1)}else if(event.key==="Enter"||event.key===" "){event.preventDefault();const sx=Math.floor(state.cursor.x/SIZE),sy=Math.floor(state.cursor.y/SIZE);act({sx,sy,index:(state.cursor.y-sy*SIZE)*SIZE+state.cursor.x-sx*SIZE})}else if(event.key==="f"||event.key==="F"){event.preventDefault();const sx=Math.floor(state.cursor.x/SIZE),sy=Math.floor(state.cursor.y/SIZE);act({sx,sy,index:(state.cursor.y-sy*SIZE)*SIZE+state.cursor.x-sx*SIZE},true)}});
  addEventListener("beforeunload",()=>save(true));$("difficulty").addEventListener("change",event=>{const next=event.target.value;if(next==="infinite")return;if(state.started&&(state.open.size||state.flags.size)&&!confirm("Change fields? Your current Infinite run will remain saved.")){event.target.value="infinite";return}location.href=`index.html?mode=${encodeURIComponent(next)}`});$("sound").addEventListener("click",()=>{state.sound=!state.sound;localStorage.setItem(SOUND_KEY,state.sound?"on":"off");if(state.sound)sound("reveal");updateHud()});$("flag-mode").addEventListener("click",()=>{state.flagMode=!state.flagMode;updateHud()});$("center").addEventListener("click",centerWorld);$("new-world").addEventListener("click",()=>{if(state.started&&(state.open.size||state.flags.size)&&!confirm("Start a new Infinite world? Your current run will be replaced."))return;newWorld()});
  function load(){try{const saved=JSON.parse(localStorage.getItem(SAVE_KEY)||"{}");if(saved.seed&&saved.unlocked?.length){Object.assign(state,saved,{unlocked:new Set(saved.unlocked),complete:new Set(saved.complete||[]),blown:new Set(saved.blown||[]),safe:new Set(saved.safe||[]),open:new Set(saved.open||[]),flags:new Set(saved.flags||[]),credited:new Set(saved.credited||[]),damage:saved.damage||{},over:false,flagMode:false,cursor:saved.cursor||{x:8,y:8}});for(const id of [...state.complete]){const[sx,sy]=id.split(",").map(Number);if(!sectorResolved(sx,sy)){state.complete.delete(id);state.wins=Math.max(0,state.wins-1);state.score=Math.max(0,state.score-Math.max(0,SECTOR_BONUS-(state.damage[id]||0)*250));dirtySectors.add(id)}}setResult("playing","Infinite run","Continue exploring","Reveal a safe edge square to expand the world.");topologyDirty=true;render(true);save();return}}catch{}newWorld()}
  load();
})();
