(() => {
  "use strict";
  const SETTINGS_KEY="jasondaemon.game.snake.settings.v1";
  const difficulty={easy:{start:5,ramp:50,max:11},normal:{start:6,ramp:40,max:13},hard:{start:7,ramp:30,max:15}};
  const canvas=document.getElementById("game"),ctx=canvas.getContext("2d"),message=document.getElementById("message"),grid=20,cell=canvas.width/grid;
  let settings={difficulty:"normal",walls:"wrap",sound:true};try{settings={...settings,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||"{}")}}catch{}
  let snake,direction,pending,queue,food,special,score,speed,mode="intro",accumulator=0,lastTime=performance.now(),audio;
  const $=id=>document.getElementById(id);
  const best=()=>GameScores.game("snake").best[`solo:${settings.difficulty}:score`]?.value||0;
  function saveSettings(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings))}
  function tone(freq,duration=.07,type="square"){if(!settings.sound)return;audio=audio||new (window.AudioContext||window.webkitAudioContext)();if(audio.state!=="running")audio.resume().catch(()=>{});const osc=audio.createOscillator(),gain=audio.createGain();osc.frequency.value=freq;osc.type=type;gain.gain.value=.14;osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+duration)}
  function available(excludeFood=false){const occupied=new Set(snake.map(segment=>`${segment.x},${segment.y}`)),out=[];for(let y=0;y<grid;y++)for(let x=0;x<grid;x++)if(!occupied.has(`${x},${y}`)&&(!excludeFood||x!==food.x||y!==food.y))out.push({x,y});return out}
  function spawnFood(){const cells=available();food=cells[Math.floor(Math.random()*cells.length)]||{x:0,y:0}}
  function reset(){snake=[{x:10,y:10}];direction={x:1,y:0};pending=direction;queue=[];special=null;score=0;speed=difficulty[settings.difficulty].start;accumulator=0;spawnFood();updateScore();showMessage("Snake","Use arrow keys, WASD, or the controls below.","Press Space to start · P to pause · R to restart")}
  function start(){reset();mode="playing";message.hidden=true;tone(330,.05,"triangle")}
  function showMessage(title,text,hint){message.hidden=false;message.querySelector("strong").textContent=title;message.querySelector("span").textContent=text;message.querySelector("small").textContent=hint}
  function updateScore(){$("score").textContent=score;$("best").textContent=best()}
  function queueDirection(next){const last=queue.length?queue[queue.length-1]:pending;if(last.x+next.x===0&&last.y+next.y===0)return;queue.push(next)}
  function end(){mode="gameover";tone(115,.2,"sawtooth");const result=GameScores.record({game:"snake",difficulty:settings.difficulty,metric:"score",value:score,meta:{walls:settings.walls}});updateScore();showMessage("Game over",`Score ${score}${result?.best?" · New local best!":""}`,"Press R or tap Start game")}
  function step(dt){if(mode!=="playing")return;accumulator+=dt;const tick=1/speed;while(accumulator>=tick){accumulator-=tick;if(queue.length){const next=queue.shift();if(direction.x+next.x!==0||direction.y+next.y!==0)pending=next}direction=pending;const head=snake[0],next={x:head.x+direction.x,y:head.y+direction.y};if(settings.walls==="wrap"){next.x=(next.x+grid)%grid;next.y=(next.y+grid)%grid}else if(next.x<0||next.x>=grid||next.y<0||next.y>=grid){end();return}if(snake.some(segment=>segment.x===next.x&&segment.y===next.y)){end();return}snake.unshift(next);let ate=false;if(next.x===food.x&&next.y===food.y){score+=10;ate=true;tone(520);spawnFood();if(Math.random()<.18){const cells=available(true);special=cells[Math.floor(Math.random()*cells.length)]||null}}else if(special&&next.x===special.x&&next.y===special.y){score+=30;ate=true;special=null;tone(680,.1,"triangle")}if(!ate)snake.pop();const level=difficulty[settings.difficulty];speed=Math.min(level.max,level.start+Math.floor(score/level.ramp));updateScore()}}
  function draw(){const gradient=ctx.createLinearGradient(0,0,0,canvas.height);gradient.addColorStop(0,"#0d1d2b");gradient.addColorStop(1,"#07111b");ctx.fillStyle=gradient;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle="rgba(255,255,255,.045)";ctx.lineWidth=1;for(let i=0;i<=grid;i++){ctx.beginPath();ctx.moveTo(i*cell,0);ctx.lineTo(i*cell,canvas.height);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i*cell);ctx.lineTo(canvas.width,i*cell);ctx.stroke()}ctx.fillStyle="#ff6f91";ctx.beginPath();ctx.arc(food.x*cell+cell/2,food.y*cell+cell/2,cell*.34,0,Math.PI*2);ctx.fill();if(special){ctx.fillStyle="#ffd166";ctx.beginPath();ctx.arc(special.x*cell+cell/2,special.y*cell+cell/2,cell*.39,0,Math.PI*2);ctx.fill()}snake.forEach((segment,index)=>{ctx.fillStyle=index===0?"#55c7ff":"#62e4bd";ctx.beginPath();ctx.roundRect(segment.x*cell+2,segment.y*cell+2,cell-4,cell-4,5);ctx.fill();if(index===0){ctx.fillStyle="#07111b";ctx.beginPath();ctx.arc(segment.x*cell+cell/2+direction.x*5,segment.y*cell+cell/2+direction.y*5,2.7,0,Math.PI*2);ctx.fill()}})}
  function loop(now){const dt=Math.min(.05,(now-lastTime)/1000);lastTime=now;step(dt);draw();requestAnimationFrame(loop)}
  const directions={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}};
  addEventListener("keydown",event=>{const key=event.key.toLowerCase();if(["arrowup","arrowdown","arrowleft","arrowright"," "].includes(key))event.preventDefault();if(key==="r")start();else if(key==="p"&&mode==="playing"){mode="paused";showMessage("Paused","The snake can wait.","Press P to continue")}else if(key==="p"&&mode==="paused"){mode="playing";message.hidden=true}else if(key===" "&&mode!=="playing")start();else if(mode==="playing"){if(key==="arrowup"||key==="w")queueDirection(directions.up);if(key==="arrowdown"||key==="s")queueDirection(directions.down);if(key==="arrowleft"||key==="a")queueDirection(directions.left);if(key==="arrowright"||key==="d")queueDirection(directions.right)}});
  document.querySelectorAll("[data-direction]").forEach(button=>button.addEventListener("pointerdown",event=>{event.preventDefault();if(mode!=="playing")start();queueDirection(directions[button.dataset.direction])}));$("start").addEventListener("click",start);$("difficulty").value=settings.difficulty;$("walls").value=settings.walls;$("difficulty").addEventListener("change",event=>{settings.difficulty=event.target.value;saveSettings();reset();mode="intro"});$("walls").addEventListener("change",event=>{settings.walls=event.target.value;saveSettings()});$("sound").addEventListener("click",event=>{settings.sound=!settings.sound;event.currentTarget.textContent=settings.sound?"Sound on":"Sound off";event.currentTarget.setAttribute("aria-pressed",String(settings.sound));saveSettings()});reset();requestAnimationFrame(loop);
})();
