(() => {
  "use strict";
  const W=960,H=720,LAPS=5,CARS=4,ROAD_WIDTH=78,CAR_W=16,CAR_H=27,CAR_RADIUS=13,STEP=1/120,$=id=>document.getElementById(id);
  const TAU=Math.PI*2,SAVE="circuit_rush_a9",ASSET_REV="1.1.0",clamp=Phaser.Math.Clamp,wrapAngle=a=>Math.atan2(Math.sin(a),Math.cos(a));
  const TRACKS=[
    {name:"Harbor Loop",subtitle:"Fast shoreline sweepers",music:"harbor-loop.mp3",musicTrim:1,scale:1,art:"harbor-art",trace:"harbor-trace",surface:{road:"harbor-track-mask",runoff:"harbor-runoff-mask",guide:"harbor-center-guide"},ground:0x286247,ground2:0x183f38,road:0x343b43,edge:0x15222a,accent:0x62dff4,controls:[[.5,.4]]},
    {name:"Foundry Eight",subtitle:"A split-level crossover circuit",music:"foundry-eight.mp3",musicTrim:1,scale:.9,art:"foundry-art",trace:"foundry-trace",surface:{road:"foundry-track-mask",runoff:"foundry-runoff-mask",guide:"foundry-center-guide"},bridge:{center:.745,length:14},overlay:"foundry-overlay",ground:0x68482d,ground2:0x3c2b22,road:0x3d4147,edge:0xcbd2d4,accent:0xef625c,controls:[[.5,.4]]},
    {name:"Alpine Crown",subtitle:"Technical mountain switchbacks",music:"alpine-crown.mp3",musicTrim:1,scale:.73,art:"alpine-art",trace:"alpine-trace",surface:{road:"alpine-track-mask",runoff:"alpine-runoff-mask",guide:"alpine-center-guide"},overlay:"alpine-overlay",cones:[[38,-29],[41,-25],[101,28],[104,25],[172,-27],[175,-24]],ground:0x3e6a43,ground2:0x213f30,road:0x383f43,edge:0x17232b,accent:0xff6dbb,controls:[[.5,.4]]},
    {name:"Sunscar Chicane",subtitle:"Hot canyon sweepers and offsets",music:"sunscar.mp3",musicTrim:1,scale:1,art:"sunscar-art",trace:"sunscar-trace",surface:{road:"sunscar-track-mask",runoff:"sunscar-runoff-mask",guide:"sunscar-center-guide"},cones:[[72,25],[75,22],[155,-24],[158,-22]],controls:[[.5,.4]]},
    {name:"Glacier Run",subtitle:"Low-grip winter esses",music:"glacier-run.mp3",musicTrim:1,scale:.89,art:"glacier-art",trace:"glacier-trace",surface:{road:"glacier-track-mask",runoff:"glacier-runoff-mask",guide:"glacier-center-guide"},overlay:"glacier-overlay",cones:[[54,-23],[57,-21],[132,24],[135,22],[205,-22]],controls:[[.5,.4]]},
    {name:"Midnight Crown",subtitle:"The rain-slick championship finale",music:"midnight-crown.mp3",musicTrim:1,scale:.63,art:"midnight-art",trace:"midnight-trace",surface:{road:"midnight-track-mask",runoff:"midnight-runoff-mask",guide:"midnight-center-guide"},bridge:{center:.647,length:15},overlay:"midnight-overlay",cones:[[44,24],[47,22],[148,-23],[151,-21],[190,22]],controls:[[.5,.4]]}
  ];
  const CAR_COLORS=[0x66eaff,0xff5c68,0xffd05b,0x8dff83];
  class CircuitRush extends Phaser.Scene{
    constructor(){super("circuit-rush")}
    preload(){const base="assets/kenney-racing/PNG/",asset=file=>`assets/${file}?v=${ASSET_REV}`;[["harbor-art","harbor-loop-base.png"],["foundry-art","foundry-eight-base.png"],["alpine-art","alpine-crown-base.png"],["sunscar-art","sunscar-base.png"],["glacier-art","glacier-run-base.png"],["midnight-art","midnight-crown-base.png"],["harbor-runoff-mask","harbor-loop-runoff.png"],["harbor-track-mask","harbor-loop-track.png"],["harbor-center-guide","harbor-loop-center.png"],["foundry-runoff-mask","foundry-eight-runoff.png"],["foundry-track-mask","foundry-eight-track.png"],["foundry-center-guide","foundry-eight-center.png"],["foundry-overlay","foundry-eight-overlay.png"],["alpine-runoff-mask","alpine-crown-runoff.png"],["alpine-track-mask","alpine-crown-track.png"],["alpine-center-guide","alpine-crown-center.png"],["alpine-overlay","alpine-crown-overlay.png"],["sunscar-runoff-mask","sunscar-runoff.png"],["sunscar-track-mask","sunscar-road.png"],["sunscar-center-guide","sunscar-centerline.png"],["glacier-runoff-mask","glacier-run-runoff.png"],["glacier-track-mask","glacier-run-track.png"],["glacier-center-guide","glacier-run-center.png"],["glacier-overlay","glacier-run-overlay.png"],["midnight-runoff-mask","midnight-crown-runoff-combined.png"],["midnight-track-mask","midnight-crown-track-combined.png"],["midnight-center-guide","midnight-crown-center-combined.png"],["midnight-overlay","midnight-crown-overlay.png"],["f1-car","f1-car-v1.png"],["prop-oil","prop-oil-v1.png"],["prop-water","prop-water-v1.png"],["prop-wrench","prop-wrench-v1.png"],["prop-tornado","prop-tornado-v2.webp"],["prop-cone","prop-cone-v1.png"]].forEach(([key,file])=>this.load.image(key,asset(file)));[["harbor-trace","harbor-loop-trace.svg"],["foundry-trace","foundry-eight-trace.svg"],["alpine-trace","alpine-crown-trace.svg"],["sunscar-trace","sunscar-chicane-trace.svg"],["glacier-trace","glacier-run-trace.svg"],["midnight-trace","midnight-crown-trace.svg"]].forEach(([key,file])=>this.load.text(key,asset(file)));this.load.image("raster-tree",base+"Objects/tree_large.png");this.load.image("raster-tree-small",base+"Objects/tree_small.png");this.load.image("raster-stand",base+"Objects/tribune_full.png");this.load.image("raster-barrier",base+"Objects/barrier_white.png");this.load.image("raster-lights",base+"Objects/lights.png")}
    create(){
      this.textures.addSpriteSheet("prop-tornado-frames",this.textures.get("prop-tornado").getSourceImage(),{frameWidth:128,frameHeight:128,endFrame:7});this.soundOn=localStorage.getItem(`${SAVE}_effects`)!=="0";this.effectsVolume=clamp(Number(localStorage.getItem(`${SAVE}_effects_volume`)??100),0,100);this.musicEnabled=localStorage.getItem(`${SAVE}_music`)!=="0";const savedMusicVolume=localStorage.getItem(`${SAVE}_music_volume`),wasOldDefault=savedMusicVolume==="32"&&localStorage.getItem(`${SAVE}_music_mix2`)!=="1";this.musicVolume=clamp(savedMusicVolume===null||wasOldDefault?12:Number(savedMusicVolume),0,100);if(wasOldDefault)localStorage.setItem(`${SAVE}_music_volume`,"12");localStorage.setItem(`${SAVE}_music_mix2`,"1");this.music=new Audio();this.music.id="track-music";this.music.hidden=true;this.music.loop=true;this.music.preload="metadata";this.resultMusic=new Audio();this.resultMusic.id="result-music";this.resultMusic.hidden=true;this.resultMusic.loop=false;this.resultMusic.preload="auto";document.body.append(this.music,this.resultMusic);
      scene=this;const params=new URLSearchParams(location.search),testTrack=Number(params.get("testTrack")),savedTrack=localStorage.getItem(`${SAVE}_track`),savedDifficulty=localStorage.getItem(`${SAVE}_difficulty`);this.testMode=Number.isInteger(testTrack)&&testTrack>=1;this.autoTest=params.get("autoplay")==="1";this.debugTrace=params.get("trace")==="1";this.testWin=params.get("testWin")==="1";this.testResult=params.get("testResult");this.raceLaps=clamp(Number(params.get("testLaps"))||LAPS,1,LAPS);this.trackIndex=clamp(this.testMode?testTrack-1:savedTrack===null?0:Number(savedTrack)||0,0,TRACKS.length-1);this.unlocked=clamp(Math.max(Number(localStorage.getItem(`${SAVE}_unlocked`))||0,this.testMode?testTrack-1:0),0,TRACKS.length-1);this.upgrades=this.readUpgrades();this.wrenchBank=clamp(Number(localStorage.getItem(`${SAVE}_wrenches`))||0,0,3);this.trackWrenches=0;this.tour=clamp(Number(localStorage.getItem(`${SAVE}_tour`))||0,0,99);this.difficulty=["easy","normal","hard"].includes(savedDifficulty)?savedDifficulty:"normal";this.soundOn=true;this.accumulator=0;this.state="title";this.keys=this.input.keyboard.addKeys("UP,DOWN,LEFT,RIGHT,W,A,S,D,P");this.touch={left:false,right:false,gas:false,brake:false};this.effectEvents=[];this.createTextures();this.mapArt=this.add.image(0,80,"harbor-art").setOrigin(0).setDepth(0);this.bridgeArt=this.add.image(0,80,"foundry-art").setOrigin(0).setDepth(8).setVisible(false);this.surfaceDebug=[this.add.image(0,80,"sunscar-runoff-mask").setOrigin(0).setDepth(17).setAlpha(.35).setVisible(false),this.add.image(0,80,"sunscar-track-mask").setOrigin(0).setDepth(18).setAlpha(.35).setVisible(false),this.add.image(0,80,"sunscar-center-guide").setOrigin(0).setDepth(19).setVisible(false)];this.world=this.add.graphics().setDepth(.2);this.decor=this.add.graphics().setDepth(2);this.underEffects=this.add.graphics().setDepth(8.5);this.effects=this.add.graphics().setDepth(20);this.cars=[];this.createHud();this.bindUi();this.selectTrack(this.trackIndex);this.refreshTitleScreen();requestAnimationFrame(()=>this.positionTitleScreen());this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>this.stopEngine());
    }
    readUpgrades(){try{const v=JSON.parse(localStorage.getItem(`${SAVE}_upgrades`));return{grip:clamp(v?.grip||0,0,5),power:clamp(v?.power||0,0,5),speed:clamp(v?.speed||0,0,5)}}catch{return{grip:0,power:0,speed:0}}}
    createTextures(){
      CAR_COLORS.forEach((color,i)=>{const g=this.make.graphics({add:false});g.fillStyle(0x000000,.32).fillEllipse(3,5,CAR_W-2,CAR_H-2);g.fillStyle(0x111820).fillRect(0,5,3,6).fillRect(CAR_W-3,5,3,6).fillRect(0,17,3,6).fillRect(CAR_W-3,17,3,6);g.fillStyle(color).fillRoundedRect(2,1,CAR_W-4,CAR_H-2,4);g.fillStyle(0x08131c).fillRoundedRect(4,7,CAR_W-8,11,3);g.fillStyle(0xc9f6ff,.85).fillRect(5,8,CAR_W-10,3);g.fillStyle(0xffffff,.42).fillRect(4,3,CAR_W-8,2);g.generateTexture(`rush-car-${i}`,CAR_W,CAR_H);g.destroy()});
      const g=this.make.graphics({add:false});g.lineStyle(4,0x59646e).strokeCircle(10,10,7);g.lineStyle(2,0xf0f4f6).strokeCircle(10,10,4);g.lineStyle(2,0xffd05b).lineBetween(10,3,10,17).lineBetween(3,10,17,10);g.generateTexture("wrench",20,20);g.clear();g.fillStyle(0x05080a,.92).fillEllipse(17,9,32,17);g.lineStyle(2,0x5d6870,.8).strokeEllipse(17,9,30,15);g.fillStyle(0xaeb8bd,.32).fillEllipse(12,6,12,4);g.generateTexture("oil",34,18);g.clear();g.fillStyle(0x36bfea,.78).fillEllipse(19,9,36,17);g.lineStyle(2,0xbff6ff,.9).strokeEllipse(19,9,34,15);g.fillStyle(0xe8fdff,.62).fillEllipse(14,6,17,4);g.generateTexture("water",38,18);g.destroy();
    }
    createHud(){
      const small={fontFamily:"system-ui",fontSize:"10px",fontStyle:"900",color:"#79eaff",letterSpacing:1.5},big={fontFamily:"system-ui",fontSize:"24px",fontStyle:"900",color:"#f5f8ff"};this.add.rectangle(W/2,34,W,68,0x030911,.78).setDepth(30);this.add.line(W/2,68,0,0,W,0,0x66eaff,.3).setDepth(31);
      this.add.text(20,12,"POSITION",small).setDepth(32);this.positionText=this.add.text(20,28,"1 / 4",big).setDepth(32);this.add.text(150,12,"LAP",small).setDepth(32);this.lapText=this.add.text(150,28,"1 / 5",big).setDepth(32);this.add.text(260,12,"TIME",small).setDepth(32);this.timeText=this.add.text(260,28,"0:00.00",big).setDepth(32);this.add.text(410,12,"BEST",small).setDepth(32);this.bestText=this.add.text(410,30,"--:--.--",{...big,fontSize:"18px",color:"#ffd05b"}).setDepth(32);this.add.text(575,12,"WRENCHES",small).setDepth(32);this.wrenchIcons=Array.from({length:3},(_,i)=>this.add.image(585+i*22,43,"prop-wrench").setScale(.52).setDepth(32));this.trackText=this.add.text(790,20,"HARBOR LOOP",{...small,fontSize:"12px",color:"#ffd05b"}).setOrigin(1,0).setDepth(32);this.message=this.add.text(W/2,H/2,"",{fontFamily:"system-ui",fontSize:"82px",fontStyle:"900",color:"#ffffff",stroke:"#06101a",strokeThickness:10}).setOrigin(.5).setDepth(40);this.statusText=this.add.text(W/2,88,"",{fontFamily:"system-ui",fontSize:"13px",fontStyle:"800",color:"#d9f8ff",backgroundColor:"#07131dcc",padding:{x:10,y:5}}).setOrigin(.5,0).setDepth(40).setAlpha(0);
    }
    bindUi(){
      $("geometry").checked=this.debugTrace;$("difficulty").value=this.difficulty;$("difficulty").onchange=()=>{};$("geometry").onchange=event=>{this.debugTrace=event.currentTarget.checked;this.drawTrack()};$("start").onclick=()=>this.beginNewChampionship();$("continue-game").onclick=()=>this.continueChampionship();$("pause").onclick=()=>this.togglePause();$("settings").onclick=()=>this.openSettings();$("fullscreen").onclick=()=>this.toggleFullscreen();this.input.keyboard.on("keydown-P",()=>this.togglePause());
      const bind=(id,key)=>{const el=$(id),set=value=>{this.touch[key]=value};["pointerdown","pointerenter"].forEach(name=>el.addEventListener(name,e=>{if(e.buttons||name==="pointerdown"){e.preventDefault();set(true)}}));["pointerup","pointercancel","pointerleave"].forEach(name=>el.addEventListener(name,e=>{e.preventDefault();set(false)}))};bind("touch-left","left");bind("touch-right","right");bind("touch-throttle","gas");bind("touch-brake","brake");document.querySelectorAll("[data-upgrade]").forEach(button=>button.onclick=()=>this.applyUpgrade(button.dataset.upgrade));$("result-action").onclick=()=>this.resultPosition===4?this.newGame():this.continueAfterResult();const reposition=()=>{if(!$("overlay").hidden)this.positionTitleScreen();if(!$("upgrade-panel").hidden)this.positionWorkshop();if(!$("result-panel").hidden)this.positionResultStage()};window.addEventListener("resize",reposition);document.addEventListener("fullscreenchange",reposition);document.addEventListener("visibilitychange",()=>{if(document.hidden&&this.state==="racing")this.togglePause()});this.bindAudioSettings();
    }
    bindAudioSettings(){this.soundOn=localStorage.getItem(`${SAVE}_effects`)!=="0";const music=$("music-enabled"),effects=$("effects-enabled"),volume=$("music-volume"),level=$("music-level"),effectsVolume=$("effects-volume"),effectsLevel=$("effects-level");music.checked=this.musicEnabled;effects.checked=this.soundOn;volume.value=this.musicVolume;level.value=`${this.musicVolume}%`;effectsVolume.value=this.effectsVolume;effectsLevel.value=`${this.effectsVolume}%`;music.onchange=()=>{this.musicEnabled=music.checked;localStorage.setItem(`${SAVE}_music`,music.checked?"1":"0");this.applyMusicMix();if(this.musicEnabled&&this.state!=="title")this.playMusic()};effects.onchange=()=>{this.soundOn=effects.checked;localStorage.setItem(`${SAVE}_effects`,effects.checked?"1":"0");if(!this.soundOn)this.stopEngine();else if(this.state==="racing")this.startEngine()};volume.oninput=()=>{this.musicVolume=Number(volume.value);level.value=`${this.musicVolume}%`;localStorage.setItem(`${SAVE}_music_volume`,String(this.musicVolume));this.applyMusicMix()};effectsVolume.oninput=()=>{this.effectsVolume=Number(effectsVolume.value);effectsLevel.value=`${this.effectsVolume}%`;localStorage.setItem(`${SAVE}_effects_volume`,String(this.effectsVolume));this.applyEffectsMix()};$("close-settings").onclick=()=>this.closeSettings()}
    openSettings(){this.settingsResume=["racing","countdown"].includes(this.state)?this.state:null;if(this.settingsResume){this.state="settings";this.stopEngine()}$("settings-panel").hidden=false}
    closeSettings(){$("settings-panel").hidden=true;if(this.settingsResume){this.state=this.settingsResume;if(this.state==="racing")this.startEngine()}this.settingsResume=null}
    async toggleFullscreen(){const target=document.querySelector(".cabinet");if(!document.fullscreenElement){try{await target.requestFullscreen?.();await screen.orientation?.lock?.("landscape")}catch{}}else{try{screen.orientation?.unlock?.();await document.exitFullscreen?.()}catch{}}}
    togglePause(){if(this.state==="racing"){this.state="paused";this.message.setText("PAUSED");this.stopEngine();this.music.pause();this.updatePauseControl(true)}else if(this.state==="paused"){this.state="racing";this.message.setText("");this.startEngine();this.playMusic();this.updatePauseControl(false)}}
    updatePauseControl(paused){const button=$("pause"),icon=$("pause-icon");button.setAttribute("aria-label",paused?"Resume":"Pause");button.title=paused?"Resume":"Pause";icon.textContent=paused?"▶":"Ⅱ"}
    selectTrack(index){this.trackIndex=clamp(index,0,this.unlocked);if(!this.testMode)localStorage.setItem(`${SAVE}_track`,this.trackIndex);this.track=TRACKS[this.trackIndex];this.setMusicTrack();this.points=this.track.trace?this.sampleSvgTrack(this.track.trace):this.sampleTrack(this.track.controls);if(this.track.startOffset){const offset=Math.round(this.points.length*this.track.startOffset);this.points=[...this.points.slice(offset),...this.points.slice(0,offset)]}this.computeTrackData();this.drawTrack();this.trackText.setText(this.track.name.toUpperCase());this.updateUpgradeLabels()}
    setMusicTrack(){const src=`assets/${this.track.music}?v=${ASSET_REV}`;if(this.musicTrack===src)return;this.musicTrack=src;this.music.pause();this.music.src=src;this.music.load();this.applyMusicMix()}
    applyMusicMix(){if(this.musicGain&&this.audio){const target=this.musicEnabled?(this.musicVolume/100)*.42*(this.track?.musicTrim||1):0;this.musicGain.gain.setTargetAtTime(target,this.audio.currentTime,.06)}this.music.muted=!this.musicEnabled}
    applyEffectsMix(){if(this.master&&this.audio)this.master.gain.setTargetAtTime(1.6*(this.effectsVolume/100),this.audio.currentTime,.04)}
    playMusic(){if(!this.musicEnabled)return;this.ensureAudio();this.applyMusicMix();this.music.play().catch(()=>{})}
    playResultMusic(won){this.music.pause();this.stopResultMusic();if(!this.musicEnabled)return;this.ensureAudio();this.resultMusic.loop=false;this.resultMusic.src=`assets/${won?"win":"lose"}.mp3?v=${ASSET_REV}`;this.resultMusic.currentTime=0;this.resultMusic.play().catch(()=>{})}
    playLobbyMusic(){this.music.pause();this.stopResultMusic();if(!this.musicEnabled)return;this.ensureAudio();this.resultMusic.loop=true;this.resultMusic.src=`assets/lobby.mp3?v=${ASSET_REV}`;this.resultMusic.currentTime=0;this.resultMusic.play().catch(()=>{})}
    stopResultMusic(){if(!this.resultMusic)return;this.resultMusic.pause();this.resultMusic.currentTime=0;this.resultMusic.loop=false}
    sampleSvgTrack(key){const doc=new DOMParser().parseFromString(this.cache.text.get(key),"image/svg+xml"),read=id=>{const d=doc.querySelector(`#${id}`)?.getAttribute("d")||"",values=(d.match(/-?\d+(?:\.\d+)?/g)||[]).map(Number);return Array.from({length:Math.floor(values.length/2)},(_,i)=>({x:values[i*2],y:values[i*2+1]+80}))},center=read("centerline"),left=read("left-edge"),right=read("right-edge"),leftRoad=read("left-road"),rightRoad=read("right-road");if(!left.length||!right.length)return center;return center.map((p,i)=>{const l=left[i%left.length],r=right[i%right.length],lr=leftRoad.length?leftRoad[i%leftRoad.length]:l,rr=rightRoad.length?rightRoad[i%rightRoad.length]:r;return{...p,left:l,right:r,leftRoad:lr,rightRoad:rr,leftWidth:Phaser.Math.Distance.Between(p.x,p.y,l.x,l.y),rightWidth:Phaser.Math.Distance.Between(p.x,p.y,r.x,r.y),leftRoadWidth:Phaser.Math.Distance.Between(p.x,p.y,lr.x,lr.y),rightRoadWidth:Phaser.Math.Distance.Between(p.x,p.y,rr.x,rr.y)}})}
    sampleTrack(controls){const pts=controls.map(([x,y])=>({x:60+x*(W-120),y:80+y*(H-120)})),out=[],count=240;for(let i=0;i<count;i++){const t=i/count*pts.length,n=Math.floor(t),u=t-n,p0=pts[(n-1+pts.length)%pts.length],p1=pts[n],p2=pts[(n+1)%pts.length],p3=pts[(n+2)%pts.length],u2=u*u,u3=u2*u,axis=k=>.5*((2*p1[k])+(-p0[k]+p2[k])*u+(2*p0[k]-5*p1[k]+4*p2[k]-p3[k])*u2+(-p0[k]+3*p1[k]-3*p2[k]+p3[k])*u3);out.push({x:axis("x"),y:axis("y")})}return out}
    computeTrackData(){this.points.forEach((p,i)=>{const prev=this.points[(i-1+this.points.length)%this.points.length],next=this.points[(i+1)%this.points.length];p.angle=Math.atan2(next.y-prev.y,next.x-prev.x);p.nx=-Math.sin(p.angle);p.ny=Math.cos(p.angle);const a=this.points[(i+8)%this.points.length].angle;p.curve=Math.abs(wrapAngle(a-p.angle))});this.checkpoints=Array.from({length:14},(_,i)=>Math.floor(i*this.points.length/14));}
    drawTrack(){
      const t=this.track,g=this.world,d=this.decor,production=Boolean(t.art);g.clear();d.clear();if(!production){g.fillStyle(t.ground).fillRect(0,0,W,H);for(let i=0;i<210;i++){const x=(i*83+this.trackIndex*31)%W,y=72+(i*47)%648,r=1+(i%3);g.fillStyle(i%4?t.ground2:0xd7e39a,i%4?.2:.09).fillCircle(x,y,r)}this.drawEnvironment(g)}
      if(!production){this.drawRibbon(g,this.points,ROAD_WIDTH+22,0x071016,.72);this.drawRibbon(g,this.points,ROAD_WIDTH+14,t.edge);this.drawRibbon(g,this.points,ROAD_WIDTH,t.road);this.drawRibbon(g,this.points,ROAD_WIDTH-12,0xffffff,.025);this.drawCurbs(g,0,this.points.length);for(let i=0;i<this.points.length;i+=10){const p=this.points[i],q=this.points[(i+4)%this.points.length];g.lineStyle(1,0xe8eef0,.26).lineBetween(p.x,p.y,q.x,q.y)}const s=this.points[0];for(let lane=-3;lane<=3;lane++)g.lineStyle(4,lane%2?0xffffff:0x161b20).lineBetween(s.x+s.nx*(lane*6)-Math.cos(s.angle)*8,s.y+s.ny*(lane*6)-Math.sin(s.angle)*8,s.x+s.nx*((lane+1)*6)-Math.cos(s.angle)*8,s.y+s.ny*((lane+1)*6)-Math.sin(s.angle)*8)}
      if(production&&this.debugTrace&&!t.surface){for(const [field,color] of [[null,0x00ffff],["leftRoad",0x65ff75],["rightRoad",0x65ff75],["left",0xff4fa3],["right",0xffd45b]]){g.lineStyle(field?2:3,color,.9);for(let i=0;i<this.points.length;i++){const p=field?this.points[i][field]:this.points[i],q=field?this.points[(i+1)%this.points.length][field]:this.points[(i+1)%this.points.length];if(p&&q)g.lineBetween(p.x,p.y,q.x,q.y)}}}
      this.drawRasterScenery();this.drawStartLine(d);this.drawGuideCones();
      if(t.bridge&&!production)this.drawBridge(d,t.bridge);
      if(production)this.mapArt.setTexture(t.art);if(t.bridge?.art)this.bridgeArt.setTexture(t.bridge.art);this.mapArt.setVisible(production);this.bridgeArt.setVisible(Boolean(t.bridge?.art));if(t.surface){[t.surface.runoff,t.surface.road,t.surface.guide].forEach((key,i)=>this.surfaceDebug[i].setTexture(key))}this.surfaceDebug.forEach(image=>image.setVisible(Boolean(production&&this.debugTrace&&t.surface)));if(!this.trackOverlay)this.trackOverlay=this.add.image(0,80,"midnight-overlay").setOrigin(0).setDepth(16).setVisible(false);if(t.overlay)this.trackOverlay.setTexture(t.overlay);this.trackOverlay.setVisible(Boolean(production&&t.overlay));this.world.setVisible(true);this.decor.setVisible(true);
    }
    drawRibbon(g,points,width,color,alpha=1,start=0,end=points.length,closed=true,yOffset=0){const half=width/2,last=closed?end:end-1;g.fillStyle(color,alpha);for(let i=start;i<last;i++){const p=points[i%points.length],q=points[(i+1)%points.length],ax=p.x+p.nx*half,ay=p.y+p.ny*half+yOffset,bx=p.x-p.nx*half,by=p.y-p.ny*half+yOffset,cx=q.x+q.nx*half,cy=q.y+q.ny*half+yOffset,dx=q.x-q.nx*half,dy=q.y-q.ny*half+yOffset;g.fillTriangle(ax,ay,bx,by,cx,cy);g.fillTriangle(bx,by,dx,dy,cx,cy)}}
    drawCurbs(g,start,end){for(let i=start;i<end;i+=3){const p=this.points[i%this.points.length],q=this.points[(i+2)%this.points.length],color=(Math.floor(i/3)%2)?0xf4f5eb:this.track.accent,half=ROAD_WIDTH/2+1;g.lineStyle(this.trackIndex===1?6:4,color,.96).lineBetween(p.x+p.nx*half,p.y+p.ny*half,q.x+q.nx*half,q.y+q.ny*half);g.lineBetween(p.x-p.nx*half,p.y-p.ny*half,q.x-q.nx*half,q.y-q.ny*half)}}
    drawBridge(g,bridge){const n=this.points.length,center=Math.round(bridge.center*n),a=this.points[(center-bridge.length+n)%n],b=this.points[(center+bridge.length+1)%n],angle=Math.atan2(b.y-a.y,b.x-a.x),nx=-Math.sin(angle),ny=Math.cos(angle),deck=(width,color,alpha=1,yOffset=0)=>{const half=width/2,ax=a.x+nx*half,ay=a.y+ny*half+yOffset,bx=a.x-nx*half,by=a.y-ny*half+yOffset,cx=b.x+nx*half,cy=b.y+ny*half+yOffset,dx=b.x-nx*half,dy=b.y-ny*half+yOffset;g.fillStyle(color,alpha).fillTriangle(ax,ay,bx,by,cx,cy).fillTriangle(bx,by,dx,dy,cx,cy)};deck(ROAD_WIDTH+30,0x071016,.48,9);deck(ROAD_WIDTH+18,0xd4d9da);deck(ROAD_WIDTH+10,this.track.edge);deck(ROAD_WIDTH,this.track.road);const length=Math.hypot(b.x-a.x,b.y-a.y),steps=Math.max(5,Math.floor(length/25));for(let i=0;i<steps;i++){const u=i/steps,v=Math.min(1,(i+.66)/steps),color=i%2?0xf4f5eb:this.track.accent,x1=Phaser.Math.Linear(a.x,b.x,u),y1=Phaser.Math.Linear(a.y,b.y,u),x2=Phaser.Math.Linear(a.x,b.x,v),y2=Phaser.Math.Linear(a.y,b.y,v),half=ROAD_WIDTH/2+1;g.lineStyle(5,color,1).lineBetween(x1+nx*half,y1+ny*half,x2+nx*half,y2+ny*half).lineBetween(x1-nx*half,y1-ny*half,x2-nx*half,y2-ny*half)}const rail=ROAD_WIDTH/2+13;g.lineStyle(4,0xe8e3b8,1).lineBetween(a.x+nx*rail,a.y+ny*rail,b.x+nx*rail,b.y+ny*rail).lineBetween(a.x-nx*rail,a.y-ny*rail,b.x-nx*rail,b.y-ny*rail);for(let i=0;i<=steps;i++){const u=i/steps,x=Phaser.Math.Linear(a.x,b.x,u),y=Phaser.Math.Linear(a.y,b.y,u),outer=rail+8,sign=i%2?1:-1;g.lineStyle(3,0xe8e3b8,.95).lineBetween(x+nx*rail,y+ny*rail,x+nx*outer+Math.cos(angle)*sign*10,y+ny*outer+Math.sin(angle)*sign*10).lineBetween(x-nx*rail,y-ny*rail,x-nx*outer+Math.cos(angle)*sign*10,y-ny*outer+Math.sin(angle)*sign*10);g.fillStyle(0xe8e3b8).fillCircle(x+nx*rail,y+ny*rail,2.5).fillCircle(x-nx*rail,y-ny*rail,2.5)}g.lineStyle(3,0xf1f3f0,.9).lineBetween(a.x+nx*32,a.y+ny*32,a.x-nx*32,a.y-ny*32).lineBetween(b.x+nx*32,b.y+ny*32,b.x-nx*32,b.y-ny*32)}
    drawEnvironment(g){const t=this.track;if(this.trackIndex===0){g.fillStyle(0x0b4053,.95).fillEllipse(492,386,350,158);g.lineStyle(3,0x58bfd0,.22).strokeEllipse(492,386,326,136);for(let i=0;i<22;i++)g.fillStyle(i%3?0x2d7d83:0x79c7bd,.32).fillCircle(338+(i*43)%322,332+(i*31)%111,2+(i%3));g.fillStyle(0x293538).fillRoundedRect(354,278,276,32,6);for(let x=365;x<620;x+=24)g.fillStyle(0xffd05b,.7).fillRect(x,287,9,3);this.drawTrees(g,[[84,104],[116,122],[850,118],[902,160],[86,587],[908,570],[702,404]])}else if(this.trackIndex===1){for(let i=0;i<8;i++){const x=104+(i*109)%790,y=116+(i*83)%520;g.fillStyle(0x2b2420,.95).fillRoundedRect(x,y,42,25,4);g.fillStyle(0xff8b54,.55).fillRect(x+6,y+7,30,4);g.fillStyle(0x12191d).fillRect(x+9,y+15,8,10).fillRect(x+25,y+14,10,11)}for(let i=0;i<7;i++){const x=130+i*120,y=530-(i%3)*120;g.fillStyle(0x20292c,.9).fillRect(x,y,8,34);g.fillStyle(0xffc25a,.4).fillCircle(x+4,y,12)}}else{this.drawTrees(g,Array.from({length:24},(_,i)=>[38+(i*101)%900,92+(i*61)%560]));g.fillStyle(0xbfe4ea,.2).fillEllipse(480,350,310,88);for(let i=0;i<5;i++){const x=330+i*70;g.fillStyle(i%2?0xd9e1d8:0xb9c8bd,.48).fillTriangle(x,410,x+40,326-(i%2)*18,x+82,410)}}}
    drawTrees(g,positions){for(const [x,y] of positions){g.fillStyle(0x18271f,.65).fillEllipse(x+3,y+9,24,11);g.fillStyle(0x5a3c27).fillRect(x-2,y-2,4,15);g.fillStyle(0x163f2b).fillCircle(x,y-8,12);g.fillStyle(0x2e7045).fillCircle(x-6,y-11,7);g.fillStyle(0x4a8b55,.8).fillCircle(x+6,y-13,6)}}
    drawRasterScenery(){this.scenery?.forEach(item=>item.destroy());this.scenery=[];if(this.track.art)return;const layouts=[{trees:[[80,112,.17],[111,660,.14],[884,123,.17],[903,660,.14]],stands:[[480,108,.18,0],[478,660,.18,Math.PI]],barriers:[[746,406,.18,.25]]},null,{trees:[[60,115,.16],[150,200,.13],[890,130,.16],[74,650,.16],[885,650,.16],[480,390,.13]],stands:[[470,106,.17,0],[470,662,.17,Math.PI]],barriers:[[712,456,.17,.3]]}],layout=layouts[this.trackIndex],add=(key,[x,y,scale,rotation=0])=>this.scenery.push(this.add.image(x,y,key).setScale(scale).setRotation(rotation).setDepth(1));layout.trees?.forEach(v=>add(v[2]>.145?"raster-tree":"raster-tree-small",v));layout.stands?.forEach(v=>add("raster-stand",v));layout.barriers?.forEach(v=>add("raster-barrier",v));layout.lights?.forEach(v=>add("raster-lights",v))}
    drawGuideCones(){this.guideCones?.forEach(item=>item.destroy());this.guideCones=[];const scale=this.track.scale||1;for(const [index,lane] of this.track.cones||[]){const p=this.points[index%this.points.length],offset=lane*scale;this.guideCones.push(this.add.image(p.x+p.nx*offset,p.y+p.ny*offset,"prop-cone").setScale(scale).setRotation(p.angle+Math.PI/2).setDepth(6))}}
    drawStartLine(g){const p=this.points[0],scale=this.track.scale||1,half=Math.max(11,Math.min(p.leftWidth||ROAD_WIDTH/2*scale,p.rightWidth||ROAD_WIDTH/2*scale)-2*scale),cells=8,rows=3,cw=half*2/cells,ch=4*scale,tx=Math.cos(p.angle),ty=Math.sin(p.angle);for(let i=0;i<cells;i++)for(let row=0;row<rows;row++){const a=-half+i*cw,b=a+cw,c=(row-(rows-1)/2)*ch,d=c+ch,color=(i+row)&1?0xf5f7f8:0x111820,x1=p.x+p.nx*a+tx*c,y1=p.y+p.ny*a+ty*c,x2=p.x+p.nx*b+tx*c,y2=p.y+p.ny*b+ty*c,x3=p.x+p.nx*b+tx*d,y3=p.y+p.ny*b+ty*d,x4=p.x+p.nx*a+tx*d,y4=p.y+p.ny*a+ty*d;g.fillStyle(color,.92).fillTriangle(x1,y1,x2,y2,x3,y3).fillTriangle(x1,y1,x3,y3,x4,y4)}}
    nearest(x,y,hint=null){let best=null,bestD=Infinity;const n=this.points.length,indices=hint===null?Array.from({length:n},(_,i)=>i):Array.from({length:61},(_,k)=>(Math.round(hint)-30+k+n)%n);for(const i of indices){const p=this.points[i],q=this.points[(i+1)%n],dx=q.x-p.x,dy=q.y-p.y,l2=dx*dx+dy*dy,u=clamp(((x-p.x)*dx+(y-p.y)*dy)/l2,0,1),px=p.x+dx*u,py=p.y+dy*u,dd=(x-px)**2+(y-py)**2;if(dd<bestD){bestD=dd;best={index:i,u,x:px,y:py,dist:Math.sqrt(dd),angle:Math.atan2(dy,dx)}}}return best}
    gridPose(distance){const n=this.points.length;let covered=0;for(let i=n-1;i>=0;i--){const p=this.points[i],q=this.points[(i+1)%n],length=Phaser.Math.Distance.Between(p.x,p.y,q.x,q.y);if(covered+length>=distance){const u=(distance-covered)/Math.max(length,.001),x=Phaser.Math.Linear(q.x,p.x,u),y=Phaser.Math.Linear(q.y,p.y,u),angle=Math.atan2(q.y-p.y,q.x-p.x);return{x,y,angle,nx:-Math.sin(angle),ny:Math.cos(angle),progress:i+1-u-n}}covered+=length}const p=this.points[n-1];return{...p,progress:-1}}
    createCar(i,distanceBehind,laneOffset){const p=this.gridPose(distanceBehind),scale=this.track.scale||1,difficulty={easy:.9,normal:1.08,hard:1.24}[this.difficulty]||1.08,skill=this.testWin?(i?-.6:1.8):difficulty+this.trackIndex*.06+this.tour*.08+(i-2)*.06,car={i,x:p.x+p.nx*laneOffset,y:p.y+p.ny*laneOffset,angle:p.angle,vx:0,vy:0,speed:0,lap:0,nextCheckpoint:1,checkpoint:0,progress:p.progress,finished:false,finishTime:0,spin:0,skidTimer:0,oilCooldown:0,collisionCooldown:0,impactCooldown:0,integrity:100,crashed:false,crashTimer:0,stuckTime:0,ai:i>0||this.autoTest,lane:laneOffset,scale,radius:CAR_RADIUS*scale,skill,seed:i*2.17};car.sprite=this.add.image(car.x,car.y,"f1-car").setScale(.38*scale).setTint(CAR_COLORS[i]).setDepth(10);car.shadow=this.add.ellipse(car.x+2*scale,car.y+3*scale,(CAR_W-2)*scale,(CAR_H-3)*scale,0x000000,.3).setDepth(9);this.cars.push(car);return car}
    resetRace(){this.cars.forEach(c=>{c.sprite.destroy();c.shadow.destroy()});this.cars=[];this.pickups?.forEach(o=>o.sprite.destroy());this.hazards?.forEach(o=>o.sprite.destroy());this.effectEvents=[];this.raceTime=0;this.trackWrenches=0;this.finishOrder=[];if(!this.textures.exists("prop-tornado"))this.createTornadoTexture();const scale=this.track.scale||1,start=this.points[0],road=Math.min(start.leftRoadWidth||ROAD_WIDTH/2,start.rightRoadWidth||ROAD_WIDTH/2),lane=Math.min(10*scale,road*.3),grid=[{d:18*scale,l:-lane},{d:27*scale,l:lane},{d:46*scale,l:-lane},{d:55*scale,l:lane}];grid.forEach((slot,i)=>this.createCar(i,slot.d,slot.l));this.player=this.cars[0];this.pickups=[this.makeTrackObject("prop-wrench","wrench"),this.makeTrackObject("prop-wrench","wrench")];const difficultyBonus=this.difficulty==="hard"?1:0,staticCount=2+Math.floor(this.trackIndex/2)+difficultyBonus,tornadoCount=this.trackIndex<2?0:1+(this.trackIndex>=5?1:0);this.hazards=[...Array.from({length:staticCount},(_,i)=>this.makeTrackObject(i%2?"prop-water":"prop-oil",i%2?"water":"oil")),...Array.from({length:tornadoCount},()=>this.makeTrackObject("prop-tornado","tornado"))];const spread=(count,start,end)=>Array.from({length:count},(_,i)=>start+(end-start)*(i+.35+Math.random()*.3)/count);this.trackEvents=[...spread(2,.12,.78).map((at,i)=>({at,item:this.pickups[i]})),...spread(this.hazards.length,.08,.92).map((at,i)=>({at,item:this.hazards[i]}))].sort((a,b)=>a.at-b.at);this.updateHud()}
    createTornadoTexture(){const g=this.make.graphics({add:false});g.fillStyle(0x081119,.2).fillEllipse(14,27,22,7);g.lineStyle(3,0xd9f7ff,.78).strokeEllipse(14,20,22,7);g.lineStyle(3,0x75ddec,.72).strokeEllipse(14,14,17,6);g.lineStyle(3,0xffffff,.82).strokeEllipse(14,8,11,5);g.lineStyle(2,0x8ddff0,.7).lineBetween(10,7,16,25).lineBetween(18,7,12,24);g.generateTexture("prop-tornado",28,31);g.destroy()}
    makeTrackObject(texture,type=texture){const scale=this.track.scale||1,displayScale=type==="tornado"?.24*scale:scale,sprite=this.add.image(-100,-100,type==="tornado"?"prop-tornado-frames":texture,type==="tornado"?0:undefined).setScale(displayScale).setDepth(9).setVisible(false);return{type,scale,x:-100,y:-100,sprite,active:false,expires:0,particleClock:0,contacts:new Set()}}
    spawnTrackObject(item){const n=this.points.length,margin=8*item.scale;let index=0,p,lane=0,x=0,y=0;for(let tries=0;tries<60;tries++){index=Math.floor(Math.random()*n);p=this.points[index];const startDistance=Math.min(index,n-index),bridgeDistance=this.track.bridge?Math.min(Math.abs(index-this.track.bridge.center*n),Math.abs(index-((this.track.bridge.center+.5)%1)*n)):n,left=Math.max(margin,(p.leftRoadWidth||ROAD_WIDTH/2)-margin),right=Math.max(margin,(p.rightRoadWidth||ROAD_WIDTH/2)-margin);lane=Phaser.Math.FloatBetween(-right,left);x=p.x+p.nx*lane;y=p.y+p.ny*lane;const clearOfCars=this.cars.every(car=>Phaser.Math.Distance.Between(x,y,car.x,car.y)>55*item.scale),clearOfItems=[...this.pickups,...this.hazards].every(other=>other===item||!other.active||Phaser.Math.Distance.Between(x,y,other.x,other.y)>28*item.scale);if(startDistance>18&&bridgeDistance>(this.track.bridge?.length||0)+10&&clearOfCars&&clearOfItems)break}item.x=x;item.y=y;item.index=index;item.progress=index;item.lane=lane;item.seed=Math.random()*TAU;item.active=true;item.contacts.clear();item.expires=item.type==="wrench"?this.raceTime+18:this.raceTime+14;item.sprite.setPosition(x,y).setRotation(item.type==="tornado"?0:p.angle).setVisible(true);this.effectEvents.push({kind:"spawn",x,y,life:.3,max:.3,color:item.type==="wrench"?0xffd05b:0x66eaff,size:10*item.scale})}
    updateTrackEvents(){const progress=(this.player.lap+this.player.progress/this.points.length)/this.raceLaps;for(const event of this.trackEvents){if(!event.fired&&progress>=event.at){event.fired=true;this.spawnTrackObject(event.item)}}for(const item of [...this.pickups,...this.hazards])if(item.active&&this.raceTime>item.expires){item.active=false;item.sprite.setVisible(false)}this.updateMovingHazards()}
    updateMovingHazards(){for(const item of this.hazards)if(item.active&&item.type==="tornado"){const n=this.points.length;item.progress=(item.progress+STEP*5)%n;const index=Math.floor(item.progress),u=item.progress-index,p=this.points[index],q=this.points[(index+1)%n],nx=Phaser.Math.Linear(p.nx,q.nx,u),ny=Phaser.Math.Linear(p.ny,q.ny,u),normalLength=Math.hypot(nx,ny)||1,width=Phaser.Math.Linear(Math.min(p.leftRoadWidth||ROAD_WIDTH/2,p.rightRoadWidth||ROAD_WIDTH/2),Math.min(q.leftRoadWidth||ROAD_WIDTH/2,q.rightRoadWidth||ROAD_WIDTH/2),u),lane=Math.sin(this.raceTime*1.15+item.seed)*Math.max(3,width*.52),cx=Phaser.Math.Linear(p.x,q.x,u),cy=Phaser.Math.Linear(p.y,q.y,u);item.x=cx+nx/normalLength*lane;item.y=cy+ny/normalLength*lane;const pulse=1+Math.sin(this.raceTime*4+item.seed)*.025,frame=Math.floor((this.raceTime+item.seed)*12)%8;item.sprite.setFrame(frame).setPosition(item.x,item.y).setRotation(0).setScale(.24*item.scale*pulse).setAlpha(.96);item.particleClock-=STEP;if(item.particleClock<=0){item.particleClock=.075;for(let i=0;i<2;i++){const angle=Math.random()*TAU,speed=5+Math.random()*12;this.effectEvents.push({kind:"dust",x:item.x+Math.cos(angle)*8*item.scale,y:item.y+12*item.scale+Math.sin(angle)*3*item.scale,vx:Math.cos(angle)*speed,vy:-3-Math.random()*7,life:.65,max:.65,color:i?0xc9aa78:0x9fefff,size:(2+Math.random()*2)*item.scale})}}item.contacts.clear()}}
    placeObject(item,x,y){item.x=x;item.y=y;item.sprite.setPosition(x,y)}
    startRace(){if(!this.testMode)localStorage.setItem(`${SAVE}_active`,"1");this.stopResultMusic();this.ensureAudio();this.playMusic();this.resetRace();$("overlay").hidden=true;$("upgrade-panel").hidden=true;$("result-panel").hidden=true;$("difficulty-control").hidden=true;this.state="countdown";this.countdown=3.25;this.message.setText("3");this.tone(420,.07);const testPositions={win:1,second:2,third:3,last:4};if(testPositions[this.testResult])this.time.delayedCall(4400,()=>{if(this.state==="racing"){if(this.testResult==="win"){this.wrenchBank=Math.max(this.wrenchBank,2);if(!this.testMode)localStorage.setItem(`${SAVE}_wrenches`,String(this.wrenchBank))}this.endRace(testPositions[this.testResult])}})}
    update(_time,deltaMs){const dt=Math.min(deltaMs/1000,.05);if(this.state==="countdown"){this.countdown-=dt;const n=Math.ceil(this.countdown);this.message.setText(n>0?String(n):"GO!");if(this.lastCount!==n&&n>0){this.tone(420,.05);this.lastCount=n}if(this.countdown<=-.35){this.message.setText("");this.state="racing";this.startEngine()}this.syncSprites();return}if(this.state!=="racing")return;this.accumulator=Math.min(this.accumulator+dt,.12);while(this.accumulator>=STEP){this.stepRace(STEP);this.accumulator-=STEP}this.syncSprites();this.drawEffects();this.updateHud()}
    playerInput(){return{steer:Number(this.keys.RIGHT.isDown||this.keys.D.isDown||this.touch.right)-Number(this.keys.LEFT.isDown||this.keys.A.isDown||this.touch.left),throttle:Number(this.keys.UP.isDown||this.keys.W.isDown||this.touch.gas),brake:Number(this.keys.DOWN.isDown||this.keys.S.isDown||this.touch.brake)}}
    performance(upgrade){return{top:150+upgrade.speed*7,accel:95+upgrade.power*7,grip:4.5+upgrade.grip*.42}}
    aiInput(car){const n=this.points.length,near=this.nearest(car.x,car.y,car.progress),speed=Math.hypot(car.vx,car.vy),look=Math.floor(8+speed*.065),target=this.points[(near.index+look)%n],scale=car.scale||1,lane=Math.sin(this.raceTime*.45+car.seed)*9*scale+car.lane*.25,tx=target.x+target.nx*lane,ty=target.y+target.ny*lane,desired=Math.atan2(ty-car.y,tx-car.x),diff=wrapAngle(desired-car.angle);let steer=clamp(diff*2.75,-1,1);for(const other of this.cars){if(other===car||other.finished)continue;const dx=other.x-car.x,dy=other.y-car.y,forward=dx*Math.cos(car.angle)+dy*Math.sin(car.angle),side=-dx*Math.sin(car.angle)+dy*Math.cos(car.angle);if(forward>0&&forward<55*scale&&Math.abs(side)<25*scale)steer+=side>0?-.55:.55}const curve=this.points[(near.index+16)%n].curve,player=this.performance(this.upgrades),benchmark=car.i===0,pace=benchmark?1:{easy:.91,normal:1.03,hard:1.09}[this.difficulty]||1.03,progression=benchmark?0:this.trackIndex*.022+this.tour*.025,rival=benchmark?0:(car.i-2)*.014,curveCost=benchmark?28:{easy:40,normal:27,hard:21}[this.difficulty],max=clamp(player.top*(pace+progression+rival)-curve*curveCost,98,player.top*1.18),throttle=speed<max-1?1:.52,brake=speed>max+9?.34:0;return{steer:clamp(steer,-1,1),throttle,brake}}
    stepRace(dt){this.raceTime+=dt;this.updateTrackEvents();for(const car of this.cars){if(car.finished)continue;if(car.crashed){car.crashTimer-=dt;if(car.crashTimer<=0)this.rescueCar(car,true);continue}const input=car.ai?this.aiInput(car):this.playerInput();this.stepCar(car,input,dt);this.updateProgress(car);this.checkObjects(car);car.oilCooldown=Math.max(0,car.oilCooldown-dt);car.collisionCooldown=Math.max(0,car.collisionCooldown-dt);car.impactCooldown=Math.max(0,car.impactCooldown-dt);car.stuckTime=car.speed<4?car.stuckTime+dt:Math.max(0,car.stuckTime-dt*3);if(car.stuckTime>(car.ai?4.5:7.5))this.rescueCar(car,false)}this.resolveCarCollisions();this.checkFinish()}
    stepCar(car,input,dt){
      const oldX=car.x,oldY=car.y,challenge={easy:-.6,normal:.6,hard:1.2}[this.difficulty]||.6,progression=this.trackIndex*.45+this.tour*.25+(car.i-2)*.14,upgrade=car.i>0?{grip:clamp(this.upgrades.grip+challenge+progression,0,5),power:clamp(this.upgrades.power+challenge+progression,0,5),speed:clamp(this.upgrades.speed+challenge+progression,0,5)}:this.upgrades,stats=this.performance(upgrade),fx=Math.cos(car.angle),fy=Math.sin(car.angle),rx=-fy,ry=fx;let forward=car.vx*fx+car.vy*fy,lateral=car.vx*rx+car.vy*ry;const{top,accel,grip}=stats;if(car.spin>0){car.spin-=dt;car.angle+=5.8*dt;lateral*=Math.exp(-1.1*dt)}else{const speedFactor=clamp(Math.abs(forward)/42,.18,1);car.angle+=input.steer*2.55*speedFactor*Math.sign(forward||1)*dt;forward+=input.throttle*accel*dt;if(input.brake){if(forward>8)forward-=175*input.brake*dt;else forward-=55*input.brake*dt}lateral*=Math.exp(-grip*dt)}forward*=Math.exp(-(0.32+.0009*Math.abs(forward))*dt);forward=clamp(forward,-48,top);car.vx=Math.cos(car.angle)*forward-Math.sin(car.angle)*lateral;car.vy=Math.sin(car.angle)*forward+Math.cos(car.angle)*lateral;car.x+=car.vx*dt;car.y+=car.vy*dt;car.speed=Math.hypot(car.vx,car.vy);if(car.spin>0&&car.speed>16){car.skidTimer-=dt;if(car.skidTimer<=0){car.skidTimer=.055;const side=5*car.scale,nx=-Math.sin(car.angle),ny=Math.cos(car.angle);for(const offset of[-side,side])this.effectEvents.push({kind:"skid",x1:oldX+nx*offset,y1:oldY+ny*offset,x2:car.x+nx*offset,y2:car.y+ny*offset,life:2.1,max:2.1,color:0x111820,size:1.35*car.scale})}}else car.skidTimer=0;
      if(this.track.surface){if(this.bridgeLayer(car)){this.constrainBridgeBranch(car,oldX,oldY,dt);return}const sx=Math.round(clamp(car.x,0,959)),sy=Math.round(clamp(car.y-80,0,639)),road=this.textures.getPixelAlpha(sx,sy,this.track.surface.road)>24,runoff=this.textures.getPixelAlpha(sx,sy,this.track.surface.runoff)>24;if(!road&&runoff){const slow=Math.exp(-1.45*dt);car.vx*=slow;car.vy*=slow}else if(!runoff){const impact=car.speed;car.x=oldX;car.y=oldY;car.vx*=.35;car.vy*=.35;if(impact>35){this.spark(car.x,car.y);if(impact>85)this.damageCar(car,20+(impact-85)*.7);if(!car.ai)this.playCollision(impact)}}return}
      const near=this.nearest(car.x,car.y,car.progress),p=this.points[near.index],q=this.points[(near.index+1)%this.points.length],signed=(car.x-near.x)*p.nx+(car.y-near.y)*p.ny,leftSide=signed>=0,widthA=leftSide?(p.leftWidth||ROAD_WIDTH/2):(p.rightWidth||ROAD_WIDTH/2),widthB=leftSide?(q.leftWidth||ROAD_WIDTH/2):(q.rightWidth||ROAD_WIDTH/2),roadA=leftSide?(p.leftRoadWidth||widthA):(p.rightRoadWidth||widthA),roadB=leftSide?(q.leftRoadWidth||widthB):(q.rightRoadWidth||widthB),roadLimit=Math.max(14,Phaser.Math.Linear(roadA,roadB,near.u)-car.radius*.25),limit=Math.max(18,Phaser.Math.Linear(widthA,widthB,near.u)-car.radius*.35);if(near.dist>roadLimit){const shoulder=near.dist-roadLimit,slow=Math.exp(-(1.05+shoulder*.035)*dt);car.vx*=slow;car.vy*=slow}if(near.dist>limit){const off=near.dist-limit,drag=Math.exp(-(2.2+off*.05)*dt);car.vx*=drag;car.vy*=drag;if(near.dist>limit+6){const impact=car.speed,nx=(car.x-near.x)/(near.dist||1),ny=(car.y-near.y)/(near.dist||1),penetration=near.dist-(limit+2);car.x-=nx*penetration;car.y-=ny*penetration;const vn=car.vx*nx+car.vy*ny;if(vn>0){car.vx-=nx*vn*1.35;car.vy-=ny*vn*1.35;this.spark(car.x,car.y);if(impact>85)this.damageCar(car,20+(impact-85)*.7);if(!car.ai)this.playCollision(impact)}}}}
    constrainBridgeBranch(car,oldX,oldY,dt){const near=this.nearest(car.x,car.y,car.progress),p=this.points[near.index],scale=this.track.scale||1,roadLimit=Math.max(12,27*scale-car.radius*.2),limit=Math.max(18,42*scale-car.radius*.25);if(near.dist>roadLimit){const shoulder=near.dist-roadLimit,slow=Math.exp(-(1.35+shoulder*.05)*dt);car.vx*=slow;car.vy*=slow}if(near.dist<=limit)return;const impact=car.speed,nx=(car.x-near.x)/(near.dist||1),ny=(car.y-near.y)/(near.dist||1);car.x=near.x+nx*(limit-2);car.y=near.y+ny*(limit-2);const vn=car.vx*nx+car.vy*ny;if(vn>0){car.vx-=nx*vn*1.4;car.vy-=ny*vn*1.4}else{car.x=oldX;car.y=oldY}this.spark(car.x,car.y);if(impact>85)this.damageCar(car,18+(impact-85)*.6);if(!car.ai)this.playCollision(impact)}
    updateProgress(car){const near=this.nearest(car.x,car.y,car.progress),n=this.points.length;car.progress=near.index+near.u;const target=this.checkpoints[car.nextCheckpoint],diff=Math.abs(((near.index-target+n/2)%n)-n/2);if(diff<3){car.checkpoint=car.nextCheckpoint;if(car.nextCheckpoint===0){car.lap++;this.tone(car===this.player?700:520,.05);if(car===this.player&&car.lap<this.raceLaps){this.message.setText(`LAP ${car.lap+1}`);this.time.delayedCall(650,()=>{if(this.state==="racing")this.message.setText("")})}}car.nextCheckpoint=(car.nextCheckpoint+1)%this.checkpoints.length}}
    checkObjects(car){if(car===this.player)for(const item of this.pickups){if(item.active&&Phaser.Math.Distance.Between(car.x,car.y,item.x,item.y)<car.radius+4*item.scale){item.active=false;item.sprite.setVisible(false);if(this.wrenchBank<3){this.wrenchBank++;this.trackWrenches++;localStorage.setItem(`${SAVE}_wrenches`,String(this.wrenchBank))}this.effectEvents.push({kind:"pickup",x:item.x,y:item.y,life:.45,max:.45,color:0xffd05b,size:13*item.scale});this.playPickup()}}for(const hazard of this.hazards){if(!hazard.active)continue;const distance=Phaser.Math.Distance.Between(car.x,car.y,hazard.x,hazard.y),touching=distance<car.radius+(hazard.type==="tornado"?10:hazard.type==="oil"?6:7)*hazard.scale;if(!touching){hazard.contacts.delete(car.i);continue}if(!hazard.contacts.has(car.i)&&car.oilCooldown<=0){hazard.contacts.add(car.i);car.oilCooldown=2.5;if(hazard.type==="oil"||hazard.type==="tornado"){car.spin=hazard.type==="tornado"?1.05:.72;car.vx*=hazard.type==="tornado"?.68:.82;car.vy*=hazard.type==="tornado"?.68:.82;if(car===this.player)this.playSpinout(hazard.type==="tornado")}else{car.vx*=.48;car.vy*=.48;this.splashBurst(car);if(car===this.player)this.playSplash()}this.effectEvents.push({kind:"hazard",x:car.x,y:car.y,life:.35,max:.35,color:hazard.type==="oil"?0x9ba8b1:0x66eaff,size:10*car.scale})}}}
    splashBurst(car){const heading=Math.atan2(car.vy,car.vx),speed=Math.max(12,car.speed);for(let i=0;i<14;i++){const angle=heading+Math.PI+Phaser.Math.FloatBetween(-1.1,1.1),velocity=Phaser.Math.FloatBetween(speed*.08,speed*.24);this.effectEvents.push({kind:"splash",x:car.x,y:car.y,vx:Math.cos(angle)*velocity,vy:Math.sin(angle)*velocity-Phaser.Math.FloatBetween(4,11),life:Phaser.Math.FloatBetween(.38,.7),max:.7,color:i%3?0x78dfff:0xe5fbff,size:Phaser.Math.FloatBetween(1.2,3.1)*car.scale})}}
    rescueCar(car,rebuilt=false){const near=this.nearest(car.x,car.y,car.progress),p=this.points[(near.index+7)%this.points.length],speed=52;car.x=p.x+p.nx*car.lane*.25;car.y=p.y+p.ny*car.lane*.25;car.angle=p.angle;car.vx=Math.cos(p.angle)*speed;car.vy=Math.sin(p.angle)*speed;car.spin=0;car.crashed=false;car.crashTimer=0;car.integrity=100;car.oilCooldown=2.5;car.impactCooldown=1;car.stuckTime=0;if(car===this.player){this.statusText.setText(rebuilt?"REPLACEMENT CAR READY":"CAR RETURNED TO TRACK").setAlpha(1);this.tweens.killTweensOf(this.statusText);this.tweens.add({targets:this.statusText,alpha:0,delay:900,duration:450});this.tone(rebuilt?520:330,.09)}}
    damageCar(car,amount,x=car.x,y=car.y){if(car.crashed||car.finished||car.impactCooldown>0)return;car.impactCooldown=.28;car.integrity-=amount;if(car.integrity<=0)this.crashCar(car);else this.collisionBurst(x,y,Math.cos(car.angle),Math.sin(car.angle),clamp(amount/55,.2,1))}
    crashCar(car){car.crashed=true;car.crashTimer=2.35;car.vx=car.vy=0;car.spin=0;this.effectEvents.push({kind:"explosion",x:car.x,y:car.y,life:.65,max:.65,color:0xff8a42,size:24*car.scale});if(car===this.player){this.statusText.setText("CAR DESTROYED · REBUILDING").setAlpha(1);this.playExplosion()}}
    bridgeLayer(car){if(!this.track.bridge)return 0;const n=this.points.length,span=this.track.bridge.length+6,distance=center=>Math.abs(((car.progress-center+n/2)%n)-n/2),over=this.track.bridge.center*n,under=(this.track.bridge.center+.5)%1*n;if(distance(over)<span)return 1;if(distance(under)<span)return-1;return 0}
    resolveCarCollisions(){for(let i=0;i<CARS;i++)for(let j=i+1;j<CARS;j++){const a=this.cars[i],b=this.cars[j];if(a.crashed||b.crashed)continue;const layerA=this.bridgeLayer(a),layerB=this.bridgeLayer(b);if(layerA&&layerB&&layerA!==layerB)continue;const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),limit=(a.radius+b.radius)*.92;if(d>0&&d<limit){const nx=dx/d,ny=dy/d,push=(limit-d)/2+.25*Math.min(a.scale,b.scale);a.x-=nx*push;a.y-=ny*push;b.x+=nx*push;b.y+=ny*push;const rel=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(rel<0){const impulse=-rel*.58;a.vx-=nx*impulse;a.vy-=ny*impulse;b.vx+=nx*impulse;b.vy+=ny*impulse;a.angle-=Math.sign(rel||1)*.018;b.angle+=Math.sign(rel||1)*.018}if(a.collisionCooldown<=0&&b.collisionCooldown<=0){a.collisionCooldown=b.collisionCooldown=.2;const force=Math.abs(rel);this.collisionBurst((a.x+b.x)/2,(a.y+b.y)/2,nx,ny,Math.min(1,force/70));if(force>42){this.damageCar(a,8+(force-42)*.32);this.damageCar(b,8+(force-42)*.32)}if(a===this.player||b===this.player){this.playCollision(force);this.cameras.main.shake(45,.002)}}}}}
    rankCars(){return [...this.cars].sort((a,b)=>{if(a.finished&&b.finished)return this.finishOrder.indexOf(a)-this.finishOrder.indexOf(b);if(a.finished!==b.finished)return a.finished?-1:1;const n=this.points.length,normalized=car=>car.lap*n+(car.lap===0&&car.progress>n*.75?car.progress-n:car.progress),pa=normalized(a),pb=normalized(b);return pb-pa})}
    checkFinish(){for(const car of this.cars){if(!car.finished&&car.lap>=this.raceLaps){car.finished=true;car.finishTime=this.raceTime;car.vx=car.vy=0;this.finishOrder.push(car);if(car===this.player){const position=this.finishOrder.length;this.time.delayedCall(500,()=>this.endRace(position));break}}}if(!this.player.finished&&this.finishOrder.filter(car=>car!==this.player).length===3)this.endRace(4)}
    endRace(position){if(this.state!=="racing")return;this.state="results";this.stopEngine();const won=position===1,bestKey=`${SAVE}_best_${this.trackIndex}`,old=Number(localStorage.getItem(bestKey))||Infinity;this.playResultMusic(won);if(!this.testMode&&won&&this.raceTime<old)localStorage.setItem(bestKey,String(this.raceTime));if(!this.testMode&&won&&this.trackIndex<TRACKS.length-1){this.unlocked=Math.max(this.unlocked,this.trackIndex+1);localStorage.setItem(`${SAVE}_unlocked`,String(this.unlocked))}this.resultPosition=position;this.championshipComplete=won&&this.trackIndex===TRACKS.length-1;this.advanceOnStart=won&&(this.trackIndex<this.unlocked||this.championshipComplete);this.pendingUpgrade=won&&this.wrenchBank>=2&&Object.values(this.upgrades).some(value=>value<5);window.GameScores?.record({game:"circuit-rush",mode:"championship",difficulty:this.difficulty,metric:"time",value:Math.round(this.raceTime*1000),meta:{track:this.trackIndex+1,position,wrenches:this.trackWrenches}});this.updateUpgradeLabels();this.showRaceResult(position);this.tone(won?920:position===4?190:560,.3,won?"sine":"sawtooth")}
    showRaceResult(position){const lost=position===4,stage=$("result-stage"),panel=$("result-panel");stage.className=`result-stage ${lost?"game-over":"podium"}`;panel.className=`overlay result-panel ${lost?"game-over":"podium"}`;this.renderConfetti(position===1);$("result-kicker").textContent=lost?"Championship ended":this.championshipComplete?"Championship complete":position===1?"Chequered flag":"Race complete";$("result-title").textContent=lost?"Game Over":this.championshipComplete?"Circuit Rush Champion":`${this.ordinal(position)} place`;$("result-detail").textContent=lost?`${this.track.name} · The team will race again.`:`${this.track.name} · ${this.formatTime(this.raceTime)} · ${this.trackWrenches}/2 wrenches found`;$("result-action").textContent=lost?"Start new championship":this.championshipComplete?"Next championship":this.pendingUpgrade?"Visit workshop":this.advanceOnStart?"Next circuit":"Race again";const ranking=this.rankCars().slice(0,3);document.querySelectorAll("#podium-cars i").forEach(marker=>{const car=ranking[Number(marker.dataset.place)-1];marker.className=car?`car-${car.i}`:""});$("overlay").hidden=true;$("upgrade-panel").hidden=true;this.positionResultStage();panel.hidden=false}
    renderConfetti(show){const layer=$("result-confetti");layer.replaceChildren();if(!show)return;const colors=["#66eaff","#ff5c68","#ffd05b","#8dff83","#ffffff"];for(let i=0;i<54;i++){const piece=document.createElement("i"),seed=(i*47)%101,drift=(seed%2?1:-1)*(18+seed%52);piece.style.setProperty("--x",`${(i*37)%100}%`);piece.style.setProperty("--drift",`${drift}px`);piece.style.setProperty("--return",`${drift*-.55}px`);piece.style.setProperty("--fall",`${4.4+(seed%31)/10}s`);piece.style.setProperty("--w",`${4+seed%6}px`);piece.style.setProperty("--h",`${8+seed%10}px`);piece.style.setProperty("--color",colors[i%colors.length]);piece.style.animationDelay=`-${(seed%43)/10}s`;layer.append(piece)}}
    positionResultStage(){const stage=$("result-stage"),canvas=document.querySelector("#game-host canvas"),cabinet=document.querySelector(".cabinet");if(!canvas||!cabinet)return;const field=canvas.getBoundingClientRect(),shell=cabinet.getBoundingClientRect();stage.style.setProperty("--field-left",`${field.left-shell.left}px`);stage.style.setProperty("--field-top",`${field.top-shell.top}px`);stage.style.setProperty("--field-width",`${field.width}px`);stage.style.setProperty("--field-height",`${field.height}px`)}
    continueAfterResult(){$("result-panel").hidden=true;if(this.pendingUpgrade){this.playLobbyMusic();this.positionWorkshop();$("upgrade-panel").hidden=false;return}if(this.resultPosition===1&&this.advanceOnStart){if(this.championshipComplete){this.tour=clamp(this.tour+1,0,99);if(!this.testMode)localStorage.setItem(`${SAVE}_tour`,String(this.tour));this.selectTrack(0);this.championshipComplete=false}else this.selectTrack(this.trackIndex+1);this.advanceOnStart=false}this.startRace()}
    resetChampionship(){this.trackIndex=0;this.unlocked=0;this.upgrades={grip:0,power:0,speed:0};this.wrenchBank=0;this.trackWrenches=0;this.tour=0;this.advanceOnStart=false;this.pendingUpgrade=false;this.resultPosition=null;localStorage.setItem(`${SAVE}_track`,"0");localStorage.setItem(`${SAVE}_tour`,"0");localStorage.setItem(`${SAVE}_unlocked`,"0");localStorage.setItem(`${SAVE}_wrenches`,"0");localStorage.setItem(`${SAVE}_upgrades`,JSON.stringify(this.upgrades));this.selectTrack(0);this.updateUpgradeLabels()}
    beginNewChampionship(){this.difficulty=$("difficulty").value;if(!this.testMode){localStorage.setItem(`${SAVE}_difficulty`,this.difficulty);this.resetChampionship()}this.startRace()}
    continueChampionship(){const saved=localStorage.getItem(`${SAVE}_difficulty`);this.difficulty=["easy","normal","hard"].includes(saved)?saved:"normal";this.startRace()}
    newGame(){this.resetChampionship();localStorage.setItem(`${SAVE}_active`,"0");this.music.pause();this.stopResultMusic();$("result-panel").hidden=true;$("upgrade-panel").hidden=true;this.refreshTitleScreen();$("overlay").hidden=false;requestAnimationFrame(()=>this.positionTitleScreen())}
    refreshTitleScreen(){$("eyebrow").textContent="Daemoncade Motorsports";$("title").textContent="Circuit Rush";$("copy").textContent="Four cars. Five laps. One championship.";$("start").textContent="Start new game";$("difficulty-control").hidden=false;$("continue-game").hidden=localStorage.getItem(`${SAVE}_active`)!=="1"}
    positionTitleScreen(){const overlay=$("overlay"),canvas=document.querySelector("#game-host canvas"),cabinet=document.querySelector(".cabinet");if(!canvas||!cabinet)return;const field=canvas.getBoundingClientRect(),shell=cabinet.getBoundingClientRect();overlay.style.setProperty("--field-center-x",`${field.left-shell.left+field.width/2}px`);overlay.style.setProperty("--field-center-y",`${field.top-shell.top+field.height/2}px`)}
    positionWorkshop(){const panel=$("upgrade-panel"),canvas=document.querySelector("#game-host canvas"),cabinet=document.querySelector(".cabinet");if(!canvas||!cabinet)return;const field=canvas.getBoundingClientRect(),shell=cabinet.getBoundingClientRect();panel.style.setProperty("--field-center-x",`${field.left-shell.left+field.width/2}px`);panel.style.setProperty("--field-center-y",`${field.top-shell.top+field.height/2}px`)}
    applyUpgrade(type){if(this.wrenchBank<2||this.upgrades[type]>=5)return;this.wrenchBank-=2;this.upgrades[type]++;localStorage.setItem(`${SAVE}_wrenches`,String(this.wrenchBank));localStorage.setItem(`${SAVE}_upgrades`,JSON.stringify(this.upgrades));this.updateUpgradeLabels();$("upgrade-panel").hidden=true;this.pendingUpgrade=false;this.tone(760,.16);this.continueAfterResult()}
    updateUpgradeLabels(){document.querySelectorAll("[data-meter]").forEach(meter=>[...meter.children].forEach((pip,i)=>pip.classList.toggle("lit",i<this.upgrades[meter.dataset.meter])));document.querySelectorAll("[data-upgrade]").forEach(button=>button.disabled=this.wrenchBank<2||this.upgrades[button.dataset.upgrade]>=5);document.querySelectorAll("#workshop-wrenches i").forEach((icon,i)=>icon.classList.toggle("lit",i<this.wrenchBank));this.wrenchIcons?.forEach((icon,i)=>icon.setAlpha(i<this.wrenchBank?1:.18).setTint(i<this.wrenchBank?0xffd05b:0x52606d))}
    syncSprites(){for(const car of this.cars){let depth=10,alpha=car.finished?.82:1;if(this.track.bridge){const n=this.points.length,under=(this.track.bridge.center+.5)%1*n,diff=Math.abs(((car.progress-under+n/2)%n)-n/2),fade=this.track.bridge.length+5;if(diff<fade){depth=7;alpha*=clamp(.5+(diff/Math.max(fade,1))*.5,.5,1)}}car.sprite.setPosition(car.x,car.y).setRotation(car.angle+Math.PI/2).setDepth(depth).setAlpha(alpha).setVisible(!car.crashed);car.shadow.setPosition(car.x+2*car.scale,car.y+3*car.scale).setRotation(car.angle).setDepth(depth-.1).setAlpha(alpha*.75).setVisible(!car.crashed)}for(const item of this.pickups||[])if(item.active)item.sprite.rotation+=.018}
    drawEffects(){this.underEffects.clear();this.effects.clear();for(const car of this.cars){if(car.finished||car.crashed)continue;const f=Math.min(car.speed/170,1),scale=car.scale||1,bx=car.x-Math.cos(car.angle)*13*scale,by=car.y-Math.sin(car.angle)*13*scale;if(car===this.player){this.underEffects.lineStyle(1.5*scale,0x66eaff,.28+.2*f).strokeCircle(car.x,car.y,(15+f*2)*scale)}if(car.speed>35)this.underEffects.fillStyle(CAR_COLORS[car.i],.13*f).fillCircle(bx,by,(2+f*3)*scale)}for(const e of this.effectEvents){const a=clamp(e.life/e.max,0,1),r=e.size*(1-a*.55);if(e.kind==="collision")for(let i=0;i<8;i++){const angle=e.angle+(i-3.5)*.35,length=r*(.7+(i%3)*.22);this.effects.lineStyle(i%2?2:1,e.color,a).lineBetween(e.x+Math.cos(angle)*2,e.y+Math.sin(angle)*2,e.x+Math.cos(angle)*length,e.y+Math.sin(angle)*length)}else if(e.kind==="explosion"){this.effects.fillStyle(0xff5a2f,a*.38).fillCircle(e.x,e.y,r*.7);this.effects.lineStyle(3,0xffd05b,a);for(let i=0;i<12;i++){const angle=i/12*TAU,length=r*(.7+(i%4)*.12);this.effects.lineBetween(e.x+Math.cos(angle)*r*.15,e.y+Math.sin(angle)*r*.15,e.x+Math.cos(angle)*length,e.y+Math.sin(angle)*length)}}else if(e.kind==="skid")this.underEffects.lineStyle(e.size,0x080b0e,a*.62).lineBetween(e.x1,e.y1,e.x2,e.y2);else if(e.kind==="dust"||e.kind==="splash"){this.effects.fillStyle(e.color,a*(e.kind==="splash"?.82:.42)).fillCircle(e.x,e.y,Math.max(.6,r));e.x+=e.vx/60;e.y+=e.vy/60;e.vy+=(e.kind==="splash"?24:-2)/60}else{this.effects.lineStyle(2,e.color,a).strokeCircle(e.x,e.y,r);this.effects.fillStyle(e.color,a*.75).fillCircle(e.x,e.y,2+a*2)}}this.effectEvents=this.effectEvents.filter(e=>(e.life-=1/60)>0)}
    collisionBurst(x,y,nx,ny,force){this.effectEvents.push({kind:"collision",x,y,angle:Math.atan2(ny,nx)+Math.PI/2,life:.28,max:.28,color:0xffd05b,size:8+force*12});this.spark(x,y)}
    spark(x,y){this.effectEvents.push({x,y,life:.2,max:.2,color:0xffd05b,size:7});if(this.effectEvents.length>36)this.effectEvents.splice(0,this.effectEvents.length-36)}
    updateHud(){const rank=this.rankCars().indexOf(this.player)+1;this.positionText.setText(`${rank} / 4`);this.lapText.setText(`${Math.min(this.player?.lap+1||1,this.raceLaps)} / ${this.raceLaps}`);this.timeText.setText(this.formatTime(this.raceTime||0));const best=Number(localStorage.getItem(`${SAVE}_best_${this.trackIndex}`));this.bestText.setText(best?this.formatTime(best):"--:--.--");this.wrenchIcons.forEach((icon,i)=>icon.setAlpha(i<this.wrenchBank?1:.18).setTint(i<this.wrenchBank?0xffd05b:0x52606d));if(this.engine){const hz=48+(this.player?.speed||0)*.72;this.engine.frequency.setTargetAtTime(hz,this.audio.currentTime,.04);this.engine2?.frequency.setTargetAtTime(hz*.5,this.audio.currentTime,.05)}}
    formatTime(value){const minutes=Math.floor(value/60),seconds=value-minutes*60;return `${minutes}:${seconds.toFixed(2).padStart(5,"0")}`}
    ordinal(n){return n===1?"1st":n===2?"2nd":n===3?"3rd":"4th"}
    ensureAudio(){if(!this.audio){this.audio=new (window.AudioContext||window.webkitAudioContext)();this.master=this.audio.createGain();this.effectsLimiter=this.audio.createDynamicsCompressor();this.effectsLimiter.threshold.value=-8;this.effectsLimiter.knee.value=12;this.effectsLimiter.ratio.value=8;this.effectsLimiter.attack.value=.003;this.effectsLimiter.release.value=.16;this.musicGain=this.audio.createGain();this.musicSource=this.audio.createMediaElementSource(this.music);this.resultMusicSource=this.audio.createMediaElementSource(this.resultMusic);this.master.gain.value=1.6*(this.effectsVolume/100);this.musicGain.gain.value=0;this.musicSource.connect(this.musicGain);this.resultMusicSource.connect(this.musicGain);this.musicGain.connect(this.audio.destination);this.master.connect(this.effectsLimiter).connect(this.audio.destination);this.applyMusicMix()}this.audio.resume?.()}
    tone(freq,duration,type="square"){if(!this.soundOn||!this.audio)return;const o=this.audio.createOscillator(),g=this.audio.createGain(),now=this.audio.currentTime;o.type=type;o.frequency.setValueAtTime(freq,now);g.gain.setValueAtTime(.12,now);g.gain.exponentialRampToValueAtTime(.001,now+duration);o.connect(g).connect(this.master);o.start(now);o.stop(now+duration)}
    noise(duration=.12,gain=.08,frequency=900){if(!this.soundOn||!this.audio)return;const frames=Math.ceil(this.audio.sampleRate*duration),buffer=this.audio.createBuffer(1,frames,this.audio.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<frames;i++)data[i]=(Math.random()*2-1)*(1-i/frames);const source=this.audio.createBufferSource(),filter=this.audio.createBiquadFilter(),volume=this.audio.createGain(),now=this.audio.currentTime;source.buffer=buffer;filter.type="lowpass";filter.frequency.value=frequency;volume.gain.setValueAtTime(gain,now);volume.gain.exponentialRampToValueAtTime(.001,now+duration);source.connect(filter).connect(volume).connect(this.master);source.start(now)}
    sweep(from,to,duration,gain=.08,type="sawtooth"){if(!this.soundOn||!this.audio)return;const o=this.audio.createOscillator(),g=this.audio.createGain(),now=this.audio.currentTime;o.type=type;o.frequency.setValueAtTime(from,now);o.frequency.exponentialRampToValueAtTime(Math.max(20,to),now+duration);g.gain.setValueAtTime(gain,now);g.gain.exponentialRampToValueAtTime(.001,now+duration);o.connect(g).connect(this.master);o.start(now);o.stop(now+duration)}
    playCollision(force=60){this.noise(.07+Math.min(force,120)/1600,.06,500+force*8);this.sweep(115,65,.09,.035,"square")}
    playSpinout(tornado=false){this.sweep(tornado?760:520,120,tornado?.58:.38,.065,"sawtooth");this.noise(tornado?.38:.18,.045,tornado?1450:850)}
    playSplash(){this.noise(.2,.07,1650);this.sweep(180,75,.16,.025,"sine")}
    playPickup(){this.tone(720,.07,"square");this.time.delayedCall(70,()=>this.tone(1080,.11,"sine"))}
    playExplosion(){this.noise(.48,.16,780);this.sweep(190,38,.46,.11,"sawtooth");this.time.delayedCall(65,()=>this.noise(.24,.09,1800))}
    startEngine(){if(!this.soundOn||!this.audio||this.engine)return;this.engine=this.audio.createOscillator();this.engine2=this.audio.createOscillator();this.engineGain=this.audio.createGain();this.engineFilter=this.audio.createBiquadFilter();this.engine.type="sawtooth";this.engine2.type="triangle";this.engine.frequency.value=55;this.engine2.frequency.value=27.5;this.engineFilter.type="lowpass";this.engineFilter.frequency.value=520;this.engineFilter.Q.value=1.1;this.engineGain.gain.value=.05;this.engine.connect(this.engineFilter);this.engine2.connect(this.engineFilter);this.engineFilter.connect(this.engineGain).connect(this.master);this.engine.start();this.engine2.start()}
    stopEngine(){if(this.engine){this.engine.stop();this.engine2?.stop();this.engine.disconnect();this.engine2?.disconnect();this.engine=null;this.engine2=null}}
  }
  let scene;
  new Phaser.Game({type:Phaser.AUTO,parent:"game-host",width:W,height:H,backgroundColor:"#071017",scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_HORIZONTALLY},render:{antialias:true,roundPixels:false,powerPreference:"high-performance"},fps:{target:60,smoothStep:true},scene:CircuitRush});
})();
