(() => {
  "use strict";
  const $=(id)=>document.getElementById(id),key="jasondaemon.checkers.stats.v1",squares=[];
  let board,turn,selected,mustContinue,over,lastMove;
  const side=(piece)=>piece.toLowerCase()==="r"?"red":piece.toLowerCase()==="b"?"black":"";
  const rc=(i)=>[Math.floor(i/4),(i%4)*2+(Math.floor(i/4)%2===0?1:0)];
  const idx=(r,c)=>r<0||r>7||c<0||c>7||(r+c)%2===0?null:r*4+Math.floor(c/2);
  const dirs=(piece)=>/[RB]/.test(piece)?[[-1,-1],[-1,1],[1,-1],[1,1]]:piece==="r"?[[-1,-1],[-1,1]]:[[1,-1],[1,1]];
  function stats(){try{return JSON.parse(localStorage.getItem(key))||{wins:0,losses:0};}catch{return{wins:0,losses:0};}}
  function save(result){const s=stats();s[result]=(s[result]||0)+1;localStorage.setItem(key,JSON.stringify(s));GameScores.record({game:"checkers",mode:$("mode").value,difficulty:$("difficulty").value,value:s.wins,meta:{result}});}
  function captures(who,from=null,b=board){const out=[];b.forEach((piece,i)=>{if((from!==null&&i!==from)||side(piece)!==who)return;const[r,c]=rc(i);for(const[dR,dC]of dirs(piece)){const mid=idx(r+dR,c+dC),to=idx(r+2*dR,c+2*dC);if(mid!==null&&to!==null&&!b[to]&&b[mid]&&side(b[mid])!==who)out.push({from:i,to,capture:mid});}});return out;}
  function simple(who,b=board){const out=[];b.forEach((piece,i)=>{if(side(piece)!==who)return;const[r,c]=rc(i);for(const[dR,dC]of dirs(piece)){const to=idx(r+dR,c+dC);if(to!==null&&!b[to])out.push({from:i,to});}});return out;}
  function legal(who=turn,b=board,forced=mustContinue){if(forced!==null)return captures(who,forced,b);const jumps=captures(who,null,b);return jumps.length?jumps:simple(who,b);}
  function promote(piece,to){const[row]=rc(to);return piece==="r"&&row===0?"R":piece==="b"&&row===7?"B":piece;}
  function animateMove(move){if(!move||matchMedia("(prefers-reduced-motion: reduce)").matches)return;const from=squares.find((square)=>Number(square.dataset.index)===move.from),to=squares.find((square)=>Number(square.dataset.index)===move.to),piece=to?.querySelector(".piece");if(!from||!to||!piece)return;const a=from.getBoundingClientRect(),b=to.getBoundingClientRect();piece.animate([{transform:`translate(${a.left-b.left}px,${a.top-b.top}px) scale(.94)`,zIndex:8},{transform:"translate(0,0) scale(1.06)",offset:.82},{transform:"translate(0,0) scale(1)"}],{duration:320,easing:"cubic-bezier(.2,.8,.3,1)"});}
  function apply(move,simulate=false,b=board,who=turn){const copy=simulate?[...b]:b,piece=copy[move.from];copy[move.from]="";if(move.capture!==undefined)copy[move.capture]="";copy[move.to]=promote(piece,move.to);if(simulate)return copy;lastMove={...move};const promoted=piece!==copy[move.to];selected=null;mustContinue=null;if(move.capture!==undefined&&!promoted&&captures(who,move.to).length){mustContinue=move.to;selected=move.to;$("message").textContent="Continue the jump with the same checker.";}else turn=who==="red"?"black":"red";checkEnd();render();animateMove(lastMove);if(!over&&$("mode").value==="cpu"&&turn==="black"&&mustContinue===null){$("message").textContent="Computer is choosing…";setTimeout(cpu,360);}}
  function checkEnd(){const red=board.some((p)=>side(p)==="red"),black=board.some((p)=>side(p)==="black");const winner=!red?"black":!black?"red":legal(turn).length?"":turn==="red"?"black":"red";if(!winner)return;over=true;const human=winner==="red";$("message").textContent=$("mode").value==="cpu"?(human?"You won the board.":"The computer won this game."):`${winner[0].toUpperCase()+winner.slice(1)} wins.`;save($("mode").value==="cpu"?(human?"wins":"losses"):"wins");}
  function scoreMove(move){const piece=board[move.from],[row]=rc(move.to);let score=move.capture!==undefined?12:0;if((piece==="b"&&row===7)||piece==="B")score+=5;const next=apply(move,true);score-=captures("red",null,next).length*3;return score+Math.random()*2;}
  function cpu(){if(over||turn!=="black")return;const moves=legal(),difficulty=$("difficulty").value;let move;if(difficulty==="easy")move=moves[Math.floor(Math.random()*moves.length)];else{const sorted=[...moves].sort((a,b)=>scoreMove(b)-scoreMove(a));move=difficulty==="medium"&&Math.random()<.25?moves[Math.floor(Math.random()*moves.length)]:sorted[0];}apply(move);if(!over&&turn==="black"&&mustContinue!==null)setTimeout(cpu,260);}
  function render(){const moves=legal(),targets=selected===null?[]:moves.filter((move)=>move.from===selected);squares.forEach((square)=>{const i=Number(square.dataset.index),piece=i>=0?board[i]:"";square.replaceChildren();square.classList.remove("selected","selectable","target");if(i<0)return;if(piece){const element=document.createElement("span");element.className=`piece ${side(piece)} ${/[RB]/.test(piece)?"king":""}`;element.setAttribute("aria-hidden","true");square.append(element);}if(moves.some((move)=>move.from===i))square.classList.add("selectable");if(i===selected)square.classList.add("selected");if(targets.some((move)=>move.to===i))square.classList.add("target");});$("turn").textContent=over?"Game over":turn[0].toUpperCase()+turn.slice(1);$("counts").textContent=`${board.filter((p)=>side(p)==="red").length} red · ${board.filter((p)=>side(p)==="black").length} black`;const s=stats();$("stats").innerHTML=`Local record<br><strong>${s.wins||0} wins · ${s.losses||0} losses</strong>`;}
  function click(i){if(over||($("mode").value==="cpu"&&turn==="black"))return;const moves=legal(),target=selected===null?null:moves.find((move)=>move.from===selected&&move.to===i);if(target)return apply(target);if(moves.some((move)=>move.from===i)){selected=i;$("message").textContent="Choose a highlighted destination.";}else{selected=mustContinue;$("message").textContent=moves.some((move)=>move.capture!==undefined)?"A jump is available and must be taken.":"Choose one of your checkers.";}render();}
  function reset(){board=Array(32).fill("");for(let i=0;i<12;i++)board[i]="b";for(let i=20;i<32;i++)board[i]="r";turn="red";selected=null;mustContinue=null;over=false;lastMove=null;$("message").textContent="Red moves first. Choose a checker.";$("difficulty").hidden=$("mode").value!=="cpu";render();}
  for(let r=0;r<8;r++)for(let c=0;c<8;c++){const button=document.createElement("button"),i=idx(r,c);button.type="button";button.className=`square ${i===null?"":"dark"}`;button.dataset.index=i===null?-1:i;button.setAttribute("aria-label",i===null?"Light square":`Playable square ${i+1}`);button.addEventListener("click",()=>i!==null&&click(i));$("board").append(button);squares.push(button);}$("new").addEventListener("click",reset);$("mode").addEventListener("change",reset);reset();
})();
