(() => {
  "use strict";
  const canvas=document.querySelector("#board"),ctx=canvas.getContext("2d");
  // Navigation uses a half-tower lattice. Towers occupy 2×2 navigation cells,
  // allowing placement every 20 pixels while creeps move continuously between nodes.
  const W=48,H=32,C=20;
  const modes={
    easy:{group:"standard",name:"Easy",desc:"Stronger towers, a relaxed wave timer, and generous rewards.",waves:150,lives:20,cash:90,hp:.8,reward:1.2,towerPower:1.12,waveTimer:12},
    medium:{group:"standard",name:"Medium",desc:"The intended balance across five increasingly complex stages.",waves:150,lives:20,cash:80,hp:1,reward:1,towerPower:1,waveTimer:10},
    hard:{group:"standard",name:"Hard",desc:"Tougher enemies, leaner towers, and faster automatic waves.",waves:150,lives:15,cash:75,hp:1.48,reward:.9,splitDepth:2,towerPower:.86,waveTimer:8},
    hundred:{group:"challenge",name:"The 100",desc:"A full hundred-wave endurance run.",waves:100,lanes:2,lives:20,cash:85,hp:1.05,reward:1},
    speed:{group:"challenge",name:"Speed",desc:"Waves arrive rapidly. There is almost no breathing room.",waves:50,lanes:2,lives:20,cash:100,hp:1,reward:1,auto:3},
    fifteen:{group:"challenge",name:"15 Towers",desc:"Survive 50 waves with no more than fifteen towers.",waves:50,lanes:2,lives:20,cash:100,hp:1,reward:1,towerCap:15},
    survivor:{group:"challenge",name:"Survivor",desc:"Every wave splits. The swarm multiplies as it advances.",waves:50,lanes:2,lives:25,cash:110,hp:.8,reward:1,only:"spawn"},
    fixed:{group:"challenge",name:"3K Fixed",desc:"Start with 3,000 credits. Defeated creeps pay nothing.",waves:50,lanes:2,lives:20,cash:3000,hp:1.15,reward:0,noIncome:true},
    nosplash:{group:"challenge",name:"No Splash",desc:"Area-damage towers are unavailable.",waves:50,lanes:2,lives:20,cash:95,hp:1,reward:1,noSplash:true},
    squirts:{group:"challenge",name:"Flow Control",desc:"Only Repeater and Cryo towers may be built.",waves:50,lanes:2,lives:20,cash:105,hp:1,reward:1,onlyTowers:["squirt","frost"]},
    fivemin:{group:"challenge",name:"Five Minutes",desc:"Score as many completed waves as possible before time expires.",waves:999,lanes:2,lives:30,cash:110,hp:.82,reward:1.15,timed:300,auto:2.4},
    nosell:{group:"challenge",name:"No Sell",desc:"Every placement is permanent. Plan the maze carefully.",waves:50,lanes:2,lives:20,cash:100,hp:1,reward:1,noSell:true}
  };
  const stages=[
    {name:"Open Field",waves:30,entries:[{x:0,y:16,side:"left"}],exits:[{x:47,y:16,side:"right"}],map:[0],barriers:[]},
    {name:"Hard Edges",waves:35,entries:[{x:8,y:0,side:"top"}],exits:[{x:39,y:31,side:"bottom"}],map:[0],barriers:[[12,6,2,7],[34,20,2,7]]},
    {name:"Cross Traffic",waves:40,entries:[{x:0,y:8,side:"left"},{x:34,y:0,side:"top"}],exits:[{x:47,y:24,side:"right"}],map:[0,0],barriers:[[20,12,7,2],[7,23,6,2]]},
    {name:"Blind Corners",waves:45,entries:[{x:10,y:31,side:"bottom"},{x:0,y:25,side:"left"}],exits:[{x:42,y:0,side:"top"}],map:[0,0],barriers:[[30,6,2,8],[38,25,6,2],[15,18,2,6]]},
    {name:"Split Decision",waves:50,entries:[{x:0,y:8,side:"left"},{x:31,y:0,side:"top"}],exits:[{x:47,y:23,side:"right"},{x:14,y:31,side:"bottom"}],map:[0,1],barriers:[[5,15,6,2],[26,24,2,6],[39,10,2,7]]}
  ];
  const minimumGateDistance=30;
  const towerDefs={
    pellet:{name:"Needle",cost:5,color:"#7dd3fc",range:2.7,rate:.58,damage:8,damageType:"kinetic",desc:"Cheap, steady ground fire."},
    squirt:{name:"Repeater",cost:15,color:"#38bdf8",range:3.5,rate:.19,damage:5,damageType:"energy",desc:"Rapid stream against any target."},
    bash:{name:"Mortar",cost:40,color:"#fb7185",range:3.15,rate:1.5,damage:28,damageType:"explosive",desc:"Lobs heavy shells at ground or air targets."},
    pulse:{name:"Pulse",cost:48,color:"#c084fc",range:2.35,rate:1.65,damage:18,damageType:"shock",pulse:true,desc:"A slow radiating shock damages every ground creep nearby."},
    frost:{name:"Cryo",cost:25,color:"#a5f3fc",range:3.1,rate:.9,damage:3,damageType:"cryo",slow:.58,desc:"Slows a group of advancing creeps."},
    swarm:{name:"Flak",cost:40,color:"#facc15",range:4.1,rate:.42,damage:13,damageType:"explosive",airOnly:true,desc:"Dedicated anti-air missile battery."},
    rail:{name:"Rail",cost:65,color:"#fb923c",range:5.6,rate:1.8,damage:58,damageType:"piercing",rail:true,desc:"Long-range precision fire against the toughest target."},
    boost:{name:"Relay",cost:45,color:"#a3e635",range:2.3,rate:0,damage:0,support:true,desc:"Amplifies nearby tower damage."}
  };
  const progression={
    pellet:{targets:"Ground",special:"Fast single-target fire",three:{name:"Quickdraw",desc:"Fires 50% faster."},six:{name:"Arc Needle",desc:"Charged rounds chain through up to three nearby enemies."}},
    squirt:{targets:"Ground + air",special:"Rapid fire",three:{name:"Twin Feed",desc:"Tracks and fires at two targets at once."},six:{name:"Crosscurrent",desc:"Every round ricochets once for 65% damage."}},
    bash:{targets:"Ground + air",special:"Heavy arcing shell",three:{name:"Blast Shell",desc:"Impacts gain splash damage and a visible shockwave."},six:{name:"Airburst",desc:"The blast radius grows and shrapnel strikes every target type."}},
    pulse:{targets:"Ground",special:"Hits every target in its radius",three:{name:"Wideband",desc:"Pulse radius grows by 25%."},six:{name:"Aftershock",desc:"A second ring deals bonus damage and briefly stuns survivors."}},
    frost:{targets:"Ground",special:"Slows advancing enemies",three:{name:"Cold Front",desc:"Freeze range grows by 25%."},six:{name:"Deep Freeze",desc:"Slows more heavily and makes frozen enemies take 25% more damage."}},
    swarm:{targets:"Air only",special:"Anti-air missiles",three:{name:"Cluster Flak",desc:"Missiles splash nearby flying enemies."},six:{name:"Sky Barrage",desc:"Launches at up to three air targets per volley."}},
    rail:{targets:"Ground",special:"Long-range precision fire",three:{name:"Dense Core",desc:"Shots ignore enemy resistance."},six:{name:"Throughline",desc:"Rounds overpenetrate into two enemies behind the target."}},
    boost:{targets:"Nearby towers",special:"Damage support",three:{name:"Wide Relay",desc:"Support radius grows by 25%."},six:{name:"Hot Clock",desc:"Supported towers gain fire rate as well as damage."}}
  };
  const enemyDefs={
    normal:{name:"Normal",color:"#f8fafc",speed:1,hp:1,reward:1,armor:"light"},fast:{name:"Fast",color:"#facc15",speed:1.75,hp:.64,reward:1,armor:"light"},
    spawn:{name:"Spawn",color:"#a3e635",speed:.92,hp:.88,reward:1,split:true},dark:{name:"Dark",color:"#8b5cf6",speed:.82,hp:1.85,reward:2,resist:.42},
    morph:{name:"Morph",color:"#fb7185",speed:1.08,hp:1.15,reward:2,morph:true},flying:{name:"Flying",color:"#38bdf8",speed:1.3,hp:.85,reward:2,air:true},
    armored:{name:"Bulwark",color:"#94a3b8",speed:.62,hp:3.2,reward:4,resist:.28,armor:"heavy",armored:true},regen:{name:"Reclaimer",color:"#34d399",speed:.78,hp:2.25,reward:4,armor:"medium",regen:.018},phaser:{name:"Phaser",color:"#f0abfc",speed:1.22,hp:1.5,reward:4,armor:"phase",evade:.22,phaser:true},
    boss:{name:"Siege Core",color:"#f97316",speed:.58,hp:11,reward:14,boss:true},hiveboss:{name:"Brood Engine",color:"#84cc16",speed:.54,hp:13,reward:18,boss:true,split:true},airboss:{name:"Sky Fortress",color:"#22d3ee",speed:.66,hp:10,reward:20,boss:true,air:true}
  };
  const enemyGuide={
    normal:{arrival:"Every round · Wave 1",ability:"No special defenses. Every new board begins with this baseline threat."},fast:{arrival:"Round 1 · Wave 5",ability:"Trades durability for significantly higher speed."},spawn:{arrival:"Round 1 · Wave 9",ability:"Splits into smaller creeps when destroyed."},dark:{arrival:"Round 1 · Wave 13",ability:"Resists most damage, but Repeater fire remains effective."},flying:{arrival:"Round 1 · Wave 17",ability:"Flies directly to its mapped exit and ignores the maze."},morph:{arrival:"Round 1 · Wave 21",ability:"Unstable form causes incoming damage to fluctuate."},armored:{arrival:"Round 1 · Wave 25",ability:"Heavy armor absorbs most ordinary projectile damage."},regen:{arrival:"Round 2 · Later waves",ability:"Continuously repairs a percentage of its maximum health."},phaser:{arrival:"Round 3 · Later waves",ability:"Periodically phases out and completely avoids a hit."},boss:{arrival:"Round bosses",ability:"Extremely durable siege unit with a large escape penalty."},hiveboss:{arrival:"Rounds 2 and 5",ability:"Boss-class brood carrier that splits when destroyed."},airboss:{arrival:"Round 3 onward",ability:"Flying boss that bypasses the maze and demands strong anti-air coverage."}
  };
  let selectedMode="easy",tab="standard",mode,state,last=performance.now(),raf;
  const $=s=>document.querySelector(s),ui={start:$("#start-screen"),game:$("#game-screen"),modeList:$("#mode-list"),begin:$("#begin"),continueGame:$("#continue-game"),towerList:$("#tower-list"),stage:$("#stage"),wave:$("#wave"),lives:$("#lives"),credits:$("#credits"),score:$("#score"),mode:$("#mode-name"),status:$("#status"),next:$("#next-wave"),incoming:$("#incoming"),selectionName:$("#selection-name"),selectionCopy:$("#selection-copy"),selectionStats:$("#selection-stats"),targetingControl:$("#targeting-control"),targeting:$("#targeting"),upgrade:$("#upgrade"),sell:$("#sell"),send:$("#send-wave"),overdrive:$("#overdrive"),lockdown:$("#lockdown"),pause:$("#pause"),speed:$("#speed"),audio:$("#audio"),progression:$("#progression"),progressionDialog:$("#progression-dialog"),progressionList:$("#progression-list"),progressionClose:$("#progression-close"),enemies:$("#enemies"),enemyDialog:$("#enemy-dialog"),enemyList:$("#enemy-list"),enemyClose:$("#enemy-close"),notice:$("#round-notice"),noticeKicker:$("#notice-kicker"),noticeTitle:$("#notice-title"),noticeCopy:$("#notice-copy"),noticeParticles:$(".notice-particles")};
  const saveKey="jasondaemon.maze-defense.save.v1";
  let audioContext=null,audioEnabled=localStorage.getItem("jasondaemon.maze-defense.sound")!=="off";
  function savedSnapshot(){try{const saved=JSON.parse(localStorage.getItem(saveKey));return saved?.version===1&&modes[saved.mode]&&!saved.ended?saved:null}catch{return null}}
  function updateContinueButton(){const saved=savedSnapshot();ui.continueGame.hidden=!saved;if(saved)ui.continueGame.textContent=`Continue previous game · Round ${saved.state.stage}, Wave ${saved.state.stageWave}`}
  function saveGame(){if(!state||state.ended||state.transitioning)return;const enemies=state.enemies.map(({path,...e})=>e),spawnQueue=state.spawnQueue.map(q=>({...q,remaining:Math.max(0,q.at-state.elapsed),at:undefined}));localStorage.setItem(saveKey,JSON.stringify({version:1,mode:selectedMode,savedAt:Date.now(),state:{stage:state.stage,stageWave:state.stageWave,wave:state.wave,lives:state.lives,cash:state.cash,score:state.score,speed:state.speed,elapsed:state.elapsed,build:state.build,towers:state.towers,enemies,spawnQueue,barriers:state.barriers,waveActive:state.waveActive,waitingForFirstWave:state.waitingForFirstWave,nextTimer:state.nextTimer,abilities:state.abilities}}));updateContinueButton()}
  function clearSavedGame(){localStorage.removeItem(saveKey);updateContinueButton()}
  function restoreGame(){const saved=savedSnapshot();if(!saved)return;selectedMode=saved.mode;mode=modes[selectedMode];const s=saved.state;state={towers:s.towers||[],enemies:s.enemies||[],shots:[],pulses:[],arcs:[],particles:[],paths:[],barriers:s.barriers||[],build:s.build||"pellet",selected:null,hover:null,stage:s.stage||1,stageWave:s.stageWave||0,wave:s.wave||0,lives:s.lives,cash:s.cash,score:s.score||0,paused:true,speed:s.speed||1,spawnQueue:[],waveActive:!!s.waveActive,waitingForFirstWave:!!s.waitingForFirstWave,transitioning:false,nextTimer:s.nextTimer??waveInterval(),elapsed:s.elapsed||0,ended:false,noticeTimer:null,transitionTimer:null,saveClock:0,abilities:s.abilities||{overdriveReady:0,lockdownReady:0,overdriveUntil:0}};state.spawnQueue=(s.spawnQueue||[]).map(q=>({...q,at:state.elapsed+(q.remaining||0)}));refreshPaths();for(const e of state.enemies){const d=enemyDefs[e.type],start=entries()[e.lane]||entries()[0],goal=exitForLane(e.lane||0);if(d.air){e.path=[{x:start.x+.5,y:start.y+.5},{x:goal.x+.5,y:goal.y+.5}];e.pi=0}else{e.path=nearestPath(e);e.pi=closestIndex(e.path,e.x,e.y)}}ui.start.hidden=true;ui.game.hidden=false;ui.pause.textContent="Resume";ui.speed.textContent=`${state.speed}× speed`;buildTowerButtons();updateSelection();updateUI();showNotice("Game Paused",`Round ${state.stage} · Wave ${state.stageWave}`,"Welcome back","round",1800);last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
  function ensureAudio(){if(!audioEnabled)return null;if(!audioContext)audioContext=new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state==="suspended")audioContext.resume();return audioContext}
  function tone(freq,duration=.06,type="sine",volume=.025,slide=0){const ac=ensureAudio();if(!ac)return;const now=ac.currentTime,o=ac.createOscillator(),g=ac.createGain();o.type=type;o.frequency.setValueAtTime(freq,now);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(30,freq+slide),now+duration);g.gain.setValueAtTime(volume,now);g.gain.exponentialRampToValueAtTime(.0001,now+duration);o.connect(g).connect(ac.destination);o.start(now);o.stop(now+duration)}
  function sound(event,type=""){if(!audioEnabled)return;if(event==="build")tone(330,.07,"triangle",.022,190);else if(event==="upgrade"){tone(440,.08,"triangle",.024,240);setTimeout(()=>tone(660,.09,"triangle",.018,180),55)}else if(event==="wave")tone(180,.13,"sawtooth",.025,90);else if(event==="escape")tone(120,.16,"square",.02,-55);else if(event==="impact")tone(type==="bash"?75:type==="frost"?520:type==="swarm"?125:260,type==="bash"?.16:.055,type==="frost"?"sine":"triangle",type==="bash"?.035:.014,type==="bash"?-30:60);else if(event==="fire"){const f={pellet:680,squirt:920,bash:105,pulse:145,frost:480,swarm:210,rail:1040}[type]||400;tone(f,type==="bash"?.11:type==="rail"?.08:.035,type==="bash"?"sine":type==="rail"?"sawtooth":"square",type==="bash"?.024:.009,type==="bash"?-45:type==="rail"?-400:80)}}

  function renderModes(){ui.modeList.innerHTML="";Object.entries(modes).filter(([,m])=>m.group===tab).forEach(([key,m])=>{const b=document.createElement("button");b.className=`mode-card${key===selectedMode?" active":""}`;b.type="button";b.innerHTML=`<strong>${m.name}</strong><span>${m.desc}</span>`;b.onclick=()=>{selectedMode=key;renderModes();ui.begin.textContent=`Start ${m.name}`};ui.modeList.append(b)});if(modes[selectedMode].group!==tab){selectedMode=Object.keys(modes).find(k=>modes[k].group===tab);renderModes();ui.begin.textContent=`Start ${modes[selectedMode].name}`}}
  document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll("[data-tab]").forEach(x=>x.classList.toggle("active",x===b));renderModes()});

  function stageDef(n=state?.stage||1){return stages[Math.max(0,Math.min(stages.length-1,n-1))]}
  function stageWaveLimit(n=state?.stage||1){if(mode.group==="standard")return stageDef(n).waves;if(mode.waves===999)return Infinity;const weights=stages.map(s=>s.waves),total=weights.reduce((a,b)=>a+b,0),before=weights.slice(0,n-1).reduce((a,b)=>a+b,0),through=before+weights[n-1];return Math.round(mode.waves*through/total)-Math.round(mode.waves*before/total)}
  function entries(){return stageDef().entries}
  function exits(){return stageDef().exits}
  function exitForLane(lane,stage=stageDef()){return stage.exits[stage.map[lane]??0]}
  const key=(x,y)=>y*W+x;
  function occupies(t,x,y){return x>=t.x&&x<t.x+2&&y>=t.y&&y<t.y+2}
  function barrierAt(x,y,barriers=state.barriers){return barriers.some(b=>x>=b.x&&x<b.x+b.w&&y>=b.y&&y<b.y+b.h)}
  function blocked(x,y,extra,barriers=state.barriers){return x<0||y<0||x>=W||y>=H||barrierAt(x,y,barriers)||state.towers.some(t=>occupies(t,x,y))||(extra&&occupies(extra,x,y))}
  function pathFor(stageNumber,lane,extra,barriers=state.barriers){const s=stageDef(stageNumber),start=s.entries[lane],goal=exitForLane(lane,s);if(Math.abs(start.x-goal.x)+Math.abs(start.y-goal.y)<minimumGateDistance)return null;const dirs=[[1,0,1],[-1,0,1],[0,1,1],[0,-1,1],[1,1,Math.SQRT2],[1,-1,Math.SQRT2],[-1,1,Math.SQRT2],[-1,-1,Math.SQRT2]],open=[{x:start.x,y:start.y,g:0,f:Math.hypot(goal.x-start.x,goal.y-start.y)}],cost=new Map([[key(start.x,start.y),0]]),prev=new Map([[key(start.x,start.y),null]]);let end=null;while(open.length){let bi=0;for(let i=1;i<open.length;i++)if(open[i].f<open[bi].f)bi=i;const p=open.splice(bi,1)[0];if(p.x===goal.x&&p.y===goal.y){end=[p.x,p.y];break}for(const [dx,dy,step] of dirs){const nx=p.x+dx,ny=p.y+dy,k=key(nx,ny);if(blocked(nx,ny,extra,barriers))continue;if(dx&&dy&&(blocked(p.x+dx,p.y,extra,barriers)||blocked(p.x,p.y+dy,extra,barriers)))continue;const ng=p.g+step;if(ng>=(cost.get(k)??Infinity))continue;cost.set(k,ng);prev.set(k,[p.x,p.y]);open.push({x:nx,y:ny,g:ng,f:ng+Math.hypot(goal.x-nx,goal.y-ny)})}}if(!end)return null;const out=[];for(let p=end;p;p=prev.get(key(p[0],p[1])))out.push({x:p[0]+.5,y:p[1]+.5});return out.reverse()}
  function allPaths(extra,stageNumber=state.stage,barriers=state.barriers){return stageDef(stageNumber).entries.map((_,lane)=>pathFor(stageNumber,lane,extra,barriers))}
  function towerAt(x,y){return state.towers.find(t=>occupies(t,x,y))}
  function canBuild(x,y){if(x<0||y<0||x>W-2||y>H-2)return false;const gates=[...entries(),...exits()];for(let yy=y;yy<y+2;yy++)for(let xx=x;xx<x+2;xx++)if(blocked(xx,yy)||gates.some(e=>e.x===xx&&e.y===yy))return false;return allPaths({x,y}).every(Boolean)}
  function refreshPaths(){state.paths=allPaths();state.enemies.filter(e=>!e.air).forEach(e=>{const p=nearestPath(e);e.path=p;e.pi=Math.max(0,closestIndex(p,e.x,e.y))})}
  function closestIndex(path,x,y){let bi=0,bd=Infinity;path.forEach((p,i)=>{const d=(p.x-x)**2+(p.y-y)**2;if(d<bd){bd=d;bi=i}});return bi}
  function nearestPath(e){return state.paths[e.lane]||state.paths[0]}
  function buildTowerButtons(){ui.towerList.innerHTML="";Object.entries(towerDefs).forEach(([id,t])=>{const p=progression[id],b=document.createElement("button"),preview=document.createElement("canvas"),copy=document.createElement("span"),tip=document.createElement("span");b.type="button";b.className="tower-button";b.dataset.tower=id;preview.width=92;preview.height=92;preview.setAttribute("aria-hidden","true");copy.className="tower-copy";copy.innerHTML=`<strong>${t.name}</strong><span>${t.cost} credits</span>`;tip.className="tower-tooltip";tip.innerHTML=`<strong>${p.targets} · Power ${t.support?"+22%":t.damage}</strong><span>${t.desc}</span><span>${p.special}</span><span>Level 5: ${p.three.name} · Level 10: ${p.six.name}</span>`;b.append(preview,copy,tip);drawTowerGlyph(preview.getContext("2d"),id,46,46,2.15,1,0);b.onclick=()=>{state.build=id;state.selected=null;updateSelection();buildTowerButtons()};b.disabled=(mode.noSplash&&(id==="bash"||id==="pulse"))||(mode.onlyTowers&&!mode.onlyTowers.includes(id));b.classList.toggle("active",state.build===id);ui.towerList.append(b)})}
  function waveInterval(){return mode.auto||mode.waveTimer||10}
  function deploymentRest(){return 10}
  function showNotice(title,copy,kicker="Prepare the field",kind="round",duration=2100){clearTimeout(state?.noticeTimer);ui.noticeKicker.textContent=kicker;ui.noticeTitle.textContent=title;ui.noticeCopy.textContent=copy;ui.notice.className=`round-notice ${kind}`;ui.noticeParticles.innerHTML="";for(let i=0;i<30;i++){const p=document.createElement("i");p.style.setProperty("--a",`${i*12+Math.random()*8}deg`);p.style.setProperty("--d",`${90+Math.random()*250}px`);p.style.animationDelay=`${Math.random()*.28}s`;ui.noticeParticles.append(p)}ui.notice.setAttribute("aria-hidden","false");requestAnimationFrame(()=>ui.notice.classList.add("show"));if(duration&&state)state.noticeTimer=setTimeout(()=>hideNotice(),duration)}
  function hideNotice(){ui.notice.classList.remove("show");ui.notice.setAttribute("aria-hidden","true")}
  function roundBarriers(stageNumber){const accepted=[];for(const raw of stageDef(stageNumber).barriers){const b={x:raw[0],y:raw[1],w:raw[2],h:raw[3]},next=[...accepted,b];if(allPaths(null,stageNumber,next).every(Boolean))accepted.push(b)}return accepted}
  function applyStage(stageNumber){state.stage=stageNumber;state.stageWave=0;state.towers=[];state.enemies=[];state.shots=[];state.pulses=[];state.arcs=[];state.particles=[];state.spawnQueue=[];state.selected=null;state.hover=null;state.barriers=[];state.barriers=roundBarriers(stageNumber);state.cash=mode.cash+(stageNumber-1)*45;state.build="pellet";state.waitingForFirstWave=true;state.transitioning=false;refreshPaths();state.nextTimer=waveInterval();state.waveActive=false;buildTowerButtons();updateSelection();ui.status.textContent=`Round ${stageNumber}: ${stageDef().name} · build, then deploy when ready.`;showNotice(`Round ${stageNumber}`,stageDef().name,"New battlefield")}
  function startGame(){clearSavedGame();mode=modes[selectedMode];state={towers:[],enemies:[],shots:[],pulses:[],arcs:[],particles:[],paths:[],barriers:[],build:"pellet",selected:null,hover:null,stage:1,stageWave:0,wave:0,lives:mode.lives,cash:mode.cash,score:0,paused:false,speed:1,spawnQueue:[],waveActive:false,waitingForFirstWave:true,transitioning:false,nextTimer:waveInterval(),elapsed:0,ended:false,noticeTimer:null,transitionTimer:null,saveClock:0,abilities:{overdriveReady:0,lockdownReady:0,overdriveUntil:0}};refreshPaths();ui.start.hidden=true;ui.game.hidden=false;buildTowerButtons();updateSelection();updateUI();showNotice("Round 1",stageDef().name,"Build your maze");last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
  function waveType(n,round=state.stage){if(mode.only)return mode.only;const limit=stageWaveLimit(round);if(n===limit)return["boss","hiveboss","airboss","boss","hiveboss"][round-1];if(n>12&&n%15===0)return round>=3&&n%30===0?"airboss":"boss";const roster=["normal","fast","spawn","dark","flying","morph","armored","regen","phaser"],span=[4,3,2,2,1][round-1],maxUnlock=[6,7,8,8,8][round-1],unlocked=Math.min(maxUnlock,Math.floor((n-1)/span));if(unlocked===0)return"normal";if((n-1)%span===0)return roster[unlocked];const recent=roster.slice(Math.max(0,unlocked-2),unlocked+1);return recent[(n+round)%recent.length]}
  function waveInfo(localWave,round=state.stage){const type=waveType(localWave,round),boss=!!enemyDefs[type].boss,growth=[1.03,1.04,1.05,1.06,1.07][round-1],count=boss?Math.max(1,Math.ceil(round*(mode.hp||1))):Math.min(8+Math.floor(localWave*.3)+(round-1),28),base=18*(1+(round-1)*.12)*Math.pow(growth,localWave-1)*mode.hp,gap=boss?1.05:Math.max(.17,.62-localWave*.004-round*.008);let groups=[{type,count,hp:base*(enemyDefs[type].hp||1)}];if(boss){const escort=enemyDefs[type].air?"flying":round>=3?"armored":"fast";groups.push({type:escort,count:3+round,hp:base*.72*(enemyDefs[escort].hp||1)})}else if(localWave>=6){const secondary=waveType(Math.max(1,localWave-2),round);if(secondary!==type){const secondaryCount=Math.max(2,Math.round(count*.3));groups=[{type,count:count-secondaryCount,hp:base*(enemyDefs[type].hp||1)},{type:secondary,count:secondaryCount,hp:base*.9*(enemyDefs[secondary].hp||1)}]}}return{type,count:groups.reduce((n,g)=>n+g.count,0),hp:groups[0].hp,gap,groups}}
  function earlyWaveBonus(){if(state.waitingForFirstWave||state.nextTimer<=0)return 0;return Math.min(24,Math.max(0,Math.floor(Math.min(deploymentRest(),state.nextTimer)*1.4)))}
  function sendWave(manual=true){const s=stageDef(),limit=stageWaveLimit();if(state.ended||state.transitioning||state.stageWave>=limit)return;const bonus=manual?earlyWaveBonus():0;if(bonus&&!mode.noIncome){state.cash+=bonus;state.score+=bonus*3}hideNotice();state.waitingForFirstWave=false;ensureAudio();sound("wave");state.wave++;state.stageWave++;const w=waveInfo(state.stageWave),lanes=s.entries.length,baseAt=state.elapsed,plan=[];for(const group of w.groups)for(let i=0;i<group.count;i++)plan.push({type:group.type,hp:group.hp});for(let i=0;i<plan.length;i++)for(let lane=0;lane<lanes;lane++)state.spawnQueue.push({at:baseAt+i*w.gap,type:plan[i].type,hp:plan[i].hp,lane,depth:mode.splitDepth||1});state.spawnQueue.sort((a,b)=>a.at-b.at);state.waveActive=true;const finalDeployment=state.spawnQueue.reduce((latest,q)=>Math.max(latest,q.at),baseAt);state.nextTimer=Math.max(0,finalDeployment-state.elapsed)+deploymentRest();const names=w.groups.map(g=>enemyDefs[g.type].name).join(" + ");ui.status.textContent=`Round ${state.stage} · Wave ${state.stageWave}: ${names}${bonus?` · ${bonus} early credits`:""}`;updateUI()}
  function spawn(spec){const d=enemyDefs[spec.type],e0=entries()[spec.lane],goal=exitForLane(spec.lane);state.enemies.push({type:spec.type,x:e0.x+.5,y:e0.y+.5,lane:spec.lane,path:d.air?[{x:e0.x+.5,y:e0.y+.5},{x:goal.x+.5,y:goal.y+.5}]:state.paths[spec.lane],pi:0,hp:spec.hp,maxHp:spec.hp,speed:d.speed*2,slow:1,slowTime:0,vulnerable:1,vulnerableTime:0,stun:0,depth:spec.depth||0,angle:0,phase:Math.random()*Math.PI*2})}
  function update(dt){if(state.paused||state.ended||state.transitioning)return;dt*=state.speed;state.elapsed+=dt;state.saveClock=(state.saveClock||0)+dt;if(state.saveClock>=2){state.saveClock=0;saveGame()}if(mode.timed&&state.elapsed>=mode.timed){finish(true);return}while(state.spawnQueue.length&&state.spawnQueue[0].at<=state.elapsed)spawn(state.spawnQueue.shift());if(state.waveActive&&!state.spawnQueue.length&&!state.enemies.length){state.waveActive=false;const interest=mode.noIncome?0:Math.min(10,Math.floor(state.cash*.025));state.cash+=interest;state.score+=state.wave*10+state.lives;if(state.stageWave>=stageWaveLimit()){if(state.stage>=stages.length){finish(true);return}const cleared=state.stage,next=state.stage+1;state.score+=500*state.stage;state.transitioning=true;ui.status.textContent=`Round ${cleared} complete.`;showNotice(`Round ${cleared} Clear`,`Round ${next} is next.`,"Field secured","victory",1250);state.transitionTimer=setTimeout(()=>applyStage(next),1400);return}else ui.status.textContent=interest?`Field clear · ${interest} reserve bonus earned.`:"Field clear."}if(!state.waitingForFirstWave&&state.stageWave<stageWaveLimit()){state.nextTimer-=dt;if(state.nextTimer<=0)sendWave(false)}
    for(const e of [...state.enemies])moveEnemy(e,dt);for(const t of state.towers)updateTower(t,dt);updateProjectiles(dt);state.pulses.forEach(s=>s.life-=dt);state.pulses=state.pulses.filter(s=>s.life>0);state.arcs.forEach(s=>s.life-=dt);state.arcs=state.arcs.filter(s=>s.life>0);state.particles.forEach(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt});state.particles=state.particles.filter(p=>p.life>0);updateUI()}
  function releaseEscorts(e,type,count){const d=enemyDefs[type];for(let i=0;i<count;i++)state.enemies.push({type,x:e.x+(Math.random()-.5)*.3,y:e.y+(Math.random()-.5)*.3,lane:e.lane,path:d.air?[e.path[e.pi]||{x:e.x,y:e.y},e.path.at(-1)]:e.path,pi:d.air?0:e.pi,hp:e.maxHp*.1*(d.hp||1),maxHp:e.maxHp*.1*(d.hp||1),speed:d.speed*2,slow:1,slowTime:0,vulnerable:1,vulnerableTime:0,stun:0,depth:0,angle:e.angle,phase:Math.random()*Math.PI*2})}
  function updateBossPhase(e){const ratio=e.hp/e.maxHp;if(e.type==="boss"&&ratio<.35&&!e.finalPhase){e.finalPhase=true;e.speed*=1.45;state.pulses.push({x:e.x,y:e.y,r:1.8,color:"#f97316",life:.6,duration:.6})}if(e.type==="hiveboss"){e.phases??=0;const needed=ratio<.35?2:ratio<.7?1:0;while(e.phases<needed){e.phases++;releaseEscorts(e,"spawn",4+e.phases)}}if(e.type==="airboss"){e.phases??=0;const needed=ratio<.4?2:ratio<.72?1:0;while(e.phases<needed){e.phases++;releaseEscorts(e,"flying",3+e.phases)}}}
  function moveEnemy(e,dt){const def=enemyDefs[e.type];if(def.boss)updateBossPhase(e);if(def.regen)e.hp=Math.min(e.maxHp,e.hp+e.maxHp*def.regen*dt);if(e.vulnerableTime>0)e.vulnerableTime-=dt;else e.vulnerable=1;if(e.stun>0){e.stun-=dt;return}if(e.slowTime>0)e.slowTime-=dt;else e.slow=1;const p=e.path[e.pi+1];if(!p){escapeEnemy(e);return}const dx=p.x-e.x,dy=p.y-e.y,dist=Math.hypot(dx,dy),step=e.speed*e.slow*dt;if(dist<=step){e.x=p.x;e.y=p.y;e.pi++}else{e.x+=dx/dist*step;e.y+=dy/dist*step}e.angle=Math.atan2(dy,dx)}
  function escapeEnemy(e){state.enemies.splice(state.enemies.indexOf(e),1);state.lives-=enemyDefs[e.type].boss?3:1;sound("escape");if(state.lives<=0)finish(false)}
  function milestoneRange(t){return(t.type==="pulse"||t.type==="frost"||t.type==="boost")&&t.level>=5?1.25:1}
  function towerRange(t){return towerDefs[t.type].range*2*(1+.1*(t.level-1))*milestoneRange(t)}
  function canTarget(t,e){const air=!!enemyDefs[e.type].air;if(t.type==="swarm")return air;if(t.type==="squirt"||t.type==="bash")return true;return !air}
  function supportingRelays(t){return state.towers.filter(b=>b.type==="boost"&&b!==t&&Math.hypot((b.x+1)-(t.x+1),(b.y+1)-(t.y+1))<=towerRange(b))}
  function abilities(){return state.abilities??={overdriveReady:0,lockdownReady:0,overdriveUntil:0}}
  function runStats(){return state.stats??={kills:0,earned:0,spent:0,leaks:0,early:0,built:0}}
  function useAbility(type){if(!state||state.paused||state.ended)return;const a=abilities(),readyKey=`${type}Ready`;if(state.elapsed<a[readyKey])return;ensureAudio();if(type==="overdrive"){a.overdriveUntil=state.elapsed+6;a.overdriveReady=state.elapsed+45;state.towers.forEach(t=>burst(t.x+1,t.y+1,"#53c8ff",4));ui.status.textContent="Overdrive active · tower systems accelerated."}else{a.lockdownReady=state.elapsed+60;for(const e of state.enemies)e.stun=Math.max(e.stun,1.25);state.pulses.push({x:W/2,y:H/2,r:Math.max(W,H),color:"#c084fc",life:.65,duration:.65});ui.status.textContent="Lockdown pulse · field briefly frozen."}sound("upgrade");updateUI()}
  function relayModifiers(t){const relays=t.type==="boost"?[]:supportingRelays(t);return{relays,damage:1+relays.reduce((n,b)=>n+.12+.02*b.level,0),rate:1+relays.filter(b=>b.level>=10).length*.15}}
  function markRelaysActive(relays){for(const relay of relays)relay.activeUntil=Math.max(relay.activeUntil||0,state.elapsed+.34)}
  function targetSort(t,a,b){switch(t.targeting||((t.type==="rail")?"strongest":"first")){case"last":return a.pi-b.pi;case"strongest":return b.maxHp-a.maxHp;case"weakest":return a.hp-b.hp;case"fastest":return enemyDefs[b.type].speed-enemyDefs[a.type].speed;default:return b.pi-a.pi}}
  function towerStats(t,level=t.level){const d=towerDefs[t.type],probe={...t,level},relay=relayModifiers(t),base=d.support?Math.round((12+.02*level)*100):d.damage*(1+.34*(level-1));let rate=d.rate?Math.pow(1.12,level-1)/d.rate*relay.rate:0;if(t.type==="pellet"&&level>=5)rate*=1.5;return{power:Math.round(base*relay.damage),basePower:Math.round(base),relayPercent:Math.round((relay.damage-1)*100),range:(towerRange(probe)/2).toFixed(1),rate}}
  function updateTower(t,dt){const d=towerDefs[t.type];if(d.support)return;t.cool=(t.cool||0)-dt;if(t.cool>0)return;const relay=relayModifiers(t),boost=relay.damage,rateBoost=relay.rate*(state.elapsed<abilities().overdriveUntil?1.65:1),range=towerRange(t),targets=state.enemies.filter(e=>canTarget(t,e)&&Math.hypot(e.x-(t.x+1),e.y-(t.y+1))<=range);if(!targets.length)return;const power=d.damage*(1+.34*(t.level-1))*boost*(mode.towerPower||1);markRelaysActive(relay.relays);if(d.pulse){targets.forEach(e=>{damageEnemy(e,power,t);if(t.level>=10&&state.enemies.includes(e)){damageEnemy(e,power*.35,t);if(state.enemies.includes(e))e.stun=Math.max(e.stun,.28)}});state.pulses.push({x:t.x+1,y:t.y+1,r:range,color:d.color,life:.46,duration:.46});if(t.level>=10)state.pulses.push({x:t.x+1,y:t.y+1,r:range*1.08,color:"#e9d5ff",life:.68,duration:.68});sound("fire","pulse");t.cool=d.rate/(Math.pow(1.1,t.level-1)*rateBoost);return}targets.sort((a,b)=>targetSort(t,a,b));let count=1;if(t.type==="squirt"&&t.level>=5)count=2;if(t.type==="swarm"&&t.level>=10)count=3;targets.slice(0,count).forEach(target=>launchProjectile(t,target,power));let milestoneRate=t.type==="pellet"&&t.level>=5?1.5:1;t.cool=d.rate/(Math.pow(1.12,t.level-1)*rateBoost*milestoneRate)}
  function launchProjectile(t,target,damage){const speed={pellet:18,squirt:25,bash:9,frost:14,swarm:12,rail:31}[t.type]||18,sx=t.x+1,sy=t.y+1,duration=Math.max(.08,Math.hypot(target.x-sx,target.y-sy)/speed);if(!["pulse","boost"].includes(t.type))t.aim=Math.atan2(target.y-sy,target.x-sx);state.shots.push({x:sx,y:sy,px:sx,py:sy,target,tx:target.x,ty:target.y,type:t.type,color:towerDefs[t.type].color,damage,speed,tower:t,age:0,duration});sound("fire",t.type)}
  function updateProjectiles(dt){for(const p of [...state.shots]){p.age+=dt;p.px=p.x;p.py=p.y;if(state.enemies.includes(p.target)){p.tx=p.target.x;p.ty=p.target.y}const dx=p.tx-p.x,dy=p.ty-p.y,dist=Math.hypot(dx,dy),step=p.speed*dt;if(dist<=step||p.age>2.5){p.x=p.tx;p.y=p.ty;resolveImpact(p);state.shots.splice(state.shots.indexOf(p),1)}else{p.x+=dx/dist*step;p.y+=dy/dist*step}}}
  function damageMatchup(type,armor){const table={light:{kinetic:1.2,explosive:.85},medium:{energy:1.2,kinetic:.9},heavy:{piercing:1.35,explosive:1.15,kinetic:.55},phase:{shock:1.3,energy:1.15,explosive:.7}};return table[armor]?.[type]||1}
  function resolveImpact(p){const e=p.target;if(!state.enemies.includes(e)){burst(p.x,p.y,p.color,3);return}const d=towerDefs[p.type],ed=enemyDefs[e.type],level=p.tower.level;let dealt=p.damage*damageMatchup(d.damageType,ed.armor)*(ed.resist&&!(p.type==="rail"&&level>=5)?Math.max(ed.resist,.72):1)*(e.vulnerable||1);if(ed.morph)dealt*=.75+Math.random()*.5;
    if(p.type==="bash"&&level>=5){const radius=level>=10?2.05:1.25;state.enemies.filter(x=>Math.hypot(x.x-e.x,x.y-e.y)<=radius*2).forEach(x=>damageEnemy(x,dealt*(x===e?1:level>=10?.72:.55),p.tower));state.pulses.push({x:e.x,y:e.y,r:radius*2,color:level>=10?"#fecdd3":d.color,life:.42,duration:.42})}
    else if(p.type==="swarm"&&level>=5){state.enemies.filter(x=>enemyDefs[x.type].air&&Math.hypot(x.x-e.x,x.y-e.y)<=1.2).forEach(x=>damageEnemy(x,dealt*(x===e?1:.5),p.tower))}
    else damageEnemy(e,dealt,p.tower);
    if(d.slow&&state.enemies.includes(e)){e.slow=Math.min(e.slow,level>=10?.38:d.slow);e.slowTime=level>=10?2.2:1.4;if(level>=10){e.vulnerable=1.25;e.vulnerableTime=2.2}}
    if(p.type==="pellet"&&level>=10)chainDamage(e,dealt,p.tower,3,[.55,.35,.2],"#a5f3fc");
    if(p.type==="squirt"&&level>=10)chainDamage(e,dealt,p.tower,1,[.65],d.color);
    if(p.type==="rail"&&level>=10)chainDamage(e,dealt,p.tower,2,[.7,.45],d.color,true);
    burst(p.x,p.y,p.color,p.type==="bash"?13:5);sound("impact",p.type)}
  function chainDamage(origin,damage,tower,count,multipliers,color,forward=false){let from=origin,used=new Set([origin]);for(let i=0;i<count;i++){const candidates=state.enemies.filter(x=>!used.has(x)&&canTarget(tower,x)&&(forward?x.pi>=origin.pi:true)&&Math.hypot(x.x-from.x,x.y-from.y)<=3.2).sort((a,b)=>Math.hypot(a.x-from.x,a.y-from.y)-Math.hypot(b.x-from.x,b.y-from.y)),next=candidates[0];if(!next)break;state.arcs.push({x1:from.x,y1:from.y,x2:next.x,y2:next.y,color,life:.18,seed:Math.random()*10});damageEnemy(next,damage*multipliers[i],tower);used.add(next);from=next}}
  function burst(x,y,color,count){for(let i=0;i<count;i++)state.particles.push({x,y,vx:(Math.random()-.5)*2.5,vy:(Math.random()-.5)*2.5,life:.22+Math.random()*.3,color})}
  function damageEnemy(e,amount,t){const ed=enemyDefs[e.type];if(ed.evade&&Math.random()<ed.evade){state.particles.push({x:e.x,y:e.y,vx:0,vy:-1,life:.3,color:ed.color});return}if(e.type==="boss"&&e.hp/e.maxHp>.55)amount*=.65;e.hp-=amount;if(e.hp>0)return;const idx=state.enemies.indexOf(e);if(idx<0)return;state.enemies.splice(idx,1);const pay=mode.noIncome?0:Math.max(1,Math.round(ed.reward*(1+(state.stage-1)*.08)*(mode.reward??1)));state.cash+=pay;state.score+=Math.round(10*ed.reward+state.wave*.7);for(let i=0;i<7;i++)state.particles.push({x:e.x,y:e.y,vx:(Math.random()-.5)*2,vy:(Math.random()-.5)*2,life:.4+Math.random()*.4,color:ed.color});if(ed.split&&e.depth>0){for(let i=0;i<2;i++)state.enemies.push({...e,hp:e.maxHp*.32,maxHp:e.maxHp*.32,speed:e.speed*1.28,depth:e.depth-1,x:e.x+(i?-.08:.08),pi:e.pi})}}
  function finish(won){state.ended=true;state.paused=true;clearTimeout(state.transitionTimer);clearSavedGame();ui.status.textContent=won?`Run complete · ${state.score} points.`:`The maze fell in round ${state.stage}, wave ${state.stageWave}.`;ui.send.disabled=true;showNotice(won?"Victory":"Game Over",won?`${state.score} points · all five rounds secured`:`Round ${state.stage}, wave ${state.stageWave} · ${state.score} points`,won?"The field is yours":"The line has fallen",won?"victory":"game-over",0);window.GameScores?.record({game:"maze-defense",mode:selectedMode,difficulty:selectedMode,metric:"score",value:state.score,meta:{wave:state.wave,round:state.stage,lives:state.lives,won}})}
  function pointerCell(ev){const r=canvas.getBoundingClientRect();return{x:Math.floor((ev.clientX-r.left)*canvas.width/r.width/C),y:Math.floor((ev.clientY-r.top)*canvas.height/r.height/C)}}
  function selectCell(ev){if(state.ended)return;const{x,y}=pointerCell(ev),existing=towerAt(x,y);if(existing){state.selected=existing;state.build=null;state.hover=null;buildTowerButtons();updateSelection();return}if(!state.build)return;const d=towerDefs[state.build];if(state.cash<d.cost){flash("Not enough credits.");return}if(mode.towerCap&&state.towers.length>=mode.towerCap){flash("This challenge allows only 15 towers.");return}if(!canBuild(x,y)){flash("Every entrance must retain a path to an exit.");return}ensureAudio();sound("build");state.towers.push({type:state.build,x,y,level:1,spent:d.cost,cool:0,targeting:state.build==="rail"?"strongest":"first"});state.cash-=d.cost;state.hover={x,y};refreshPaths();updateUI()}
  function updateAbilityUI(){if(!state)return;const a=abilities(),over=Math.max(0,a.overdriveReady-state.elapsed),lock=Math.max(0,a.lockdownReady-state.elapsed);ui.overdrive.disabled=over>0||state.ended;ui.lockdown.disabled=lock>0||state.ended;ui.overdrive.textContent=state.elapsed<a.overdriveUntil?"Overdrive active":over?`Overdrive ${Math.ceil(over)}s`:"Overdrive";ui.lockdown.textContent=lock?`Lockdown ${Math.ceil(lock)}s`:"Lockdown";ui.overdrive.classList.toggle("ready",!over);ui.lockdown.classList.toggle("ready",!lock)}
  function updateSelection(){updateAbilityUI();const t=state.selected;if(!t){ui.selectionName.textContent=state.build?`Place ${towerDefs[state.build].name}`:"Nothing selected";ui.selectionCopy.textContent=state.build?towerDefs[state.build].desc:"Choose a tower, then place it on an open half-square.";ui.selectionStats.hidden=true;ui.targetingControl.hidden=true;ui.upgrade.disabled=true;ui.sell.disabled=true;return}const d=towerDefs[t.type],p=progression[t.type],cost=Math.round(d.cost*Math.pow(1.42,t.level)*(t.level===4||t.level===9?1.5:1)),cur=towerStats(t),next=towerStats(t,Math.min(10,t.level+1)),powerLabel=d.support?"Boost":"Power",unlocked=t.level>=10?`${p.three.name} + ${p.six.name}`:t.level>=5?p.three.name:"Core systems",boostNote=cur.relayPercent?` <small>(+${cur.relayPercent}% Relay)</small>`:"";ui.selectionName.textContent=`${d.name} · Level ${t.level}`;ui.selectionCopy.textContent=`${d.desc} Active: ${unlocked}.`;ui.selectionStats.hidden=false;ui.selectionStats.innerHTML=`<span></span><strong>Current</strong><strong class="next">${t.level>=10?"Max":"Next"}</strong><span>${powerLabel}</span><strong>${cur.power}${d.support?"%":""}${boostNote}</strong><strong class="next">${next.power}${d.support?"%":""}${boostNote}</strong><span>Range</span><strong>${cur.range}</strong><strong class="next">${next.range}</strong>${d.rate?`<span>Rate</span><strong>${cur.rate.toFixed(1)}/s</strong><strong class="next">${next.rate.toFixed(1)}/s</strong>`:""}${t.level===4?`<span>Unlock</span><strong>Level 5</strong><strong class="next">${p.three.name}</strong>`:t.level===9?`<span>Unlock</span><strong>Level 10</strong><strong class="next">${p.six.name}</strong>`:""}`;ui.targetingControl.hidden=!!(d.support||d.pulse);ui.targeting.value=t.targeting||(t.type==="rail"?"strongest":"first");ui.upgrade.textContent=t.level>=10?"Max level":`Upgrade ${cost}`;ui.upgrade.disabled=t.level>=10||state.cash<cost;ui.sell.textContent=`Sell ${Math.floor(t.spent*.75)}`;ui.sell.disabled=!!mode.noSell}
  function upgrade(){const t=state.selected;if(!t||t.level>=10)return;const d=towerDefs[t.type],cost=Math.round(d.cost*Math.pow(1.42,t.level)*(t.level===4||t.level===9?1.5:1));if(state.cash<cost)return;ensureAudio();sound("upgrade");state.cash-=cost;t.spent+=cost;t.level++;if(t.level===5||t.level===10){state.pulses.push({x:t.x+1,y:t.y+1,r:2.5,color:t.level===10?"#fef08a":d.color,life:.75,duration:.75});burst(t.x+1,t.y+1,t.level===10?"#fef08a":d.color,18)}updateSelection();updateUI()}
  function sell(){const t=state.selected;if(!t||mode.noSell)return;ensureAudio();tone(360,.09,"triangle",.018,-150);state.cash+=Math.floor(t.spent*.75);state.towers.splice(state.towers.indexOf(t),1);state.selected=null;refreshPaths();updateSelection();updateUI()}
  function flash(s){ui.status.textContent=s;canvas.classList.remove("shake");void canvas.offsetWidth;canvas.classList.add("shake")}
  function updateUI(){if(!state)return;const s=stageDef(),limit=stageWaveLimit(),remaining=state.enemies.length+state.spawnQueue.length,lastQueued=state.spawnQueue.reduce((latest,q)=>Math.max(latest,q.at),state.elapsed),deploying=lastQueued>state.elapsed+.05;ui.mode.textContent=mode.name;ui.stage.textContent=`${state.stage} / ${stages.length}`;ui.wave.textContent=`${state.stageWave} / ${Number.isFinite(limit)?limit:"∞"}`;ui.lives.textContent=state.lives;ui.credits.textContent=state.cash;ui.score.textContent=state.score;ui.next.textContent=state.waitingForFirstWave?"Planning time · deploy when ready":state.stageWave<limit?`Auto wave in ${Math.max(0,state.nextTimer).toFixed(1)}s · ${deploying?"deploying":"rest period"}${remaining?` · ${remaining} active`:""}`:`${remaining} creeps remain before round clear`;if(state.stageWave<limit){const rows=[];for(let offset=1;offset<=3&&state.stageWave+offset<=limit;offset++){const w=waveInfo(state.stageWave+offset);rows.push(`<div class="incoming-row"><b>W${state.stageWave+offset}</b><strong>${enemyDefs[w.type].name}</strong><span>${w.count*s.entries.length} · ~${Math.round(w.hp)} HP</span></div>`)}ui.incoming.innerHTML=`<div class="incoming-forecast">${rows.join("")}</div>`}else ui.incoming.textContent=`Clear the field to advance to ${state.stage<stages.length?stageDef(state.stage+1).name:"victory"}.`;ui.send.disabled=state.transitioning||state.stageWave>=limit||state.ended;const bonus=earlyWaveBonus();ui.send.textContent=state.stageWave<limit?`Send wave ${state.stageWave+1}${bonus&&!mode.noIncome?` · +${bonus}`:""}`:"All waves sent";updateSelection()}
  function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);const grad=ctx.createLinearGradient(0,0,960,640);grad.addColorStop(0,"#152c42");grad.addColorStop(1,"#091827");ctx.fillStyle=grad;ctx.fillRect(0,0,960,640);for(let x=0;x<=W;x++){ctx.strokeStyle=x%2?"rgba(148,177,207,.045)":"rgba(148,177,207,.12)";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x*C,0);ctx.lineTo(x*C,640);ctx.stroke()}for(let y=0;y<=H;y++){ctx.strokeStyle=y%2?"rgba(148,177,207,.045)":"rgba(148,177,207,.12)";ctx.beginPath();ctx.moveTo(0,y*C);ctx.lineTo(960,y*C);ctx.stroke()}drawArenaWalls();drawRoutes();if(state){drawBarriers();entries().forEach((e,i)=>drawGate(e.x,e.y,"IN",i));exits().forEach((e,i)=>drawGate(e.x,e.y,"OUT",i));state.towers.forEach(drawTower);drawPlacementGhost();state.enemies.forEach(drawEnemy);state.shots.forEach(drawProjectile);state.arcs.forEach(drawArc);state.pulses.forEach(p=>{const progress=1-p.life/(p.duration||.46);ctx.strokeStyle=p.color;ctx.globalAlpha=Math.max(0,1-progress);ctx.lineWidth=6*Math.max(0,1-progress)+1;ctx.beginPath();ctx.arc(p.x*C,p.y*C,p.r*C*Math.max(0,progress),0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1});state.particles.forEach(p=>{ctx.fillStyle=p.color;ctx.globalAlpha=Math.min(1,p.life*2);ctx.fillRect(p.x*C,p.y*C,3,3);ctx.globalAlpha=1})}if(state?.paused&&!state.ended){ctx.fillStyle="rgba(3,10,18,.62)";ctx.fillRect(0,0,960,640);ctx.fillStyle="#f5f8fc";ctx.font="900 56px Avenir Next";ctx.textAlign="center";ctx.fillText("Paused",480,335)}}
  function drawArc(a){const x1=a.x1*C,y1=a.y1*C,x2=a.x2*C,y2=a.y2*C,segments=7;ctx.save();ctx.strokeStyle=a.color;ctx.shadowColor=a.color;ctx.shadowBlur=10;ctx.globalAlpha=Math.min(1,a.life/.12);ctx.lineWidth=2.5;ctx.beginPath();ctx.moveTo(x1,y1);for(let i=1;i<segments;i++){const q=i/segments,n=Math.sin((i+a.seed)*7.13)*5;ctx.lineTo(x1+(x2-x1)*q+n,y1+(y2-y1)*q-n)}ctx.lineTo(x2,y2);ctx.stroke();ctx.restore()}
  function drawProjectile(p){const progress=Math.min(1,p.age/p.duration),arc=p.type==="bash"?Math.sin(progress*Math.PI)*22:0,x=p.x*C,y=p.y*C-arc,px=p.px*C,py=p.py*C-(p.type==="bash"?Math.sin(Math.max(0,progress-.08)*Math.PI)*22:0),angle=Math.atan2(y-py,x-px);ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.shadowColor=p.color;ctx.shadowBlur=p.type==="rail"?13:7;ctx.fillStyle=p.color;ctx.strokeStyle="#eaf7ff";ctx.lineWidth=1;
    if(p.type==="pellet"){ctx.beginPath();ctx.moveTo(7,0);ctx.lineTo(-4,-3);ctx.lineTo(-4,3);ctx.closePath();ctx.fill()}
    else if(p.type==="squirt"){ctx.beginPath();ctx.ellipse(0,0,5,3,0,0,Math.PI*2);ctx.fill()}
    else if(p.type==="bash"){ctx.fillStyle="#fb7185";ctx.beginPath();ctx.arc(0,0,6,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle="#07111d";ctx.fillRect(-2,-2,4,4)}
    else if(p.type==="frost"){ctx.beginPath();ctx.roundRect(-6,-3,12,6,3);ctx.fill();ctx.stroke();for(let i=0;i<4;i++){ctx.rotate(Math.PI/2);ctx.fillRect(3,-1,5,2)}}
    else if(p.type==="swarm"){ctx.beginPath();ctx.moveTo(9,0);ctx.lineTo(-5,-4);ctx.lineTo(-3,0);ctx.lineTo(-5,4);ctx.closePath();ctx.fill();ctx.fillStyle="#fb923c";ctx.beginPath();ctx.moveTo(-4,-2);ctx.lineTo(-10,0);ctx.lineTo(-4,2);ctx.closePath();ctx.fill()}
    else if(p.type==="rail"){ctx.fillStyle="#fff7ed";ctx.fillRect(-9,-2,18,4);ctx.fillStyle=p.color;ctx.beginPath();ctx.moveTo(12,0);ctx.lineTo(5,-4);ctx.lineTo(5,4);ctx.closePath();ctx.fill()}
    ctx.restore()}
  function drawPlacementGhost(){if(!state.build||!state.hover)return;const{x,y}=state.hover,d=towerDefs[state.build],valid=state.cash>=d.cost&&(!mode.towerCap||state.towers.length<mode.towerCap)&&state.hover.valid,cx=(x+1)*C,cy=(y+1)*C;ctx.save();ctx.fillStyle=valid?"rgba(163,230,53,.14)":"rgba(251,113,133,.18)";ctx.strokeStyle=valid?"rgba(163,230,53,.8)":"rgba(251,113,133,.85)";ctx.lineWidth=2;ctx.fillRect(x*C,y*C,C*2,C*2);ctx.strokeRect(x*C+1,y*C+1,C*2-2,C*2-2);ctx.beginPath();ctx.arc(cx,cy,d.range*40,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=valid?.68:.42;drawTowerGlyph(ctx,state.build,cx,cy,1,1,0);ctx.restore()}
  function drawArenaWalls(){ctx.save();ctx.fillStyle="#07111d";ctx.fillRect(0,0,960,10);ctx.fillRect(0,630,960,10);ctx.fillRect(0,0,10,640);ctx.fillRect(950,0,10,640);ctx.strokeStyle="#35526d";ctx.lineWidth=2;ctx.strokeRect(8,8,944,624);ctx.fillStyle="#66839c";for(let x=28;x<950;x+=60){ctx.beginPath();ctx.arc(x,5,2,0,Math.PI*2);ctx.arc(x,635,2,0,Math.PI*2);ctx.fill()}for(let y=28;y<630;y+=60){ctx.beginPath();ctx.arc(5,y,2,0,Math.PI*2);ctx.arc(955,y,2,0,Math.PI*2);ctx.fill()}ctx.restore()}
  function drawBarriers(){if(!state)return;for(const b of state.barriers){const x=b.x*C,y=b.y*C,w=b.w*C,h=b.h*C;ctx.save();const g=ctx.createLinearGradient(x,y,x+w,y+h);g.addColorStop(0,"#31465a");g.addColorStop(.5,"#172a3b");g.addColorStop(1,"#0a1724");ctx.fillStyle=g;ctx.strokeStyle="#6f8ba4";ctx.lineWidth=3;ctx.beginPath();ctx.roundRect(x+2,y+2,w-4,h-4,7);ctx.fill();ctx.stroke();ctx.strokeStyle="rgba(125,211,252,.22)";ctx.lineWidth=1;for(let q=12;q<w+h;q+=20){ctx.beginPath();ctx.moveTo(x+Math.max(4,q-h),y+Math.min(h-4,q));ctx.lineTo(x+Math.min(w-4,q),y+Math.max(4,q-w));ctx.stroke()}ctx.fillStyle="#a8bed0";for(const px of [x+8,x+w-8])for(const py of [y+8,y+h-8]){ctx.beginPath();ctx.arc(px,py,2.5,0,Math.PI*2);ctx.fill()}ctx.restore()}}
  function drawRoutes(){if(!state||state.stage>3)return;ctx.strokeStyle="rgba(83,200,255,.12)";ctx.lineWidth=18;ctx.lineCap="round";state.paths.filter(Boolean).forEach(p=>{ctx.beginPath();p.forEach((n,i)=>i?ctx.lineTo(n.x*C,n.y*C):ctx.moveTo(n.x*C,n.y*C));ctx.stroke()});ctx.lineCap="butt"}
  function drawGate(x,y,label,i){ctx.fillStyle=label==="IN"?"#53c8ff":"#a3e635";ctx.fillRect(x*C+1,y*C+1,C-2,C-2);ctx.fillStyle="#07111d";ctx.font="900 6px Avenir Next";ctx.textAlign="center";const route=label==="IN"?(stageDef().map[i]??0):i;ctx.fillText(`${label} ${String.fromCharCode(65+route)}`,x*C+C/2,y*C+C/2+2)}
  function drawTower(t){const d=towerDefs[t.type],cx=(t.x+1)*C,cy=(t.y+1)*C;t.renderAim??=t.aim||0;const delta=Math.atan2(Math.sin((t.aim||0)-t.renderAim),Math.cos((t.aim||0)-t.renderAim));t.renderAim+=delta*.18;ctx.save();if(t===state.selected){ctx.strokeStyle="rgba(83,200,255,.4)";ctx.lineWidth=2;ctx.beginPath();ctx.arc(cx,cy,towerRange(t)*C,0,Math.PI*2);ctx.stroke()}const angle=t.type==="boost"&&state.elapsed<(t.activeUntil||0)?state.elapsed*9:t.renderAim;drawTowerGlyph(ctx,t.type,cx,cy,1,t.level,angle);ctx.restore()}
  function drawTowerGlyph(g,type,cx,cy,scale=1,level=1,angle=0){const d=towerDefs[type],s=scale,rotates=["pellet","squirt","bash","frost","swarm","rail","boost"].includes(type);g.save();g.translate(cx,cy);g.shadowColor=d.color;g.shadowBlur=5*s;g.fillStyle="#081522";g.strokeStyle=d.color;g.lineWidth=2*s;g.beginPath();g.roundRect(-15*s,-15*s,30*s,30*s,7*s);g.fill();g.stroke();g.shadowBlur=0;g.fillStyle=d.color;g.strokeStyle=d.color;g.save();if(rotates)g.rotate(angle);
    if(type==="pellet"){g.beginPath();g.moveTo(-7*s,8*s);g.lineTo(0,-10*s);g.lineTo(7*s,8*s);g.closePath();g.fill();g.fillRect(3*s,-2*s,15*s,4*s)}
    else if(type==="squirt"){g.beginPath();g.arc(-3*s,0,8*s,0,Math.PI*2);g.fill();g.fillRect(3*s,-7*s,14*s,5*s);g.fillRect(3*s,3*s,14*s,5*s)}
    else if(type==="bash"){g.beginPath();g.arc(0,0,10*s,0,Math.PI*2);g.fill();g.fillStyle="#081522";g.beginPath();g.arc(0,0,5*s,0,Math.PI*2);g.fill();g.fillStyle=d.color;g.fillRect(2*s,-5*s,14*s,10*s)}
    else if(type==="pulse"){for(let r=4;r<=11;r+=4){g.globalAlpha=.35+r/20;g.beginPath();g.arc(0,0,r*s,0,Math.PI*2);g.stroke()}g.globalAlpha=1;g.beginPath();g.arc(0,0,4*s,0,Math.PI*2);g.fill()}
    else if(type==="frost"){for(let i=0;i<6;i++){g.rotate(Math.PI/3);g.fillRect(0,-1.5*s,13*s,3*s);g.fillRect(7*s,-5*s,2*s,10*s)}}
    else if(type==="swarm"){for(let y=-1;y<=1;y+=2)for(let x=-1;x<=1;x+=2){g.beginPath();g.roundRect((x*6-3)*s,(y*6-3)*s,6*s,6*s,2*s);g.fill()}g.fillRect(8*s,-3*s,9*s,6*s)}
    else if(type==="rail"){g.fillRect(-8*s,-5*s,21*s,10*s);g.fillStyle="#081522";g.fillRect(-4*s,-2*s,15*s,4*s);g.fillStyle=d.color;g.fillRect(11*s,-2*s,9*s,4*s)}
    else if(type==="boost"){g.beginPath();g.arc(0,0,5*s,0,Math.PI*2);g.fill();for(let i=0;i<4;i++){g.rotate(Math.PI/2);g.fillRect(4*s,-2*s,12*s,4*s)}g.strokeStyle=d.color;g.beginPath();g.arc(0,0,12*s,0,Math.PI*2);g.stroke()}g.restore();
    if(level>=5){g.save();g.strokeStyle="#e2e8f0";g.lineWidth=1.5*s;g.globalAlpha=.9;for(let i=0;i<4;i++){g.rotate(Math.PI/2);g.beginPath();g.moveTo(10*s,-17*s);g.lineTo(17*s,-17*s);g.lineTo(17*s,-10*s);g.stroke()}g.restore()}
    if(level>=10){g.save();g.strokeStyle="#fef08a";g.fillStyle="#fef08a";g.lineWidth=1.5*s;g.shadowColor="#fde047";g.shadowBlur=8*s;g.beginPath();for(let i=0;i<6;i++){const a=-Math.PI/2+i*Math.PI/3,x=Math.cos(a)*20*s,y=Math.sin(a)*20*s;i?g.lineTo(x,y):g.moveTo(x,y)}g.closePath();g.stroke();for(let i=0;i<3;i++){const a=state?state.elapsed*1.8+i*Math.PI*2/3:i*Math.PI*2/3;g.beginPath();g.arc(Math.cos(a)*20*s,Math.sin(a)*20*s,2.2*s,0,Math.PI*2);g.fill()}g.restore()}
    g.fillStyle="#fff";g.font=`800 ${7*s}px Avenir Next`;g.textAlign="center";g.fillText(level,0,3*s);g.restore()}
  function drawEnemy(e){const d=enemyDefs[e.type],x=e.x*C,y=e.y*C,bob=Math.sin(state.elapsed*5+e.phase)*1.4,r=d.boss?17:9;ctx.save();ctx.translate(x,y+bob);ctx.rotate(e.angle);ctx.fillStyle=d.color;ctx.strokeStyle="#07111d";ctx.lineWidth=2;ctx.shadowColor=d.color;ctx.shadowBlur=7;
    if(e.type==="normal"){ctx.beginPath();ctx.arc(0,0,9,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle="#07111d";ctx.fillRect(1,-3,8,6)}
    else if(e.type==="fast"){ctx.beginPath();ctx.moveTo(13,0);ctx.lineTo(-8,-8);ctx.lineTo(-3,0);ctx.lineTo(-8,8);ctx.closePath();ctx.fill();ctx.stroke()}
    else if(e.type==="spawn"){ctx.beginPath();for(let i=0;i<6;i++){const a=i*Math.PI/3;ctx.lineTo(Math.cos(a)*10,Math.sin(a)*10)}ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle="#07111d";ctx.beginPath();ctx.arc(3,0,3,0,Math.PI*2);ctx.fill()}
    else if(e.type==="dark"){ctx.beginPath();ctx.moveTo(11,0);ctx.lineTo(4,9);ctx.lineTo(-10,7);ctx.lineTo(-6,0);ctx.lineTo(-10,-7);ctx.lineTo(4,-9);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle="#07111d";ctx.fillRect(-2,-7,4,14)}
    else if(e.type==="morph"){const rr=9+Math.sin(state.elapsed*7+e.phase)*2;ctx.beginPath();for(let i=0;i<8;i++){const a=i*Math.PI/4,q=i%2?rr*.65:rr;ctx.lineTo(Math.cos(a)*q,Math.sin(a)*q)}ctx.closePath();ctx.fill();ctx.stroke()}
    else if(e.type==="flying"){ctx.beginPath();ctx.moveTo(14,0);ctx.lineTo(-8,-9);ctx.lineTo(-4,0);ctx.lineTo(-8,9);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle="#07111d";ctx.fillRect(-2,-2,8,4)}
    else if(e.type==="armored"){ctx.beginPath();ctx.moveTo(11,0);ctx.lineTo(6,9);ctx.lineTo(-8,8);ctx.lineTo(-12,0);ctx.lineTo(-8,-8);ctx.lineTo(6,-9);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle="#07111d";ctx.fillRect(-5,-4,12,8);ctx.strokeStyle="#e2e8f0";ctx.strokeRect(-5,-4,12,8)}
    else if(e.type==="regen"){ctx.beginPath();ctx.arc(0,0,10,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle="#07111d";ctx.fillRect(-2,-7,4,14);ctx.fillRect(-7,-2,14,4)}
    else if(e.type==="phaser"){ctx.globalAlpha=.55+.25*Math.sin(state.elapsed*8+e.phase);ctx.beginPath();ctx.moveTo(12,0);ctx.lineTo(0,9);ctx.lineTo(-12,0);ctx.lineTo(0,-9);ctx.closePath();ctx.fill();ctx.stroke();ctx.globalAlpha=1}
    else if(e.type==="hiveboss"){ctx.beginPath();for(let i=0;i<10;i++){const a=i*Math.PI/5,q=i%2?12:18;ctx.lineTo(Math.cos(a)*q,Math.sin(a)*q)}ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle="#07111d";ctx.beginPath();ctx.arc(4,0,6,0,Math.PI*2);ctx.fill()}
    else if(e.type==="airboss"){ctx.beginPath();ctx.moveTo(22,0);ctx.lineTo(-10,-15);ctx.lineTo(-5,-4);ctx.lineTo(-18,0);ctx.lineTo(-5,4);ctx.lineTo(-10,15);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle="#07111d";ctx.fillRect(-2,-4,12,8)}
    else{ctx.beginPath();ctx.roundRect(-17,-12,34,24,7);ctx.fill();ctx.stroke();ctx.fillStyle="#07111d";ctx.beginPath();ctx.arc(5,0,6,0,Math.PI*2);ctx.fill();ctx.strokeStyle=d.color;ctx.beginPath();ctx.arc(-8,0,6,0,Math.PI*2);ctx.stroke()}
    ctx.shadowBlur=0;ctx.restore();ctx.fillStyle="rgba(2,8,15,.8)";ctx.fillRect(x-12,y-r-8,24,3);ctx.fillStyle=e.hp/e.maxHp>.5?"#a3e635":e.hp/e.maxHp>.2?"#facc15":"#fb7185";ctx.fillRect(x-12,y-r-8,24*Math.max(0,e.hp/e.maxHp),3)}
  function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(state)update(dt);draw();raf=requestAnimationFrame(loop)}
  function updateAudioButton(){ui.audio.textContent=audioEnabled?"Sound on":"Sound off";ui.audio.setAttribute("aria-pressed",String(audioEnabled))}
  function renderProgression(){ui.progressionList.innerHTML="";Object.entries(towerDefs).forEach(([id,t])=>{const p=progression[id],card=document.createElement("article"),header=document.createElement("header"),icon=document.createElement("canvas");card.className="progression-card";icon.width=104;icon.height=104;header.append(icon);header.insertAdjacentHTML("beforeend",`<div><h3>${t.name}</h3><span>${p.targets} · ${p.special}</span></div>`);card.append(header);card.insertAdjacentHTML("beforeend",`<div class="progression-tier"><b>Level 5</b><strong>${p.three.name}</strong><p>${p.three.desc}</p></div><div class="progression-tier"><b>Level 10</b><strong>${p.six.name}</strong><p>${p.six.desc}</p></div>`);ui.progressionList.append(card);drawTowerGlyph(icon.getContext("2d"),id,52,52,2.15,10,0)})}
  function drawEnemyPreview(g,id){const d=enemyDefs[id],cx=52,cy=52,r=d.boss?25:17;g.save();g.translate(cx,cy);g.shadowColor=d.color;g.shadowBlur=15;g.fillStyle=d.color;g.strokeStyle="#07111d";g.lineWidth=4;if(d.air){g.beginPath();g.moveTo(r,0);g.lineTo(-r*.55,-r*.7);g.lineTo(-r*.25,0);g.lineTo(-r*.55,r*.7);g.closePath()}else if(id==="phaser"){g.globalAlpha=.68;g.beginPath();g.moveTo(r,0);g.lineTo(0,r*.75);g.lineTo(-r,0);g.lineTo(0,-r*.75);g.closePath()}else if(id==="hiveboss"||id==="morph"){g.beginPath();for(let i=0;i<10;i++){const a=i*Math.PI/5,q=i%2?r*.62:r;g.lineTo(Math.cos(a)*q,Math.sin(a)*q)}g.closePath()}else if(id==="armored"||id==="dark"){g.beginPath();for(let i=0;i<6;i++){const a=i*Math.PI/3;g.lineTo(Math.cos(a)*r,Math.sin(a)*r)}g.closePath()}else{g.beginPath();g.arc(0,0,r,0,Math.PI*2)}g.fill();g.stroke();g.shadowBlur=0;g.fillStyle="#07111d";if(id==="regen"){g.fillRect(-3,-11,6,22);g.fillRect(-11,-3,22,6)}else if(id==="spawn"||id==="hiveboss"){g.beginPath();g.arc(4,0,6,0,Math.PI*2);g.fill()}else{g.fillRect(1,-4,Math.max(8,r*.7),8)}g.restore()}
  function renderEnemyGuide(){ui.enemyList.innerHTML="";Object.entries(enemyGuide).forEach(([id,guide])=>{const d=enemyDefs[id],card=document.createElement("article"),icon=document.createElement("canvas"),copy=document.createElement("div");card.className="enemy-card";icon.width=104;icon.height=104;copy.innerHTML=`<h3>${d.name}</h3><span class="enemy-arrival">${guide.arrival}</span><p>${guide.ability}</p><div class="enemy-stats"><span>${d.air?"Air":"Ground"}</span>${d.armor?`<span>${d.armor} armor</span>`:""}<span>Health ${d.hp}×</span><span>Speed ${d.speed}×</span><span>Reward ${d.reward}</span></div>`;card.append(icon,copy);ui.enemyList.append(card);drawEnemyPreview(icon.getContext("2d"),id)})}
  canvas.addEventListener("pointerdown",selectCell);canvas.addEventListener("pointermove",ev=>{if(state?.build){const p=pointerCell(ev);if(!state.hover||p.x!==state.hover.x||p.y!==state.hover.y)state.hover={...p,valid:canBuild(p.x,p.y)}}});canvas.addEventListener("pointerleave",()=>{if(state)state.hover=null});ui.begin.onclick=startGame;ui.continueGame.onclick=restoreGame;ui.send.onclick=()=>sendWave(true);ui.upgrade.onclick=upgrade;ui.sell.onclick=sell;ui.targeting.onchange=()=>{if(state?.selected){state.selected.targeting=ui.targeting.value;updateSelection();saveGame()}};ui.progression.onclick=()=>{renderProgression();ui.progressionDialog.showModal()};ui.progressionClose.onclick=()=>ui.progressionDialog.close();ui.progressionDialog.addEventListener("click",e=>{if(e.target===ui.progressionDialog)ui.progressionDialog.close()});ui.enemies.onclick=()=>{renderEnemyGuide();ui.enemyDialog.showModal()};ui.enemyClose.onclick=()=>ui.enemyDialog.close();ui.enemyDialog.addEventListener("click",e=>{if(e.target===ui.enemyDialog)ui.enemyDialog.close()});ui.audio.onclick=()=>{audioEnabled=!audioEnabled;localStorage.setItem("jasondaemon.maze-defense.sound",audioEnabled?"on":"off");updateAudioButton();if(audioEnabled){ensureAudio();tone(520,.08,"triangle",.02,180)}};ui.pause.onclick=()=>{if(!state)return;state.paused=!state.paused;ui.pause.textContent=state.paused?"Resume":"Pause";if(state.paused)saveGame();last=performance.now()};ui.speed.onclick=()=>{if(!state)return;state.speed=state.speed===1?2:state.speed===2?3:1;ui.speed.textContent=`${state.speed}× speed`};$("#new-game").onclick=()=>{cancelAnimationFrame(raf);if(state){clearTimeout(state.noticeTimer);clearTimeout(state.transitionTimer)}clearSavedGame();hideNotice();ui.game.hidden=true;ui.start.hidden=false;state=null;draw()};document.addEventListener("visibilitychange",()=>{if(document.hidden&&state&&!state.ended){state.paused=true;ui.pause.textContent="Resume";saveGame()}});window.addEventListener("pagehide",saveGame);
  ui.overdrive.onclick=()=>useAbility("overdrive");ui.lockdown.onclick=()=>useAbility("lockdown");
  updateAudioButton();updateContinueButton();renderModes();draw();
})();
